### ISSUE TITLE
Add-on signing blocks this experiment

### ISSUE THREAD

**Issue by Casonctin** [bwinton/SnoozeTabs#10]
Firefox new add-on signing is blocks this experiment.

**Comment by bwinton** [comment]
Based on [this article](http://www.ghacks.net/2015/08/11/snoozetabs-for-firefox-is-the-first-mozilla-idea-town-add-on/), SnoozeTabs may be intended to be installed through IdeaTown, so perhaps this is intended…  :wink:

(No, not really.  I suspect the only way around this will be to submit the add-on to addons.mozilla.org, which isn’t a huge priority in the next little while, but I will probably get around to it in a while…  And thank you for the bug report!)

**Comment by rugk** [comment]
Any news?
https://discourse.mozilla-community.org/t/whats-happening-to-snoozetabs/5907

**Comment by eterps** [comment]
There is currently no way to use this addon?

**Comment by bwinton** [comment]
Well, I signed it, and put a [new copy up](http://people.mozilla.org/~bwinton/snoozetabs/) but there seems to be a problem with the bookmarks somewhere between [this line](https://github.com/bwinton/SnoozeTabs/blob/master/lib/snooze.js#L38) and [this line](https://github.com/bwinton/SnoozeTabs/blob/master/lib/snooze.js#L42).

**Comment by rugk** [comment]
Nice, so as you have signed it now I think this issue can be closed. You may track the other bookmark problem in another issue.

**Comment by bwinton** [comment]
Sounds good.  Thanks for the comment!
