### ISSUE TITLE
"Snooze Tab until..." context-menu option is disabled for any website after opening a new tab

### ISSUE THREAD

**Issue by SoftVision-EmilPasca** [bwinton/SnoozeTabs#109]
[Affected versions]:
- Nightly 53.0a1
- Snooze Tabs 1.0 (built on 1/19/2017)

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Have a Firefox profile with the latest Snooze Tabs add-on version (1.0-dev, built on 1/19/2017) loaded as a temporary add-on.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisite and navigate to multiple websites.
2. Open a new tab.
3. Refocus any of the websites tabs and right-click them.
4. Observe the "Snooze Tab until.." context-menu option.

[Expected result]:
- "Snooze Tab until..." context-menu option is available.

[Actual result]:
- "Snooze Tab until..." context-menu option is disabled(grayed out).

[Notes]:
- This issue occurs for all the websites opened before a new tab is opened.
- Attached a screen recording of the issue:
![snoozetabs_context-menu-issue](https://cloud.githubusercontent.com/assets/20083658/22117147/8831348e-de7b-11e6-84c4-8ce68e38833d.gif)

**Comment by SoftVision-EmilPasca** [comment]
This issue occurs if opening an "about:addons", "about:preferences" or other similar tab instead of a new tab.

**Comment by ckprice** [comment]
Could use some research/repro

**Comment by pdehaan** [comment]
I can repro this on macOS Sierra w/ Nightly.

![blank_skitch_document](https://cloud.githubusercontent.com/assets/557895/22482632/a8fad40e-e7ae-11e6-9bc2-df737a8236ca.png)

Only one suspicious looking thing in the Browser Console:

![browser_console_and__snooze_tab_until_____context-menu_option_is_disabled_for_any_website_after_opening_a_new_tab_ _issue__109_ _bwinton_snoozetabs_and_file____users_pdehaan_dev_github_mozilla_snoozetabs_dist_background_js](https://cloud.githubusercontent.com/assets/557895/22482701/048187f0-e7af-11e6-9da8-a0f6d12aa25c.png)

> "ReferenceError: reference to undefined property 2[Learn More]  (background.js:795:29)"

![file____users_pdehaan_dev_github_mozilla_snoozetabs_dist_background_js_and__snooze_tab_until_____context-menu_option_is_disabled_for_any_website_after_opening_a_new_tab_ _issue__109_ _bwinton_snoozetabs](https://cloud.githubusercontent.com/assets/557895/22482784/54face6c-e7af-11e6-9745-0f71a24c9288.png)

Looks like the error may be coming from **moment**?

**Comment by SoftVision-EmilPasca** [comment]
The issue is no longer reproducible on the latest Snooze Tabs version (1.0.9 built on 02/07/2017).
