### ISSUE TITLE
SnoozeTabs Panel Redesign

### ISSUE THREAD

**Issue by sevaan** [bwinton/SnoozeTabs#11]
[Removed old design]

**Comment by rugk** [comment]
:+1: Yes this looks much nicer!

**Comment by johngruen** [comment]
guess what...we've got a new design

**Comment by bwinton** [comment]
(From @sevaan) Proposed UX: https://mozilla.invisionapp.com/share/MV9F846SY

**Comment by rugk** [comment]
Nice! There is just one issue: The glowing for "tab return" looks a bit silly.

**Comment by sevaan** [comment]
> Nice! There is just one issue: The glowing for "tab return" looks a bit silly.

This is just our MVP, using existing mechanisms in Firefox. The glow comes from the Send Tab feature where you can send a tab to Firefox from another device. We're just going to use it for now to get a first version out there, and then build on it.

**Comment by rugk** [comment]
>  The glow comes from the Send Tab feature where you can send a tab to Firefox from another device.

Okay, in this case I never noticed it. :pensive:

**Comment by sevaan** [comment]
Yes, we'll definitely improve it. For those that don't notice it, hopefully the system notification will catch their eye.

We also have some sketches and ideas where a list of returned tabs could live in the snooze tabs panel, with a notification badge on the toolbar icon, which doesn't clear until the user interacts with it.

Baby steps!

**Comment by parag9d** [comment]
Hi, all the iconography used in the revamped UI have been added here: https://www.dropbox.com/sh/x88v1s4xikh356m/AABXcIc7nP7YXJg2dxcG1luLa?dl=0

**Comment by parag9d** [comment]
@sevaan The UX for the confirmation feedback is yet to be added I guess. What happens after the user clicks on an option, before the closing of the panel?

**Comment by sevaan** [comment]
Nothing. The panel closes and the icon jumps. It’s just sent away, exactly the way snoozing mail works. We removed the confirmation stuff for the MVP, because it’s an extra step that the user would have to click out of each time.

On Mon, Nov 21, 2016 at 10:34 AM rugk

<
mailto:rugk <notifications@github.com>
> wrote:

a, pre, code, a:link, body { word-wrap: break-word !important; }

The glow comes from the Send Tab feature where you can send a tab to Firefox from another device.

Okay, in this case I never noticed it.

😔

—

You are receiving this because you were mentioned.

Reply to this email directly,
https://github.com/bwinton/SnoozeTabs/issues/11#issuecomment-261971141
, or

**Comment by parag9d** [comment]
I was thinking of something like this: https://www.dropbox.com/s/fcayh38gtlx932p/Interaction%201.gif?dl=0

**Comment by sevaan** [comment]
That looks okay. Blake, you were mentioning that bouncing the icon might be hard for the MVP. Maybe something like this could be an alternative.

**Comment by lmorchard** [comment]
In interests of clearing up issues, can this be considered done / have follow up issues filed?

**Comment by bwinton** [comment]
I'ld like to get the date/time stuff a little closer to the existing spec before I would call this done…
(Or at least get @sevaan's sign off on the current stuff. 🙂)

**Comment by lmorchard** [comment]
Ah, yeah, the current date/time component is just out-of-box rc-calendar defaults and not at all tweaked to match the spec

**Comment by sevaan** [comment]
Can we edit the calendar control to lose the Now option and to put a time selector on the same panel (rather than having the user switch views)? @bwinton found a pretty good time selector here: https://react-component.github.io/time-picker/examples/disabled.html

**Comment by bwinton** [comment]
Turns out that's the time picker we're already using.  I don't know how to hook it up correctly, but that's why we have this bug, right?  🙂

**Comment by ckprice** [comment]
Let's open an 'style calendar picker issue' and close this.
