### ISSUE TITLE
[Enhancement] Hover state is missing from the "Manage Snoozed Tabs" and "Back" buttons

### ISSUE THREAD

**Issue by SoftVision-EmilPasca** [bwinton/SnoozeTabs#113]
[Affected versions]:
- Nightly 53.0a1
- Snooze Tabs 1.0 (built on 1/20/2017)

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Have a Firefox profile with the latest Snooze Tabs add-on version (1.0-dev, built on 1/20/2017) loaded as a temporary add-on.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisite and navigate to any website.
2. Click the "Snooze Tabs" icon from the main browser toolbar.
3. Hover the "Manage Snoozed Tabs" button.
4. Click on the "Manage Snoozed Tabs" button.
5. Hover the "Back" button.

[Expected result]:
- When hovering the "Manage Snoozed Tabs" or the "Back" button, it gains a darker overlay.

[Actual result]:
- When hovering the "Manage Snoozed Tabs" or the "Back" button, it remains unchanged.

[Notes]:
- The same behavior occurs for "Pick a date " section bottom part buttons.
- Attached a screen recording of the issue:
![snoozetabs_hoverissue](https://cloud.githubusercontent.com/assets/20083658/22152022/878e635e-df29-11e6-8c8c-7f4c027c2940.gif)

**Comment by bwinton** [comment]
@sevaan Can I get some hex values for those?  (Also for the blue "Snooze!" button"?)

**Comment by sevaan** [comment]
Let's use the colours and styling from here: https://firefoxux.github.io/StyleGuide/#/buttons

Grey Buttons
- Normal: #FBFBFB
- Hover: #EBEBEB
- Pressed: #D4D4D4

Blue Buttons
- Normal: #0094FB
- Hover: #006ECF
- Pressed: #0059AE

**Comment by pdehaan** [comment]
When managing snoozes, I noticed that the horizontal separator lines don't always extend 100% width.

Plus, the little doorhanger arrow looks black instead of white.

![menubar_and_nightly_start_page_and__enhancement__hover_state_is_missing_from_the__manage_snoozed_tabs__and__back__buttons_ _issue__113_ _bwinton_snoozetabs](https://cloud.githubusercontent.com/assets/557895/22266348/88a8747e-e234-11e6-867f-455ce75e8e84.png)

**Comment by SoftVision-EmilPasca** [comment]
The issue is no longer reproducible on the latest Snooze Tabs version (1.0.9 built on 02/02/2017).
