### ISSUE TITLE
[Enhancement] "Manage Snoozed Tabs" panel should remain displayed after deleting a snoozed tab from the list

### ISSUE THREAD

**Issue by SoftVision-EmilPasca** [bwinton/SnoozeTabs#114]
[Notes]:
- As a user, I would like to remove multiple tabs from the list without needing to open the list again for each tab that I want out.

[Affected versions]:
- Nightly 53.0a1
- Snooze Tabs 1.0 (built on 1/20/2017)

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Have a Firefox profile with the latest Snooze Tabs add-on version (1.0-dev, built on 1/20/2017) loaded as a temporary add-on.
- Have a few snoozed tabs in the "Manage Snoozed Tabs" panel.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisite and navigate to any website.
2. Click the "Snooze Tabs" icon from the main browser toolbar.
3. Click on the "Manage Snoozed Tabs" button.
4. Remove a snoozed tab from the "Manage Snoozed Tabs" panel.

[Expected result]:
- The "Manage Snoozed Tabs" panel doesn't slides over after removing a snoozed tab.

[Actual result]:
- The "Manage Snoozed Tabs" panel slides over after removing a snoozed tab.

[Additional Notes]:
- The requested behavior is already available for "about: " pages since there you don't have the option to snooze them, just to see the snoozed ones.
- Attached a screen recording of the issue:
![snoozetabs_delete_item](https://cloud.githubusercontent.com/assets/20083658/22157792/d1a20050-df41-11e6-9923-889a455e9909.gif)

**Comment by lmorchard** [comment]
I think this is fixed with https://github.com/bwinton/SnoozeTabs/pull/240

**Comment by SoftVision-EmilPasca** [comment]
The issue is no longer reproducible on the latest Snooze Tabs version (1.0.15-dev built on 03/07/2017).
