### ISSUE TITLE
Need prettier blank state for manage tabs

### ISSUE THREAD

**Issue by pdehaan** [bwinton/SnoozeTabs#118]
```sh
$ git rev-parse --short HEAD # dc9b49d
```

### Steps to reproduce:
```sh
$ nvm use 6
$ npm install
$ npm start
```

### Actual results:
![firefox_developer_edition_and_new_issue_ _bwinton_snoozetabs](https://cloud.githubusercontent.com/assets/557895/22228676/a1dbab12-e187-11e6-8083-0df3dff97a73.png)

### Expected results:
My browser is launched with a "New Tab" experience.
Clicking the "SnoozeTabs" button brings up an empty **Manage Snoozed Tabs** panel, since this is first run and the first time I've interacted with the button.

**Comment by sevaan** [comment]
![screen shot 2017-01-27 at 11 18 56 am](https://cloud.githubusercontent.com/assets/473531/22378110/6b2c9f06-e482-11e6-81e5-7429b62f03ef.png)

Colour of logo and text: #B1B1B1
Logo is 64x64 and Text is 14pt.
