### ISSUE TITLE
Some blurry favicons

### ISSUE THREAD

**Issue by pdehaan** [bwinton/SnoozeTabs#119]
```sh
$ git rev-parse --short HEAD # dc9b49d
```

A few randomly spotted favicons.

![favicon_ico__icon_image__16 x 16_pixels__and_q1_2017_goals](https://cloud.githubusercontent.com/assets/557895/22229081/56bcc96a-e18a-11e6-8933-232a3eb35aef.png)

SFGate favicon seems to be http://www.sfgate.com/favicon.ico
Bogus 404 favicon from http://www.404inator.com/favicon.ico seems to be some Firefox served favicon.

Not sure if either is easily fixable, or if we just have to deal with poor favicons.
In Activity Stream, we did a few calculations to determine favicon size and use fallbacks to [tippy-top-sites](https://github.com/mozilla/tippy-top-sites).

**Comment by pdehaan** [comment]
Here's a few more examples from more random sites while verifying a PR:

![firefox_developer_edition_start_page_and_library](https://cloud.githubusercontent.com/assets/557895/22229566/552990a8-e18d-11e6-927c-9cdc1ace6f5a.png)

1. http://www.today.com/favicon.ico (16x16 favicon)
1. http://tonight.com/favicon.ico (404)
1. http://ww1.tomorrow.com/ (favicon is a blurry 16x16 `<link rel="shortcut icon" type="image/png" href="data:image/png;base64,iVBOR...==" />`)
1. http://thisweekend.com/favicon.ico (404)
1. http://nextweek.com (favicon is a `<link rel="Shortcut Icon" href="http://images.smartname.com/images/template/favicon.ico">` which seems to do a download of the image when i try and fetch it directly).

**Comment by sevaan** [comment]
Is it possible to sample a colour from the favicons? For smaller icons, we could keep them at 16x16, but center them in a coloured box that is the correct size. Is this possible?

**Comment by wresuolc** [comment]
Activity stream might have some code to sample colours from favicons

**Comment by lmorchard** [comment]
The needs-ux label's gone, but I want to say we had some discussion on this last week and ended with not being able to sample a color. Do we have another solution for this? I can't remember

**Comment by ckprice** [comment]
Let's make the favicons half size.
