### ISSUE TITLE
Bookmarks not getting called back.

### ISSUE THREAD

**Issue by bwinton** [bwinton/SnoozeTabs#12]
There seems to be a problem with the bookmarks somewhere between [this line](https://github.com/bwinton/SnoozeTabs/blob/master/lib/snooze.js#L38) and [this line](https://github.com/bwinton/SnoozeTabs/blob/master/lib/snooze.js#L42).

**Comment by rugk** [comment]
So it's in these lines: https://github.com/bwinton/SnoozeTabs/blob/master/lib/snooze.js#L38-L42 :smile: (you can mark multiple lines on GitHub)

**Comment by bwinton** [comment]
Sort of, although it's really a problem in the unseen library code between the call and the (not firing) callback…
(The multiple lines thing is neat, though.  ;)
