### ISSUE TITLE
Doorhanger view changes if you're managing snoozed tabs while tab is automatically unsnoozed

### ISSUE THREAD

**Issue by pdehaan** [bwinton/SnoozeTabs#124]
Found in 57340e7

---

### Steps to reproduce:
1. Snooze a few tabs into the future (an hour or two will do).
1. Snooze a new tab for "Real Soon Now!" which should snooze it for a few seconds.
1. Before the latest tab has managed to unsnooze, open the SnoozeTabs doorhanger and switch to the "Manage Snoozed Tabs" view.
1. Wait.

### Actual results:
Before the tab has been unsnoozed, the visible panel is Manage Snoozed Tabs.
After the tab has been unsnoozed, the visible panel changes.

### Expected results:
The doorhanger panel should not change as the tab is unsnoozed.

**Comment by pdehaan** [comment]
![snooze-tabs-awaken](https://cloud.githubusercontent.com/assets/557895/22315106/a30639d8-e319-11e6-98e2-b5e009b104bd.gif)

**Comment by lmorchard** [comment]
I think this is fixed with https://github.com/bwinton/SnoozeTabs/pull/240
