### ISSUE TITLE
After deleting an item from the "Snoozed Tabs" folder in the Library, the item is still displayed in the "Manage Snoozed Tabs" panel

### ISSUE THREAD

**Issue by SoftVision-EmilPasca** [bwinton/SnoozeTabs#126]
[Notes]:
- After restarting the browser or snoozing a new tab, the previously deleted bookmarked item from the "Snoozed Tabs" folder is added back.

[Affected versions]:
- Nightly 54.0a1
- Snooze Tabs 1.0.9 (built on 1/31/2017)

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Have a Firefox profile with the latest Snooze Tabs add-on version (1.0.9 -dev, built on 1/31/2017) loaded as a temporary add-on.
- Have a few snoozed tabs in the "Manage Snoozed Tabs" panel.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisite and navigate to any website.
2. Open the Library(Ctrl+Shift+B).
3. Delete one of the bookmarked items from the "Snoozed Tabs" folder.
4. Click the "Snooze Tabs" icon from the main browser toolbar.
5. Click on the "Manage Snoozed Tabs" button and search for the deleted bookmark.

[Expected result]:
- The deleted item is no longer displayed in the "Manage Snoozed Tabs" panel.

[Actual result]:
- The deleted item is still displayed in the "Manage Snoozed Tabs" panel.

[Additional Notes]:
- Deleting an item from "Manage Snoozed Tabs" panel also deletes it from bookmarks folder so I assume that should also work the other way around. 
- Attached a screen recording of the issue:
![snoozetabs_bookmarkmanager](https://cloud.githubusercontent.com/assets/20083658/22468390/c093a0ec-e7d0-11e6-9198-92756ca1f0f1.gif)

**Comment by bwinton** [comment]
Yes.  This is by design.  The Snoozed Tabs folder is a workaround for not knowing when we're being uninstalled, not an alternative access point.  Perhaps we should name it something different, to make that clearer?

**Comment by sevaan** [comment]
> Deleting an item from "Manage Snoozed Tabs" panel also deletes it from bookmarks folder so I assume that should also work the other way around.

I think it should work this way too.

**Comment by ckprice** [comment]
Putting into Next for now, but maybe @johngruen wants to increase priority. Could get seen/confuse some people.

**Comment by bwinton** [comment]
Yeah, I think we aren't going to implement this, since we hope that this folder won't exist until SnoozeTabs is uninstalled in the future…
