### ISSUE TITLE
Measure domains of snoozed tab URLs?

### ISSUE THREAD

**Issue by lmorchard** [bwinton/SnoozeTabs#127]
The metrics plan so far has no mention of measuring anything about the kinds of sites that get snoozed. Noticed that min-vid is measuring plays by domain, so I'm wondering if adding something similar to our metrics would be handy? A bit leary of adding measurements that could be personally identifying even just for the Test Pilot run, but it could be useful feedback.

/cc @johngruen who may have already thought about this

**Comment by ckprice** [comment]
Min Vid had a defined list of domains it was recording which makes this a bit different. I've added as a question in the PN draft for legal.

**Comment by bwinton** [comment]
As a more privacy-friendly option, maybe we could categorize the top 100 sites, and send back categories instead, if there was a question we needed that data to answer.

**Comment by bwinton** [comment]
We don't seem to need this for now, so let's close it.
