### ISSUE TITLE
Panel has empty space at the bottom on pages you cannot snooze

### ISSUE THREAD

**Issue by sevaan** [bwinton/SnoozeTabs#131]
If you are on a page you cannot snooze (e.g. about:newtab), when you click on the panel the Manage Snoozed Tabs panel should open. Currently there is a big empty blank space at the bottom of the panel. Ideally the panel height should collapse to show the relevant tabs if there are any. If this isn't possible, the dark space should be white. If there are no tabs to manage, show the empty Manage Tabs state (Issue #118)

<img width="346" alt="screen shot 2017-02-01 at 11 41 42 am" src="https://cloud.githubusercontent.com/assets/473531/22516312/6b72a4c0-e873-11e6-8114-6aef5d77c580.png">

Also, when clicking on a tab, it opens in a new active tab, but the panel remains open. The panel should close if the user has selected a tab to open.

**Comment by lmorchard** [comment]
Also seems like a PR #120 issue, and not on master

**Comment by sevaan** [comment]
Closing this issue as I've posted it in Issue #120.
