### ISSUE TITLE
/bin/build-addon.sh runs `npm run build` twice?

### ISSUE THREAD

**Issue by pdehaan** [bwinton/SnoozeTabs#133]
In the [/bin/build-addon.sh](https://github.com/bwinton/SnoozeTabs/blob/master/bin/build-addon.sh), it looks like we may be calling `npm run build` twice ([once directly](https://github.com/bwinton/SnoozeTabs/blob/a4d13b3b0bb3aca832a1d1134fe802d425dda4bf/bin/build-addon.sh#L4), the [other indirectly](https://github.com/bwinton/SnoozeTabs/blob/a4d13b3b0bb3aca832a1d1134fe802d425dda4bf/bin/build-addon.sh#L7) via [`npm run package`](https://github.com/bwinton/SnoozeTabs/blob/a4d13b3b0bb3aca832a1d1134fe802d425dda4bf/package.json#L65)) if there is an `$TESTPILOT_AMO_USER` or `$TESTPILOT_AMO_SECRET` env var set.

You can see this in the [Circle CI build log's `$ ./bin/build-addon.sh` step](https://circleci.com/gh/bwinton/SnoozeTabs/104?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link), because **svgo** seems to be getting called twice.

```sh
#!/bin/bash
...
npm run build

if [[ -z $TESTPILOT_AMO_USER || -z $TESTPILOT_AMO_SECRET ]]; then
  npm run package
else
  ...
fi
```

Not sure if we can just move the `npm run build` step into the bash `else` block since it will get called in the `if` block's `npm run package` script.

**Comment by lmorchard** [comment]
Ah, yeah, `build` was not called by `package` when this script was written. Then we moved it back in.
