### ISSUE TITLE
Items become unreadable or even unreachable because of doorhanger resize, when "SnoozeTabs" button is moved in the Firefox menu

### ISSUE THREAD

**Issue by SoftVision-EmilPasca** [bwinton/SnoozeTabs#137]
[Notes]:
This issue causes the next problems
- The Snooze options are not entirely visible.
- The items from the "Managed Snoozed Tabs" panel can't be removed.
- The calendar for "Pick a Date/Time" snoozing option is not entirely visible, making the Saturday days impossible to be selected.

[Affected versions]:
- Nightly 54.0a1
- Snooze Tabs 1.0.9 (built on 02/02/2017)

[Affected Platforms]:
- All Windows

[Prerequisites]:
- Have a Firefox profile with the latest Snooze Tabs add-on version (1.0.9 -dev, built on 02/02/2017) loaded as a temporary add-on.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisite and navigate to any website.
2. Click the "SnoozeTabs" button and observe the doorhanger size and items.
3. Right-click on the Snooze Tabs icon from the toolbar and select the "Move to Menu" option from the doorhanger.
4. Click the Firefox menu from the main toolbar.
5. Click on the "SnoozedTabs" icon and observe the doorhanger size and items.

[Expected result]:
- The "SnoozedTabs" doorhanger has the same width as when displayed in toolbar and all items are visible and reachable.

[Actual result]:
- The "SnoozedTabs" doorhanger has a reduced width making some of the items unreadable or even unreachable.

[Additional Notes]:
- The issue isn't reproducible on Mac OS.
- Attached a screen recording of the issue:
![snoozetabs_panel_isssue](https://cloud.githubusercontent.com/assets/20083658/22558100/38149b94-e975-11e6-83d4-ef5f323078ad.gif)

**Comment by lmorchard** [comment]
> [Expected result]:
> - The "SnoozedTabs" doorhanger has the same width as when displayed in toolbar and all items are visible and reachable.

It can't have the same width - we can have a custom width when the popup originates from the toolbar, but [when in the menu panel, the width is fixed by Firefox](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/User_interface_components#Popup_resizing). There are alternate styles for the menu panel case. 

> [Actual result]:
> - The "SnoozedTabs" doorhanger has a reduced width making some of the items unreadable or even unreachable.

What's weird is it looks like the window itself is cut off a bit in the screen recording. The scrollbar is kind of off screen. Maybe that's just an artifact of the recording? If so, we may need to narrow the styles for this menu panel case even further.

**Comment by SoftVision-EmilPasca** [comment]
I've checked the Browser Console and it displays the following messages:
`SnoozeTabs (FE): init  snooze-content.js:33477:6
SnoozeTabs (FE): resize 10 false true  snooze-content.js:33477:6
SnoozeTabs (FE): fetching items  snooze-content.js:33477:6
SnoozeTabs (FE): resize 248 true false  snooze-content.js:33477:6
SnoozeTabs (FE): fetched items Object {  }  snooze-content.js:33477:6
SnoozeTabs (BE): backend received panelOpened undefined  background.js:4768:6
SnoozeTabs (Metrics): postMessage Object { event: "panel-opened" }  background.js:4550:6
SnoozeTabs (FE): resize 248 false false`

**Comment by lmorchard** [comment]
Oh! I missed the part about Windows vs Mac. Turns out the fixed panel width is in `em` units, which seems to vary in terms of `px` between platforms. Will see if I can get a breakpoint for the styles that works well on both platforms

**Comment by bwinton** [comment]
Could you set the breakpoint in em?  😉

**Comment by sevaan** [comment]
If we move the time details underneath the preset titles and adjust the margins a little, the main options can fit nicely:

<img width="1156" alt="screen shot 2017-02-03 at 3 09 27 pm" src="https://cloud.githubusercontent.com/assets/473531/22606704/cdaf8a30-ea22-11e6-84f3-57f9202d7be1.png">


Will work on the other views.

**Comment by lmorchard** [comment]
> Could you set the breakpoint in em? 

@bwinton - It would have to be the em of whatever font is used on the respective platforms within Firefox for UI

> If we move the time details underneath the preset titles and adjust the margins a little, the main options can fit nicely:

@sevaan - [There should be styles for that in there already](https://github.com/lmorchard/SnoozeTabs/blob/62a37646522637f0b36ec30d71120814d62f706b/src/popup/snooze.scss#L560) - are you not seeing them? The probably need tweaking, but I did take a first stab at it

**Comment by lmorchard** [comment]
FWIW, this is what the styles look like in my browser:

<img width="268" alt="screenshot 2017-02-03 16 05 41" src="https://cloud.githubusercontent.com/assets/21687/22608417/c20854de-ea2a-11e6-8d19-d551244a378c.png">

<img width="277" alt="screenshot 2017-02-03 16 07 13" src="https://cloud.githubusercontent.com/assets/21687/22608434/d659b630-ea2a-11e6-9414-fc5ed2f91b25.png">

<img width="277" alt="screenshot 2017-02-03 16 07 13" src="https://cloud.githubusercontent.com/assets/21687/22608456/f1e4b9d6-ea2a-11e6-88f0-cd886203bb77.png">

**Comment by sevaan** [comment]
Those look good, @lmorchard!

**Comment by SoftVision-EmilPasca** [comment]
When testing with the custom build made today (02/08/2017), Snooze Tabs 1.0.11 and loaded as a temporary add-on, the issue is no longer reproducible.
However, the issue is still reproducible, when testing with the latest Snooze Tabs 1.0.11, from the following link:
https://testpilot.firefox.com/files/snoozetabs@mozilla/latest

Which build should we consider as the latest one, the custom one which we made from the master repository, or the one from the link?

**Comment by lmorchard** [comment]
A custom build from a fresh `master` checkout will always be the latest. The one from the Test Pilot link is built from the `production` branch, which requires a manual update and so will always lag behind master.

If you *don't* want to make a custom build, you can [look on CircleCI for test runs](https://circleci.com/gh/bwinton/SnoozeTabs) and every test run should have a .zip file build under the Artifacts tab as a result of the test run.
