### ISSUE TITLE
Snooze options under the gray margin of the "Managed Snoozed Tabs" panel can be hovered and clicked

### ISSUE THREAD

**Issue by SoftVision-EmilPasca** [bwinton/SnoozeTabs#138]
[Notes]:
- When this occurs the current tab is wrongly snoozed.
- The same behavior can be observed when selecting the "Pick a Date/Time" snoozing option.

[Affected versions]:
- Nightly 54.0a1
- Snooze Tabs 1.0.9 (built on 02/02/2017)

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Have a Firefox profile with the latest Snooze Tabs add-on version (1.0.9 -dev, built on 02/02/2017) loaded as a temporary add-on.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisite and navigate to any website.
2. Click on the "SnoozedTabs" button.
3. Click on the "Managed Snoozed Tabs" button.
4. Hover over the gray margin of the panel and click it.

[Expected result]:
- The snooze options under the gray margin of the panel are unclickable.

[Actual result]:
- The snooze options under the gray margin of the panel can be hovered and clicked, snoozing the current tab.

[Notes]:
- The issue is also reproducible when SnoozedTabs is moved to the Firefox Menu. 
- Also, when button is moved in the Firefox menu, the gray margin does not cover the entire panel.
- Attached a screen recording of the issue:
![snoozetabs_margin_issue](https://cloud.githubusercontent.com/assets/20083658/22560595/e53c7bd6-e97d-11e6-9a74-81dab62e275a.gif)

**Comment by lmorchard** [comment]
> Also, when button is moved in the Firefox menu, the gray margin does not cover the entire panel.

Going to file a different issue about this - it's unrelated to this issue and is a lingering problem with menu panel styling.

**Comment by SoftVision-EmilPasca** [comment]
This issue should be reopen since I've managed to reproduce it when selecting the "Pick a Date/Time" snoozing option, as mentioned in the [Notes].
Tested with latest Snooze Tabs version (1.0.9 built on 02/06/2017).
![snoozetabs_dateissue](https://cloud.githubusercontent.com/assets/20083658/22651045/482ba1ea-ec8a-11e6-9e58-8303dd637979.gif)

**Comment by lmorchard** [comment]
Yeah, looks like I forgot the date picker obscures the panel too. Got a PR incoming

**Comment by SoftVision-EmilPasca** [comment]
The issue is no longer reproducible on the latest Snooze Tabs version (1.0.9 built on 02/07/2017).

**Comment by SoftVision-EmilPasca** [comment]
While on special URLs (eg: about:addons), the snoozed items are still hoverable but no longer actionable under the gray margin of the "Edit Time/Date" panel. 
@lmorchard Is this something that we should be concerned about?
![snoozetabs_hover_issue](https://cloud.githubusercontent.com/assets/20083658/23704455/b5124454-040d-11e7-843a-345f825c31d5.gif)

**Comment by lmorchard** [comment]
>  @lmorchard Is this something that we should be concerned about?

No, I don't think so. Main thing is that they shouldn't be clickable
