### ISSUE TITLE
Unable to properly build and test the latest version of SnoozeTabs(02/03/2017)

### ISSUE THREAD

**Issue by SoftVision-EmilPasca** [bwinton/SnoozeTabs#139]
[Notes]:
- There is no clear error displayed while building from GitHub.
- When opening the zip package, you can observe that it is empty.

[Affected versions]:
- Snooze Tabs 1.0.9 (built on 02/03/2017)

[Steps to reproduce]:
1. Open a new terminal window and run the following commands:
2. git clone "https://github.com/bwinton/SnoozeTabs"
3. cd SnoozeTabs
4. npm install
5. npm run build
6. npm run package
7. Observe the package size.

[Expected result]:
- The snoozetabs-1.0.9.zip size has ~476 KB (488,124 bytes).

[Actual result]:
- The snoozetabs-1.0.9.zip size has 22 bytes.

**Comment by lmorchard** [comment]
I can reproduce locally, will investigate!

**Comment by lmorchard** [comment]
Oddly, this does *not* seem to have happened on CircleCI with the latest test run. The build there seems okay:

https://circleci.com/gh/bwinton/SnoozeTabs/109#artifacts/containers/0
https://109-15314951-gh.circle-artifacts.com/0/tmp/circle-artifacts.omD2dlB/snoozetabs-1.0.9.zip

And CircleCI is using a build script that does the same as the steps to reproduce - except `npm run package` also runs `build`, making steps 5 & 6 redundant. But, skipping the build step locally doesn't resolve the issue for me.

**Comment by SoftVision-EmilPasca** [comment]
The issue is no longer reproducible on the latest Snooze Tabs version (1.0.9 built on 02/06/2017).
