### ISSUE TITLE
"Pick a Date/Time" panel wrongly interacts in current implementation with keyboard navigation events

### ISSUE THREAD

**Issue by SoftVision-EmilPasca** [bwinton/SnoozeTabs#145]
[Notes]
- A similar behavior can be observed for the "Managed Snoozed Tabs" panel.
- The user is able to interact with the slided panel elements.
- The issue is also reproducible when SnoozedTabs is moved to the Firefox Menu.

[Affected versions]:
- Nightly 54.0a1
- Snooze Tabs 1.0.9 (built on 02/06/2017)

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Have a Firefox profile with the latest Snooze Tabs add-on version (1.0.9 -dev, built on 02/06/2017) loaded as a temporary add-on.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisite and navigate to any website.
2. Click on the "SnoozedTabs" button.
3. Click on the "Pick a Date/Time" button.
4. Press and hold the "Right" or "Tab" key on the keyboard and observe the panel behavior.

[Expected result]:
- The "Pick a Date/Time" panel remains displayed since keyboard navigation is not yet implemented.

[Actual result]:
- The "Pick a Date/Time" panel is overlapped by "Managed Snoozed Tabs" panel making the content unusable.

[Notes]:
- Attached a screen recording of the issue:
![snoozetabs_keyboardissue](https://cloud.githubusercontent.com/assets/20083658/22654029/236c8c20-ec94-11e6-829b-ed8e75dc3c8f.gif)

**Comment by lmorchard** [comment]
I *think* this has been fixed since b743607dbed24a3631fe82a4b56600730e046b83 because we no longer render these "off-stage" panels until they're needed

**Comment by SoftVision-EmilPasca** [comment]
The issue is no longer reproducible on the latest Snooze Tabs version (1.0.16-dev built on 03/24/2017).
