### ISSUE TITLE
Add hover state for delete snooze button?

### ISSUE THREAD

**Issue by pdehaan** [bwinton/SnoozeTabs#149]
Currently, the unhovered and hovered state for the delete snooze button are the same.
Not sure if we want to lighten/darken the delete button on hover.

![foxnews_-_yahoo_search_results_and_1__npm_start__node__and__eslintrc_ _pulse](https://cloud.githubusercontent.com/assets/557895/22705329/faeffa52-ed1f-11e6-85ea-9990520af21d.png)

**Comment by sevaan** [comment]
Hover Colour: #951400
