### ISSUE TITLE
Causes ACR panel to break - Wrong icon URL

### ISSUE THREAD

**Issue by rugk** [bwinton/SnoozeTabs#15]
This add-on causes incompatibility issues with [ACR](https://addons.mozilla.org/de/firefox/addon/add-on-compatibility-reporter/). More details here: https://github.com/mozilla/addon-compatibility-reporter/issues/61

**Comment by wagnerand** [comment]
It also causes your add-on icon to not be displayed in the add-ons manager, which is the whole purpose of the add-on :)

The fix would be to use an actual chrome:// uri instead of a relative path.

**Comment by rugk** [comment]
Ah this was already tracked in https://github.com/bwinton/SnoozeTabs/issues/13

**Comment by rugk** [comment]
@wagnerand Maybe do a PR?

**Comment by wagnerand** [comment]
Sorry I don't have capacity for this. I think anyone can submit a PR. :)

**Comment by wagnerand** [comment]
Why has this been closed?

**Comment by bwinton** [comment]
Sorry, I was hoping I'ld be able to add a comment when closing the issues…

We've got entirely new designs, and will be re-writing the add-on as a WebExtension, so all of the current issues are no longer valid.

**Comment by wagnerand** [comment]
🎉 👍
