### ISSUE TITLE
Do we need an incompatibility notice with the Containers experiment?

### ISSUE THREAD

**Issue by ckprice** [bwinton/SnoozeTabs#151]
https://github.com/mozilla/testpilot-containers

How do things work with Containers? How should they work?

**Comment by bwinton** [comment]
Do they work with Containers?  Has anyone tested it?
I think they mostly just don't display any container-related info.  There's a bug open to let them support containers, and someone has said they'ld like to work on it…

**Comment by ckprice** [comment]
Taking this, and will add a notice on the Test Pilot side.
