### ISSUE TITLE
SnoozeTabs notification bar is wrongly displayed and cannot be dismissed on particular websites

### ISSUE THREAD

**Issue by SoftVision-EmilPasca** [bwinton/SnoozeTabs#153]
[Affected versions]:
- Nightly 54.0a1
- Snooze Tabs 1.0.11

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Have a Firefox profile with the latest Snooze Tabs signed-addon.xpi from https://testpilot.firefox.com/files/snoozetabs@mozilla/latest
- "Ask for confirmation when snoozing tabs" is checked in "Manage Snooze Tabs" panel.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisite and navigate to https://www.instagram.com/nytimes/.
2. Click on the "SnoozedTabs" button.
3. Click on the "Later Today" button or any other snoozing option.
4. Observe the "SnoozeTabs" notification bar and press the "Cancel" or "x" buttons.

[Expected result]:
- The "SnoozeTabs" notification bar is correctly displayed and when pressing the "Cancel" or "x" buttons, the notification is dismissed.

[Actual result]:
- The "SnoozeTabs" notification bar is wrongly displayed and cannot be dismissed when clicking the "Cancel" or "x" buttons.

[Notes]:
- In some cases, even if the notification is wrongly displayed, it can be dismissed e.g: http://giphy.com/
- Attached a screen recording of the issue: https://goo.gl/jeVvyN

**Comment by lmorchard** [comment]
Yeah, I think this is because we're injecting this bar into third-party web content, and it's hard to completely control styling on any given page. I wonder if there's some more we can do to kind of "CSS reset" for the bar? It's possible other sites will break this bar in further interesting ways

**Comment by lmorchard** [comment]
This issue, specifically, is caused by this CSS on Instagram's site - most notably the `flex-direction:column`:
```
#react-root,article,div,footer,header,main,nav,section {
	-webkit-box-align:stretch;
	-ms-flex-align:stretch;
	align-items:stretch;
	border:0 solid #000;
	box-sizing:border-box;
	display:-webkit-box;
	display:-ms-flexbox;
	display:flex;
	-webkit-box-orient:vertical;
	-webkit-box-direction:normal;
	-ms-flex-direction:column;
	flex-direction:column;
	-ms-flex-negative:0;
	flex-shrink:0;
	margin:0;
	padding:0;
	position:relative
}
```

**Comment by lmorchard** [comment]
Yeah, I started looking for an up-to-date CSS reset, but not finding anything that seems super recent - e.g. one that has all the default flexbox properties and such. Might just be a whack-a-mole game for now

**Comment by SoftVision-EmilPasca** [comment]
The issue is no longer reproducible on the latest Snooze Tabs version (1.0.12-dev built on 02/10/2017).

**Comment by SoftVision-EmilPasca** [comment]
I have managed to reproduce this issue using the latest Snoozetabs (1.0.21 - https://circleci.com/gh/bwinton/SnoozeTabs/651) when testing on Mac 10.12, Windows 10 x64 and Ubuntu 14.04 x64 with the latest Firefox Release (57.0.4) and latest Nightly (59.0a1-20180118012136).

**Comment by SoftVision-EmilPasca** [comment]
I have re-tested this issue, it is no longer reproducible with the latest Snoozetabs (1.0.21 - https://circleci.com/gh/bwinton/SnoozeTabs/652).
