### ISSUE TITLE
Icons from "Tomorrow" and "This Weekend" snoozing options are not displayed in the SnoozeTabs panel

### ISSUE THREAD

**Issue by SoftVision-EmilPasca** [bwinton/SnoozeTabs#154]
[Affected versions]:
- Nightly 54.0a1
- Snooze Tabs 1.0.11

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Have a Firefox profile with the latest Snooze Tabs signed-addon.xpi from https://testpilot.firefox.com/files/snoozetabs@mozilla/latest

[Steps to reproduce]:
1. Open the browser with the profile from prerequisite and navigate to any website.
2. Click on the "SnoozedTabs" button.
3. Observe the snoozing options icons from the SnoozeTabs panel.

[Expected result]:
- All the icons are displayed correctly.

[Actual result]:
- The icons from "Tomorrow" and "This Weekend" options are not displayed.

[Notes]:
- Attached a screen recording of the issue:
![snoozetabs_icons_missing](https://cloud.githubusercontent.com/assets/20083658/22748909/4e956c72-ee34-11e6-850f-22782554e6fa.gif)

**Comment by lmorchard** [comment]
Weird: I *can* reproduce this using the latest .xpi build from production. I *cannot* reproduce this in my local dev build. Need to see if there's something weird happening in the production build process.

**Comment by pdehaan** [comment]
Similarly, the trash can icon in the Manage Snoozed Tabs UI is missin':

![problem_loading_page_and_firefox_test_pilot_-_tab_center](https://cloud.githubusercontent.com/assets/557895/22758440/984515ba-ee03-11e6-96f2-3c4a624bcee4.png)

**Comment by pdehaan** [comment]
Crazy theory: peeking into the XPI, it looks like the 3 icons in question are uppercased. See https://github.com/bwinton/SnoozeTabs/tree/master/src/icons

Looks like they're lowercased in the [`times` const](https://github.com/bwinton/SnoozeTabs/tree/master/src/icons) in /src/icons/*.svg:

```js
export const times = [
  {id: 'debug', icon: 'nightly.svg', title: 'Real Soon Now!'},
  {id: 'later', icon: 'later_today.svg', title: 'Later Today'},
  {id: 'tomorrow', icon: 'tomorrow.svg', title: 'Tomorrow'},
  {id: 'weekend', icon: 'weekends.svg', title: 'This Weekend'},
  {id: 'week', icon: 'next_week.svg', title: 'Next Week'},
  {id: 'month', icon: 'next_month.svg', title: 'Next Month'},
  {id: NEXT_OPEN, icon: 'next_open.svg', title: 'Next Open'},
  {id: PICK_TIME, icon: 'pick_date.svg', title: 'Pick a Date/Time'}
];
```

... and trash icon in [/src/lib/components/ManagePanel.js:125](https://github.com/bwinton/SnoozeTabs/blob/1f84cf7418c8496771dd2ccf3e80c182d98bbda2/src/lib/components/ManagePanel.js#L125):

```html
<div className="delete" onClick={() => this.handleItemDelete(item)}>
  <img src="../icons/trash.svg" width="16" height="16" />
</div>
```


![blank_skitch_document](https://cloud.githubusercontent.com/assets/557895/22758591/2c76db9c-ee04-11e6-97a0-136b557580e8.png)

**Comment by pdehaan** [comment]
Odd, I'm on macOS Sierra and my local files look all lowercased locally:

```sh
$ ls -lash
   1.9K Jan 23 16:11 bell_icon.svg
   814B Jan 23 16:11 color_bell_icon.png
   1.9K Feb  3 15:14 color_bell_icon.svg
   1.9K Jan 23 16:11 disabled_bell_icon.svg
   1.3K Jan 23 16:11 later_today.svg
   1.8K Jan 23 16:11 next_month.svg
    16K Jan 23 16:11 next_open.svg
   1.8K Jan 23 16:11 next_week.svg
    38K Jan  6 15:01 nightly.svg
   1.6K Jan 23 16:11 pick_date.svg
   223B Feb  3 15:14 stop.svg
   1.0K Jan  6 15:01 tomorrow.svg
   710B Jan  6 15:01 trash.svg
   2.9K Jan  6 15:01 weekends.svg
```

**Comment by pdehaan** [comment]
Ref: #156

**Comment by SoftVision-EmilPasca** [comment]
The issue is no longer reproducible on the latest Snooze Tabs version (1.0.12 built on 02/10/2017).
