### ISSUE TITLE
We shouldn't show the "Real Soon Now" item in Production builds.

### ISSUE THREAD

**Issue by bwinton** [bwinton/SnoozeTabs#155]
Ya know, now that we have actual production builds and all…

**Comment by pdehaan** [comment]
Ref: [/src/lib/times.js:9](https://github.com/bwinton/SnoozeTabs/blob/724ae06c6afabca502bbc5215074db68f97b300f/src/lib/times.js#L9)

@bwinton Can we still keep the menu option for NODE_ENV !== production?

**Comment by bwinton** [comment]
Yeah, that was my thought.  We want it for testing, but shouldn't show it in prod.
