### ISSUE TITLE
Slightly misaligned OK/Cancel buttons on washingtonpost.com snoozed tabs

### ISSUE THREAD

**Issue by pdehaan** [bwinton/SnoozeTabs#157]
![add-ons_manager](https://cloud.githubusercontent.com/assets/557895/22761318/11e3598a-ee0f-11e6-8f3c-e83485909a39.png)

I was trying to snooze https://www.washingtonpost.com/news/arts-and-entertainment/wp/2017/02/08/john-oliver-is-preparing-to-take-on-president-trump-but-he-isnt-exactly-excited-about-it/?utm_term=.3bcab7497677 on macOS and noticed that the OK/Cancel buttons are wicked misaligned:

![john_oliver_is_preparing_to_take_on_president_trump__but_he_isn t_exactly_excited_about_it_-_the_washington_post](https://cloud.githubusercontent.com/assets/557895/22761358/4009c308-ee0f-11e6-8a89-ba0175cb6165.png)

**Comment by lmorchard** [comment]
This is probably a milder / related case of #153 - which is that we may not be able to control styling on all sites when injecting this notification bar into third-party web content. Maybe correcting it on individual sites is good enough? Maybe we want to try something different?
