### ISSUE TITLE
Snoozed tab is deleted, if it is rescheduled from the "Edit Date/Time" panel

### ISSUE THREAD

**Issue by SoftVision-EmilPasca** [bwinton/SnoozeTabs#158]
[Affected versions]:
- Nightly 54.0a1
- Snooze Tabs 1.0.11

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Have a Firefox profile with the latest Snooze Tabs signed-addon.xpi from https://testpilot.firefox.com/files/snoozetabs@mozilla/latest
- Have at least one previously snoozed tab in the "Manage Snooze Tabs" panel.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisite and navigate to any website.
2. Click on the "SnoozedTabs" button.
3. Click on the "Manage Snooze Tabs" button.
4. Hover over an item from the "Manage Snooze Tabs" panel and click on the date.
5. After the "Edit Date/Time" panel is displayed, reschedule and click the "Snooze!" button.

[Expected result]:
- The snoozed tab is rescheduled to the selected time.

[Actual result]:
- The snoozed tab is deleted.

[Notes]:
- The issue is also reproducible even if the user decides to click the "Snooze!" button without rescheduling.
- The deleted tab from the "Manage Snooze Tabs" panel is also deleted from the Library.
- Attached the Browser Console messages:
`
SnoozeTabs (FE): resize 320 false false  snooze-content.js:33623:6
SnoozeTabs (FE): resize 320 false false snooze-content.js:33623:6
SnoozeTabs (BE): backend received update Object { old: Object, updated: Object }  background.js:4993:6
SnoozeTabs (Metrics): sendEvent b7c51fbc-ce9e-4b14-a2f1-02a8d8af98d8 Object { event: "updated", snooze_time_type: undefined, snooze_time: NaN }  background.js:4722:6
SnoozeTabs (Metrics): sendEvent b7c51fbc-ce9e-4b14-a2f1-02a8d8af98d8 Object { event: "cancelled", snooze_time_type: "weekend", snooze_time: 146859 }  background.js:4722:6
SnoozeTabs (FE): fetching items  snooze-content.js:33623:6
SnoozeTabs (FE): fetched items undefined Object {  }  snooze-content.js:33623:6
SnoozeTabs (FE): resize 320 false false  snooze-content.js:33623:6
SnoozeTabs (BE): schedule inject rejected Error: Incorrect argument types for tabs.sendMessage.
Stack trace:
schedule/</<@moz-extension://c948b10f-145f-4ecc-9a0b-72f51d01c89c/background.js:5115:16
promise callback*schedule/<@moz-extension://c948b10f-145f-4ecc-9a0b-72f51d01c89c/background.js:5114:7
promise callback*schedule@moz-extension://c948b10f-145f-4ecc-9a0b-72f51d01c89c/background.js:5109:12
promise callback*update@moz-extension://c948b10f-145f-4ecc-9a0b-72f51d01c89c/background.js:5152:12
handleMessage@moz-extension://c948b10f-145f-4ecc-9a0b-72f51d01c89c/background.js:5099:5
  background.js:4993:6
SnoozeTabs (FE): resize 320 false false  snooze-content.js:33623:6
SnoozeTabs (BE): Sync Folder! Object { id: "8pGy3HnXr9M7", title: "Snoozed Tabs", index: 0, dateAdded: 1486649543820, parentId: "unfiled_____", dateGroupModified: 1486649543820 } Array [  ]  backg
`
- Attached a screen recording of the issue: 
![snoozetabs_reschedule](https://cloud.githubusercontent.com/assets/20083658/22786669/339d38ce-eee2-11e6-865d-0b498bbd42c0.gif)

**Comment by lmorchard** [comment]
Can reproduce this, adding to launch milestone because IMO it's critical. Will be poking at it today.

**Comment by SoftVision-EmilPasca** [comment]
The issue is no longer reproducible on the latest version (Snooze Tabs 1.0.12 - build on 02/14/2017).
However,  two "Snooze Tabs" folders are displayed in the Library when rescheduling a tab from the "Edit Date/Time" panel .
