### ISSUE TITLE
Snooze Tab Icon Credits

### ISSUE THREAD

**Issue by sevaan** [bwinton/SnoozeTabs#164]
Our design contributor used some icons from the Noun Project that we will need to credit somewhere.

- Snooze Tabs logo: https://thenounproject.com/term/bell/242717/ (Modified)
- Later Today: https://thenounproject.com/term/stopwatch/190330/
- Tomorrow: https://thenounproject.com/term/future/101713/
- Weekend:https://thenounproject.com/nas.ztu/collection/travel/?oq=weekend&cidx=0&i=58827
- Next Month: https://thenounproject.com/term/calendar/124931/ (Modified)
- Pick a Date: https://thenounproject.com/term/calendar/124931/

As for where...any ideas @johngruen?

**Comment by pdehaan** [comment]
Ref: https://thenounproject.zendesk.com/hc/en-us/articles/200509928-How-do-I-give-creators-credit-in-my-work-

**Comment by lmorchard** [comment]
Maybe listing them in the README.md in the project root would be okay?

**Comment by bwinton** [comment]
Maybe there and on the test pilot landing page?
