### ISSUE TITLE
Unable to see German translations locally in add-on

### ISSUE THREAD

**Issue by pdehaan** [bwinton/SnoozeTabs#169]
We merged the l10n stuff in #168.

```sh
➜  SnoozeTabs git:(master) $ git rev-parse --short HEAD # 3595938
```

So after I grab latest commit from master, and create a new German/de localization (./locales/de/snoozetabs.properties) which has the following:

```properties
# LOCALIZATION NOTE: This add-on will let you select tabs to close for a while, after which they will re-appear in your browser with a notification.
extDesc=AN ADD-ON TO LET YOU SNOOZE YOUR TABS FOR A WHILE.
popupTitle=SNOOZE TAB UNTIL…
contextMenuTitle=SNOOZE TAB UNTIL…
bookmarkFolderTitle=SNOOZED TABS
notificationTitle=TAB WOKE UP…

confirmIconAltText=TAB ICON
# LOCALIZATION NOTE: "{time}" is the time the tab will snooze until, as per https://github.com/bwinton/SnoozeTabs/issues/60
confirmTimeTitle=THIS TAB WILL SNOOZE UNTIL {time}.
confirmOkButton=OK
confirmCancelButton=CANCEL
confirmDontShowLabel=DONʼT SHOW THIS AGAIN
confirmCloseAltText=CLOSE BUTTON

# LOCALIZATION NOTE: This will be in 5 seconds, for testing.
timeRealSoonNow=REAL SOON NOW!
timeLaterToday=LATER TODAY
timeTomorrow=TOMORROW
timeThisWeekend=THIS WEEKEND
timeNextWeek=NEXT WEEK
timeNextMonth=NEXT MONTH
# LOCALIZATION NOTE: This will be the next time Firefox opens.
timeNextOpen=NEXT OPEN
timeNextOpenLong=THE NEXT TIME FIREFOX OPENS
timePickADate=PICK A DATE/TIME
# LOCALIZATION NOTE: "{time}" is the time the tab will snooze until.
timeUpcomingToday=LATER TODAY AT {time}
# LOCALIZATION NOTE: "{time}" is the time the tab will snooze until.
timeUpcomingTomorrow=TOMORROW AT {time}
# LOCALIZATION NOTE: "{weekday}" is the day of the week, "{date}" is the day of the month.  Example: "Sun, Mar 5 at 7:05am".
timeUpcomingLater={weekday}, {month} {date} AT {time}

datePickerBack=« BACK
datePickerDisabled=TIME SELECTION IS IN THE PAST
datePickerSnooze=SNOOZE!

mainManageButton=MANAGE SNOOZED TABS
mainCalendarHeader=PICK A DATE/TIME

manageHeader=MANAGE SNOOZED TABS
manageNoSnoozes=NO UPCOMING SNOOZES
manageConfirmLabel=ASK FOR CONFIRMATION WHEN SNOOZING TABS
manageBack=« BACK
manageCalendarHeader=EDIT DATE/TIME
manageDateLater=LATER
# LOCALIZATION NOTE: The next two will always appear on top of each other.
manageDateNext=NEXT TIME
manageTimeNext=FIREFOX OPENS
```

Running `npm start` locally correctly creates ./dist/_locales/de/messages.json which has the following sauce:

```js
{
  "extDesc": {
    "message": "AN ADD-ON TO LET YOU SNOOZE YOUR TABS FOR A WHILE."
  },
  "popupTitle": {
    "message": "SNOOZE TAB UNTIL…"
  },
  // ...
  "manageTimeNext": {
    "message": "FIREFOX OPENS"
  }
}
```

Even if I set my locale in about:preferences#content to German or set `general.useragent.locale` in about:config (see [Anatomy of an internationalized WebExtension](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Internationalization#Testing_out_your_WebExtension)), it's only partially picking up my translations:

![firefox_test_pilot_and_browser_console_and_internationalization_-_mozilla___mdn](https://cloud.githubusercontent.com/assets/557895/22906732/bc8f9986-f1fa-11e6-9fa7-877e6922e704.png)
**Figure 1:** Some date formatting seems to be in German.

![file____users_pdehaan_dev_github_mozilla_snoozetabs_dist_popup_snooze-content_js_and_browser_console_and_internationalization_-_mozilla___mdn](https://cloud.githubusercontent.com/assets/557895/22906773/ed3e66ca-f1fa-11e6-911e-11fe84c53e35.png)
**Figure 2:** More partially German-ed test.

**Comment by flodolo** [comment]
I filed #172 before realizing this one has some info about dates. Localization is correctly picked up for me though.

**Comment by lmorchard** [comment]
FWIW, parts of date l10n are separate from the strings, because they're handled by the Moment.JS library. Month names, etc. Actual date/time formats are manually-tweaked strings for the UX spec, though. We should handle that in #172

**Comment by bwinton** [comment]
@flod: Have we fixed this with our various l10n changes?

**Comment by flodolo** [comment]
I'm pretty positive we have.

**Comment by bwinton** [comment]
Okay, I'm going to close this and #172 then, and we can open new issues if there's stuff we're missing.
