### ISSUE TITLE
Integrate Pontoon

### ISSUE THREAD

**Issue by pdehaan** [bwinton/SnoozeTabs#170]
From the fabulous Mr. @bwinton in https://github.com/bwinton/SnoozeTabs/issues/55#issuecomment-279526119:

> _"Okay, so, @clouserw (or whomever), could you ask the nice Pontoon people to point Pontoon at the [l10n branch](https://github.com/bwinton/SnoozeTabs/tree/l10n) of this repo, and we can see what happens? 😉 Thanks!"_

**Comment by wresuolc** [comment]
@flodolo or @mathjazz can help us, I think

**Comment by flodolo** [comment]
This one is one me (feel free to assign the issue). I should be able to look into it later today (morning your time).

**Comment by flodolo** [comment]
Pontoon integration seems to work fine. I'm doing some tests on the localized version to see if there are things we need to fix before exposing the string.

**Comment by flodolo** [comment]
Opened #173 to improve a few more things after testing locally.

Would this work as description on Pontoon?
```
SnoozeTabs is a Test Pilot experiment that lets you “snooze” tabs, closing them for a period like you would snooze an alarm.
```

Info needed for message to localizers:
* Is there a dev version of the add-on like it happens for Activity Stream? 
* Is there a schedule for releases?

**Comment by bwinton** [comment]
That seems like a good description to me.

There should be localized versions of the add-on under [this page](https://circleci.com/gh/bwinton/SnoozeTabs/tree/l10n).  (Click on the number of the build on top, then “Artifacts”, then either of the zip files.)

There is currently no release schedule, that I know of.

**Comment by flodolo** [comment]
Project enabled
https://pontoon.mozilla.org/projects/test-pilot-snoozetabs/

Alternative tracking. Compared to Pontoon, this only show content actually in the repository
https://l10n.mozilla-community.org/webstatus/?product=testpilot-snoozetabs

Communication to localizers
https://groups.google.com/d/msg/mozilla.dev.l10n/hQfI8Ofv--U/V42wuSL_CQAJ
