### ISSUE TITLE
[l10n] Dates and time are not correctly localized

### ISSUE THREAD

**Issue by flodolo** [bwinton/SnoozeTabs#172]
* Time is set to 12h, it should be 24h for Italian
* Abbreviated day name is uppercase, Abbreviated month name lowercase. Not the end of the world, but it looks kind of strange
* Order is wrong, day number should be before the month name

![schermata 2017-02-14 alle 12 15 51](https://cloud.githubusercontent.com/assets/3644868/22927109/e36aad6a-f2af-11e6-8f30-dee19700ada1.png)

**Comment by flodolo** [comment]
Same problem with the notification bar
![schermata 2017-02-14 alle 12 34 43](https://cloud.githubusercontent.com/assets/3644868/22927513/ffa18722-f2b1-11e6-81f4-417db0e561a1.png)

**Comment by bwinton** [comment]
(I'll look into this a little, I think there are some things we can do.)

**Comment by lmorchard** [comment]
I think all of these are built from manually-tweaked Moment format strings. Maybe we can use localized strings for those too?

**Comment by bwinton** [comment]
Yeah, something like that.

**Comment by petercpg** [comment]
![image](https://cloud.githubusercontent.com/assets/205738/22979388/26dbf7b2-f3d1-11e6-969f-649031681836.png)

For Chinese, the year/month order should be localizable too. For this case it should be "2017 二月"

**Comment by bwinton** [comment]
So, how terrible would it be to expose the date/time format strings to localizers?  Like, if one of the things was `ddd MMM D \ [@] ha` (for the month time in the panel), would that be totally inexplicable?  Would a link to [these docs](http://momentjs.com/docs/#/displaying/) help?

**Comment by flodolo** [comment]
I think the risk of messing up the add-on is quite high, unless you're able to fall back to something reasonable if you try to pass garbage instead of proper formatting.

**Comment by bwinton** [comment]
I don't think we would be.  Hrm.  This is tricky.  The script I wrote (currently) only makes parameters out of the things I list in the en-US file, so I'll need to change that somehow...

**Comment by bwinton** [comment]
Okay, so I think I've got something, but I've got a couple of questions...
What would the `@ 3pm` turn into in Italian?  `@ 15h`?  `@ 15`?
Actually, when you get a chance, could you check out [this change](https://github.com/bwinton/SnoozeTabs/commit/264ab074915feb2d9038266f8d81aab6b2a7000a) and let me know if it would work okay?

**Comment by flodolo** [comment]
> What would the @ 3pm turn into in Italian? @ 15h? @ 15?
The most natural would probably be @15:00 (then you have the problem of which separator to use…), or just @15, definitely not @15h (15h would be an interval)

Will check the change in a bit.

**Comment by flodolo** [comment]
> Actually, when you get a chance, could you check out this change and let me know if it would work okay?

I tried but the only thing that seems to change it the very soon one. Also not clear what I am supposed to do: remove `{ampm}`? That wouldn't work, since 3pm would become 3, which is 3am.

Isn't this add-on using moment.js? That should have [built-in support](http://momentjs.com/docs/#/i18n/) for localized dates. Why aren't we using that?

**Comment by bwinton** [comment]
Well, let's see what @sevaan thinks about simplifying the date formats…  I know he went to a lot of time specifying what should be shown when, but when faced with the difficulties of translation, he might not mind using some less-nice-but-easier-to-work-with stuff.

**Comment by bwinton** [comment]
Okay, I added a little more to the pull-request, to explain what I was going for a little better.  In particular, Italian now uses 24h time, and has the day number before the month name.  Do you think this will work for most locales?  Is there anything else from [moment](http://momentjs.com/docs/#/displaying/format/) that I should add to let localizers localize it correctly?

**Comment by flodolo** [comment]
> Okay, I added a little more to the pull-request

Where?

> In particular, Italian now uses 24h time, and has the day number before the month name.

Unfortunately it's hard to tell, see also the note above about month/year in Chinese (a problem we had in Firefox OS too).

I'm wondering if we should hard-code a set of these strings, and associate locales to them, with a fallback to en-US as default. That way, at least, we won't be exposing strange codes for localization.

**Comment by bwinton** [comment]
Sorry, yes, the new code [is here](https://github.com/bwinton/SnoozeTabs/commit/f79db9fff9b9aa01156ac3d017436430cf69e69b#diff-ce81ec9605485778025bc163f3bcf931).

I'm not sure how a hard-coded set of strings would look.  Could you give me an example (maybe as a PR)?

**Comment by flodolo** [comment]
Mind the code, I was thinking about something like this
https://github.com/flodolo/SnoozeTabs/commit/244f14abbe67fcfd890314f2304f8aed919e89fe

The problem is how to make it scale (several locales will share the same sentence), and prepare a decent set of locales to start with.

**Comment by bwinton** [comment]
So, I think we can ask @johngruen for a decent starting list of locales, and I've got an idea to make it scale…  Lemme code up, something different and see what you think…

**Comment by bwinton** [comment]
Okay, [here's](https://github.com/bwinton/SnoozeTabs/commit/29471a258d754f5b0c13a9d5f491bc7bf3995773) what I got.  It handles sub-locales, and seems to be decent.  (Uh, there's a bunch of extra testing code in there, but hopefully you get the idea.)

**Comment by flodolo** [comment]
> Okay, here's what I got. It handles sub-locales, and seems to be decent.

It definitely makes sense to me.

The only alternative I can think of is to use CLDR data
e.g. https://github.com/unicode-cldr/cldr-dates-modern/blob/master/main/en/ca-gregorian.json#L332

but as far as I can tell it's not exposed in Firefox yet (@zbraniecki would know for sure, and maybe has some feedback on this discussion)

**Comment by bwinton** [comment]
Even if the CLDR stuff was in Firefox, it probably wouldn't be in WebExtensions…  😢  Okay, I'll fix that up and make a PR.

**Comment by zbraniecki** [comment]
Why don't you guys use `Intl.DateTimeFormat` to format date and time? It's the recommended Intl-aware solution for correct date time formatting which does two things:
* selects the right pattern based on the options you request
* localizes the pattern

**Comment by bwinton** [comment]
We were already using Moment, so it seemed simpler to stick with it.  If you want to make a pull request that switches to `Intl.DateTimeFormat` (while keeping the en_US and it versions the same as they are now), I'd be more than happy to review it!

**Comment by zbraniecki** [comment]
Oh, sure, if you're fine with the overhead, Moment.js is good. It's just that all browsers carry the data for you already these days, so Intl API is just cheaper.

**Comment by flodolo** [comment]
This is only partially fixed. 

The panel when snoozing a tab looks OK now

![schermata 2017-02-23 alle 07 40 38](https://cloud.githubusercontent.com/assets/3644868/23247624/76bff330-f99b-11e6-8999-47bacd37c80f.png)

But the Manage snoozed tabs panel does not (I think it should be easy to fix)

![schermata 2017-02-23 alle 07 40 56](https://cloud.githubusercontent.com/assets/3644868/23247635/7f216fb8-f99b-11e6-9218-abeb6d81627a.png)

The notification bar is not fixed, and it seems the hardest one given how convoluted the code is.

**Comment by flodolo** [comment]
Side note: I'm not sure CLDR would help in this case, besides getting localized fragments (month name, day name, etc.), since this is using custom formats not available in CLDR.

**Comment by zbraniecki** [comment]
> Side note: I'm not sure CLDR would help in this case, besides getting localized fragments (month name, day name, etc.), since this is using custom formats not available in CLDR.

how is that not available in CLDR?
For date:
```javascript
(new Date()).toLocaleString('en-US', {weekday: 'short', month: 'short', day: 'numeric'});
```

for time:
```javascript
(new Date()).toLocaleString('en-US', {hour: 'numeric'});
```

seems to be what en-US uses.

**Comment by zbraniecki** [comment]
@flodolo asked me for a sample, so I mapped the patterns you guys produce to Intl API: https://pastebin.mozilla.org/8980059

Maybe it'll come handy ;)

**Comment by bwinton** [comment]
I believe this is fixed by a patch from @flod…
