### ISSUE TITLE
"Manage Snoozed Tabs" looks too similar to rest of items in panel

### ISSUE THREAD

**Issue by pdehaan** [bwinton/SnoozeTabs#180]
From @sharonbautista's User Research results:

> One participant struggled to see "Manage Snoozed Tabs" (blended in with snooze times listed above)

<img width="360" alt="snooze_tab_until _and_firefox_test_pilot_-_min_vid_and_new_issue_ _bwinton_snoozetabs" src="https://cloud.githubusercontent.com/assets/557895/22943970/27b4f7ca-f2a4-11e6-8ba6-c53d6bf5411c.png">

It may be helpful if the "Manage Snoozed Tabs" button's background color was a bit different than the rest of the list items.

Currently it looks like the snooze list items have a background color of #FFFFFF whereas the button has a background color of #FBFBFB.

**Comment by sevaan** [comment]
Yes, it looks like the colour is off, compared to other panels.

The colour of the Manage Snoozed Tabs button, as well as the Back buttons on the Calendar and Manage Snoozes panels should be...

BG Colour: #E9E9E9
Hover Colour: #DEDEDE

**Comment by sevaan** [comment]
Click: #D2D2D2
