### ISSUE TITLE
Add an updateURL

### ISSUE THREAD

**Issue by wresuolc** [bwinton/SnoozeTabs#187]
Please add an updateURL.  I think you should just need to add this right after the `id` line at https://github.com/bwinton/SnoozeTabs/blob/master/src/manifest.json#L4 :

"update_url": "https://testpilot.firefox.com/files/snoozetabs@mozilla/updates.json"

**Comment by bwinton** [comment]
I don't see that in the [list of manifest keys](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/manifest.json)…
