### ISSUE TITLE
Confirm font sizes for the "Back" and "Snooze!" buttons on the datepicker panel

### ISSUE THREAD

**Issue by pdehaan** [bwinton/SnoozeTabs#195]
![add-ons_manager](https://cloud.githubusercontent.com/assets/557895/23186894/971b9c24-f83d-11e6-9650-9594880dd29b.png)

Trying to confirm with my eyes, but it almost looks like the "Back" and "Snooze!" buttons have a different sized font.

![menubar_and_firefox_test_pilot_-_snooze_tabs_and_1__pdehaan_pdehaan____dev_github_mozilla_pulse__zsh__and_you ve_just_been_upgraded_to_firefox_nightly_54_](https://cloud.githubusercontent.com/assets/557895/23186878/84a50152-f83d-11e6-8154-c199b0f3532a.png)

**Comment by sevaan** [comment]
Looks that way to me too. The "back" is correct.
