### ISSUE TITLE
Snooze Tabs does not work on the Test Pilot site (aka strong CSP breaks Snooze Tabs)

### ISSUE THREAD

**Issue by johngruen** [bwinton/SnoozeTabs#197]
Try snoozing on Test Pilot, for example...

i get the following errors:

```
Content Security Policy: The page’s settings blocked the loading of a resource at data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAABGdBTUEAALGPC/xhBQAAAAlwSFlzAAAk5gAAJOYBJupJ4gAAABl0RVh0U29mdHdhcmUAcGFpbnQubmV0IDQuMC4xMzQDW3oAAAKrSURBVFhHxZbLaxRBEMaj4DF49yJCDgEPgqAgGMwhENCTB2+KYvAVlBBYkkhgQSUeFBEkIAkSEEECHjx4yB8QEMRzLt52s5PHPhKECCJoW1/vVG91d+3M+FoLfrvdX1dX9fT0Y/qMMf8VVSxCa2nabD++ZEE5bC+KKuZRvTZoKleO+IwNUJPun4UqZpFMDduE+M/SiqKKWfATF9XzUMUsejqAxvM7ZrN8joodjd9/a2nG6bvLD62GNtbA1oPzprkw6Wkhqghqk6ds0PCpsOJZr948auF66+Ws51u5OmD1jbsjni5RRU6+Pn6Mqh29+aJkVzsnjKA2OTMAMdDWbRCRUH923XZYv32cqh09KQ35yTKoTZz0+lZvtGcpnCHgVQAHkRpGz3pRwidmXWrAq2D64ITFw9rOq7IX+FfYXZ5zcTbLZ6228/q+04ArgNrECeskNfXUK0i4K6CFh5UrAO6oaRIs0qR02oMHH0J2iNgvY6HMuALAYgFcb6QLUlJ/chntP1I8s7sk8G/SWUJ2mLDxw53lChobs6NRwHSFf8dPaFtzFyJ/vHsyXJcHiChHJEgwtWFACRKyYXFpPohBtkBg7qMckSDJGkC6zdxr0HxAOoB7xEEiyhEJEnnMStLX4EzzYRCDbJSwCzEkEiRqwPYidU+eTJ1xO0HzB2T9hJpDFRktWHqQyB3gyjhqtT5k+wg1hyoCbQsC3AlkSMqJXbnbkY1YZGoeVQRaoD8hjM+o4u9cPnmElxMTCXwd/wsa87cohZ/PqwD5JfS3qT8doxR+Pq+SR1N8ju2tvnF8Xll0etgnD1XMghN9q6xRtW1fP33s3QD4Gy+ZHjZfPrwze+/f2pMR2vaji+Si9+uGKubBX7uS8JotiioWATchvniQuDE/TpLul4cq9g7T9xPhuVAv+3JqYwAAAABJRU5ErkJggg== (“img-src https://testpilot.stage.mozaws.net https://ssl.google-analytics.com https://www.google-analytics.com”).  (unknown)
Content Security Policy: The page’s settings blocked the loading of a resource at self (“style-src https://testpilot.stage.mozaws.net https://code.cdn.mozilla.net”).
```

**Comment by wresuolc** [comment]
This would be a Test Pilot specific problem -- try snoozing a different https site?

**Comment by lmorchard** [comment]
I don't think this is HTTPS - I think this is Content Security Policy. We do some jiggerypokery with injecting scripts into page content for the confirmation bar before closing a tab to snooze. Also, for flashing the favicon to indicate a freshly woken tab.

Test Pilot in particular has a very strict CSP, so it's no surprise (in retrospect) that this would get blocked. Maybe the fix here is to just recover more gracefully from failing to inject the confirmation bar?

**Comment by johngruen** [comment]
@lmorchard yeah, that seems like a good idea. maybe just don't show it at all? @sevaan

**Comment by bwinton** [comment]
I'm a little surprised that an add-on's content script can't inject content.  Maybe check that with some WebExtensions people before we go to great lengths to fix it?

**Comment by lmorchard** [comment]
Well, the 2 errors pasted above are specifically with the inline styles and data: URL image - both of which are things CSP can block. So we might get the *markup* into the page, but then be unable to use any CSS or images.

**Comment by wresuolc** [comment]
I filed that bug 7 years ago! https://bugzilla.mozilla.org/show_bug.cgi?id=615708

**Comment by lmorchard** [comment]
Revised title to be more obvious about effects

**Comment by wresuolc** [comment]
I think our only option here is to fail gracefully.  The functionality should still work it just won't have pretty notifications and such.  Also, let's fire off a GA ping to see how many of these we hit?

**Comment by lmorchard** [comment]
Well, the functionality is asking the user to confirm or cancel the closing of the tab. What does "graceful" mean here - do we just skip the confirmation and close the tab?

**Comment by wresuolc** [comment]
mmm, for flashing the favicon I meant just not do it.  For the confirmation that's tougher.  Let's ask @johngruen if he has a comment

**Comment by lmorchard** [comment]
So, I'm not sure #247 is the right solution UX-wise. But, it does look like there's an exception caught when trying to inject the confirmation bar UI. So, #247 catches that and just goes ahead and snoozes the tab rather than failing silently.
