### ISSUE TITLE
Snooze Tab notification should have focus when show

### ISSUE THREAD

**Issue by johngruen** [bwinton/SnoozeTabs#198]
So that i can dismiss the snooze tab notification with a keypress, the notification should take focus when show.

**Comment by lmorchard** [comment]
Not sure what you mean here... the operating system notification bubble? Not sure we can affect that with focus or keypress events

**Comment by johngruen** [comment]
<img width="363" alt="screen shot 2017-02-22 at 2 47 17 pm" src="https://cloud.githubusercontent.com/assets/3323249/23229342/f229a25c-f90d-11e6-8f8a-d1f59feeebdb.png">

Sorry, @lmorchard i mean the Snooze drop down thing.

**Comment by bwinton** [comment]
So, I tried to do this a few ways, but nothing seemed to work.  (You would think `okButton.focus()` would focus it, but no…)

**Comment by johngruen** [comment]
worth investigating, but probably not a blocker.

**Comment by lmorchard** [comment]
Don't think we're going to be able to make this one happen

**Comment by lmorchard** [comment]
Tried doing some focus things after moving the bar into an iframe, didn't work there either. Going to say this isn't working
