### ISSUE TITLE
Redesign the popup

### ISSUE THREAD

**Issue by nt1m** [bwinton/SnoozeTabs#2]
The popup looks kinda outdated compared to the current Australis design.
I think it should look a bit more like this :
http://people.mozilla.org/~shorlander/mockups-interactive/australis-interactive-mockups/windows8.html

The changes I suggest : 
- Remove the background behind the popup (the light gray one), so it can integrate with the latest popup style
- Make the hover effect flat
- Use font:menu

**Comment by rugk** [comment]
What about https://github.com/bwinton/SnoozeTabs/issues/11?
