### ISSUE TITLE
Closing snooze tabs doorhanger throws "Popup destroyed" error

### ISSUE THREAD

**Issue by 6a68** [bwinton/SnoozeTabs#202]
In release channel Firefox (51.0.1), clicking the snooze tabs toolbar button twice in a row generates an `Error: Popup destroyed` line in the Browser Console, pointing at [this line](https://dxr.mozilla.org/mozilla-release/source/browser/components/extensions/ext-utils.js#132) in `ext-utils.js`.

Looks like [bugzilla bug 1259093](https://bugzilla.mozilla.org/show_bug.cgi?id=1259093) might be relevant--searching that page for 'destroyed' turns up a lot of discussion of this exact spot in the code.

Not sure what the bug is, nor what a good workaround might be. Pinged @kmaglione in IRC, hopefully he can offer some advice.

**Comment by lmorchard** [comment]
I'd seen this error, but hadn't seen any obvious effects from it. Is there something you're seeing?

**Comment by lmorchard** [comment]
FWIW, I'm pretty sure this is an upstream WebExtension thing. I'm playing with [another dead-simple WebExtension to explore varying styles between toolbar & menu button placements](https://github.com/lmorchard/webextension-toolbar-vs-menu) and seeing this error there too.

**Comment by lmorchard** [comment]
Going to call this an upstream thing that I don't think we can affect. Also doesn't seem to be causing the "run slow" message.
