### ISSUE TITLE
Use Intl for formatting date and times in toolbar panel

### ISSUE THREAD

**Issue by flodolo** [bwinton/SnoozeTabs#204]
Right now we have custom formats only for Italian and German, we should cover all locales working on it.

**Comment by flodolo** [comment]
I've started looking into it, based on CLDR and moment.js existing formats. As expected, I'm stuck with Chinese and Japanese (sorry for butchering your language), and not completely sure about Germanic languages.

![de](https://cloud.githubusercontent.com/assets/3644868/23247752/14573fea-f99c-11e6-9018-38adeaee3d7e.png)
@Archaeopteryx
Does the date/time format make sense for German?

@mikkcz
Ignore the fact that this is a German screenshot. Does the date/time format make sense for Czech?

![zh-tw](https://cloud.githubusercontent.com/assets/3644868/23247771/3a3e0a68-f99c-11e6-8e77-dfbea96a2cd5.png)
@petercpg
Does it make any sense for zh-TW?

![ja](https://cloud.githubusercontent.com/assets/3644868/23247826/7fdc8f68-f99c-11e6-88dc-97e61972936b.png)
@kyoshino
Does this make any sense for ja?

**Comment by flodolo** [comment]
This is the code generating those screenshots
https://github.com/flodolo/SnoozeTabs/commit/398110a6bd8f8e5baef65e0c8422c3fc219418a1

**Comment by flodolo** [comment]
@tomer @robertoalvarado
Any feedback on the localization format for your locales in https://github.com/flodolo/SnoozeTabs/commit/398110a6bd8f8e5baef65e0c8422c3fc219418a1 ? 

Not sure about the RTL mess just switching general.useragent.locale

## Mexican Spanish

![esmx](https://cloud.githubusercontent.com/assets/3644868/23248155/30f6a850-f99e-11e6-9804-611739a737ab.png)

## Hebrew

![he](https://cloud.githubusercontent.com/assets/3644868/23248159/366841a4-f99e-11e6-9702-7177e970b77e.png)

**Comment by flodolo** [comment]
When there are Snoozed Tabs, the Manage panel is not correctly localized, need more date/time formats for that.

**Comment by flodolo** [comment]
More code available here, added localization formats for dates. English uses 'MMM D, YYYY' and 'ddd, MMM D'

https://github.com/bwinton/SnoozeTabs/pull/205/files

This is the Manage panel localized in Italian

![schermata 2017-02-23 alle 08 29 52](https://cloud.githubusercontent.com/assets/3644868/23249049/b26f8402-f9a2-11e6-9b7b-1471774b59e1.png)

**Comment by belkacem77** [comment]
Hi Francesco,
For the Kab locale we got
![2017-02-23 08_28_35-](https://cloud.githubusercontent.com/assets/7033740/23249033/a3ffea06-f9a2-11e6-99d2-5cb30358ab36.jpg)
and
![2017-02-23 08_29_162-](https://cloud.githubusercontent.com/assets/7033740/23249053/b5536fee-f9a2-11e6-86ca-48d4e4493de2.jpg)

Are dates and format picked from CLDR?

**Comment by flodolo** [comment]
No, they're not picked from CLDR. I assume kab uses the same format as French?

**Comment by petercpg** [comment]
> @petercpg
> Does it make any sense for zh-TW?

@flod couple things to fix:

- date should be put before week day, and add '日' as suffix  (eg, 3 月 23 日 週四)
- for time, AM/PM should be put before time, also add '時' as suffix (eg, 早上 9 時)
- when it's too long, break before or after '@' to keep date and time in one line respectively

**Comment by belkacem77** [comment]
@flodolo 
Yes, kab has same format as fr but short format of days and the name of months are still in English.

**Comment by flodolo** [comment]
Unfortunately you would need to translate them over at
http://momentjs.com/

@allAfter chatting with Gandalf over IRC, I want to check if it's possible to use CLDR and Intl for this.

**Comment by belkacem77** [comment]
Let's translate them on momentjs.com

**Comment by flodolo** [comment]
> Let's translate them on momentjs.com

I might be able to use Intl and CLDR, so it might not be necessary for this specific case.

**Comment by MikkCZ** [comment]
Hi @flodolo. No, it does not make sense for Czech. First we do not use dot after the day abbreviation, but that is cosmetic compared to the time formát "@ 9". We do not understand @ as "ať". I think keeping the English am and pm would make more sense. It will look like it's just not localized and only make some people unsure if it's morning or afternoon time, but they will know it's time.

**Comment by flodolo** [comment]
@bwinton 
This needs a real developer, but it might something to start from
https://github.com/flodolo/SnoozeTabs/commit/3a6816bb47b686007f5bc60485d4aaa3aa623605

From top to bottom: Italian, Czech, English, Traditional Chinese, Kabyle.

![intl](https://cloud.githubusercontent.com/assets/3644868/23254042/ecc29856-f9b6-11e6-86a6-6ca2eed1c94e.png)

**Comment by Archaeopteryx** [comment]
Issues for German:
- "@" won't be understood as "at" (or "um" in German)
- standalone hour digits won't be understood, use "N Uhr" or "09:13" instead
- no fullstop after the abbreviated weekday, please
- "Do 23.03. 09:13" is better than "Do 23. Mrz. 9 Uhr"

**Comment by flodolo** [comment]
I'm going to remove the old images because they would only create confusion, will add German localization with the current approach instead.

**Comment by flodolo** [comment]
From the top: German, Japanese, Hebrew

![senza titolo](https://cloud.githubusercontent.com/assets/3644868/23259125/cbfe40d8-f9cb-11e6-98a6-9039c97e768a.png)

**Comment by Archaeopteryx** [comment]
For German:
- Now it's the fill month, matters more if you use "September"
- The comma after the month name should be dropped
But if I remember correct, that's hardcoded in the cldr. For the second issue, there is an open bug there.

**Comment by petercpg** [comment]
one more issue for zh-tw: for snoozes until 'tomorrow' and 'this weekend', the line break should be in between the weekday and time, so the examples for this screenshot should be like:
　　週五
上午 9:00

**Comment by flodolo** [comment]
There's no line break in the text itself, so it should be something to fix in the layout (space too narrow).

**Comment by bwinton** [comment]
Removing the moment-locales (since we're not using them) also cuts 143K off the zip, which is a nice side-benefit…  🙂

**Comment by kyoshino** [comment]
Japanese: LGTM.

**Comment by MikkCZ** [comment]
The last screenshot for Czech looks good. :)
