### ISSUE TITLE
The bottom years slightly overlap the calendar border from the "Pick a Date/Time" panel

### ISSUE THREAD

**Issue by SoftVision-EmilPasca** [bwinton/SnoozeTabs#213]
[Affected versions]:
- Nightly 54.0a1
- Snooze Tabs 1.0.15 (built on 02/24/2017)

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Have a Firefox profile with the latest Snooze Tabs add-on version (1.0.15 -dev, built on 02/24/2017) loaded as a temporary add-on.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisite and navigate to any website.
2. Click on the "SnoozedTabs" button.
3. Click on the "Pick a Date/Time" option.
4. Click on the Month/Year text to choose a decade or a century time frame.
6. Observe the year at the bottom of the calendar.

[Expected result]:
- The year is displayed within the calendar borders.

[Actual result]:
- The year slightly overlaps the calendar bottom border.

[Notes]:
- Attached a screen recording of the issue:
![snoozetabs_calendar_year_century](https://cloud.githubusercontent.com/assets/20083658/23312244/b428791e-fac1-11e6-832d-618bfdf8c5e7.gif)

**Comment by bwinton** [comment]
Hmm…  https://cl.ly/1W1W1H2N1x2I
