### ISSUE TITLE
Empty space at the bottom of the panel in prod builds

### ISSUE THREAD

**Issue by lmorchard** [bwinton/SnoozeTabs#214]
When "Real Soon Now" is removed from the main panel of snooze options, the panel doesn't shrink. Instead there's an empty space. [I tried addressing it with a simple CSS fix](https://github.com/bwinton/SnoozeTabs/pull/190), but that bumped other things around. This should still be fixed though

**Comment by bwinton** [comment]
Could we have an extra CSS file load in development mode that re-sets the height to something nicer?  ;)
