### ISSUE TITLE
SnoozeTabs does not function inside the test pilot site

### ISSUE THREAD

**Issue by phena109** [bwinton/SnoozeTabs#216]
As title, I try to snooze myself to visit the following page as I think it's good I come back on an occasional bases. But no matter how many times I set, it still doesn't give me the confirmation dialog while other sites are fine.

While I maybe wrong because I didn't go all out to test the whole pilot site and every other site, but I just feel that the pilot site is a bit of special so SnoozeTabs handles it differently or some characteristics of the site make SnoozeTabs behave a certain way.

- https://testpilot.firefox.com/
- https://testpilot.firefox.com/experiments/snooze-tabs

Using Mac Sierra and Firefox 51, basically up to date.

Hope you can look into this.

Cheers,
phena109

**Comment by lmorchard** [comment]
Thanks for the bug report! I think this is the same as issue #197, so I'll close this one and we'll track a fix on that issue.
