### ISSUE TITLE
Snoozetabs not working on 51.0.1 (32-bit)

### ISSUE THREAD

**Issue by Servelan** [bwinton/SnoozeTabs#218]
I have several tab-related extensions, and disabled the biggest, Tab Mix Plus to see if that would resolve the issue.  It did not.  Former software tester willing to help resolve the problem, but not sure where to start.

**Comment by pdehaan** [comment]
@Servelan what OS/version are you using?

**Comment by prashant363** [comment]
I encountered the same issue. Snooze tab didn't work on 51.0 - 32 bit , Win 7 64 bit.
Checked Manage Snooze section. it is being displayed empty as well

**Comment by lmorchard** [comment]
Thanks for the report! For further clarification: What about Snooze Tabs is not working? Does the panel not come up at all when the toolbar button is clicked? Does that work, but snoozing a tab does not? More details are helpful. Screenshots especially so!

**Comment by prashant363** [comment]
@imorchard 
Regarding your comment above 

The panel comes up when the toolbar button is clicked.
However snoozing a tab seems to be not working on 51.0 - 32 bit , Win 7 64 bit.
Refer attached video, i have created for the behavior( hope the step followed are correct :) )
[snooze.zip](https://github.com/bwinton/SnoozeTabs/files/804401/snooze.zip)

**Comment by lmorchard** [comment]
Okay, the issue in the video looks like Issue #197 - Snooze Tabs currently does not work on the Test Pilot site due to very strict CSP security settings. Does Snooze Tabs work on other sites? (e.g. nytimes.com, qz.com, etc)

**Comment by prashant363** [comment]
Thanks for the quick response @imorchard. The snooze tab works for Google News(google.co.in) and other sites . Should have done that earlier. :) 

Checked on FF 51.0  , Win 7 64 bit.

**Comment by lmorchard** [comment]
>  Should have done that earlier. :)

Eh, it *should* be surprising that this doesn't work on Test Pilot itself 😞 Thanks for checking though!

**Comment by Servelan** [comment]
Restarting
          the browser a couple of times seems to have made it work now.
        
    
    
    On 2/27/2017 9:08 AM, prashant363
      wrote:
    
    
      @imorchard
        Regarding your comment above
      The panel comes up when the toolbar button is clicked.
        However snoozing a tab seems to be not working on 51.0 - 32 bit
        , Win 7 64 bit.
        Refer attached video, i have created for the behavior( hope the
        step followed are correct :) )
        snooze.zip
      —
        You are receiving this because you were mentioned.
        Reply to this email directly, view
          it on GitHub, or mute
          the thread.
      
        
          
          
        
        
      
      {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/bwinton/SnoozeTabs","title":"bwinton/SnoozeTabs","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/bwinton/SnoozeTabs"}},"updates":{"snippets":[{"icon":"PERSON","message":"@prashant363 in #218: @imorchard \r\nRegarding your comment above \r\n\r\nThe panel comes up when the toolbar button is clicked.\r\nHowever snoozing a tab seems to be not working on 51.0 - 32 bit , Win 7 64 bit.\r\nRefer attached video, i have created for the behavior( hope the step followed are correct :) )\r\n[snooze.zip](https://github.com/bwinton/SnoozeTabs/files/804401/snooze.zip)\r\n\r\n\r\n"}],"action":{"name":"View Issue","url":"https://github.com/bwinton/SnoozeTabs/issues/218#issuecomment-282783728"}}}

**Comment by ckprice** [comment]
Closing as a dup of #197
