### ISSUE TITLE
Tabs are loaded without being selected on Startup

### ISSUE THREAD

**Issue by chuckharmston** [bwinton/SnoozeTabs#219]
Copied from https://github.com/mozilla/pulse/issues/132

> I've noticed that tabs except for Pinned tabs aren't loaded on startup until they are actually switched/clicked to. But Snoozed Tabs "Next Open" option does not respect this feature/option. This slows down Firefox startup time and responsiveness.
> 
> I think it should behave the same as other tabs to prevent any slowdown during startup. This is especially an issue if multiple tabs were snoozed to "Next Open".
> 
> I think(not sure) the variable/option I'm talking about is: browser.sessionstore.restore_on_demand

CC @Nidre

**Comment by SoftVision-EmilPasca** [comment]
I've managed to reproduce this on the latest Snoozetabs 1.0.15-dev (build 02/27/2017).

**Comment by lmorchard** [comment]
Hmm, I don't think this is a think we can do with WebExtension APIs. We can open tabs on startup, but I don't think we can open the kind of deferred tabs that the browser itself opens on startup.

**Comment by bwinton** [comment]
Closing as impossible, though I think we would like to do it if we could.  :wink:
(Actually, if someone wants to add a bug on the WebExtensions component in Bugzilla, asking for background tabs to be not loaded according to the preferences of `browser.sessionstore.restore_on_demand`, that seems like a way of getting this closer to being fixed.)
