### ISSUE TITLE
Customizable time drop down and 'pick a date/Time' option are displayed intermittently

### ISSUE THREAD

**Issue by prashant363** [bwinton/SnoozeTabs#222]
Snoozing a tab for say @3am is impossible as clock to set time is displayed intermittently.
The same is the case with 'pick a Date/Time' 

Is this expected? or a certain step needs to performed for it?

Environment: Win 7, 64 bit , FF 51
[Manage_snooze_customTime.zip](https://github.com/bwinton/SnoozeTabs/files/804543/Manage_snooze_customTime.zip)

**Comment by SoftVision-EmilPasca** [comment]
Thank you for reporting this @prashant363. However, I think this is a duplicate of #179.

**Comment by prashant363** [comment]
Thankyou @SoftVision-EmilPasca  :)
