### ISSUE TITLE
On startup, tabs are opened before I choose to restore session

### ISSUE THREAD

**Issue by lukasbalaz** [bwinton/SnoozeTabs#225]
I use Tab Mix Plus Add-on and it always asks me if I want to restore previous session on startup. But snoozed tabs open before the session is restored and then they are overwritten (with no way to get them back). Maybe add an option to "ask before opening", something like "Yes, open the tabs" or "Nope, wait 5 minutes".

**Comment by SoftVision-EmilPasca** [comment]
Hi @lukasbalaz, thank you for reporting this issue.
As discussed in #219, handling this kind of tabs or adding an option like  "ask before opening" on startup when session is restored might not be possible due to WebExtension APIs.
