### ISSUE TITLE
The "Mozilla" logo is not displayed in the SnoozedTabs notification on Windows and Linux

### ISSUE THREAD

**Issue by SoftVision-EmilPasca** [bwinton/SnoozeTabs#226]
[Notes]:
- On Mac OS, "Mozilla" logo is displayed in the notification.
- Based on the following design: https://mozilla.invisionapp.com/share/MV9F846SY#/screens two images should be displayed in the notification.

[Affected versions]:
- Nightly 54.0a1
- Snooze Tabs 1.0.15 (built on 02/28/2017)

[Affected Platforms]:
- All Windows
- All Linux

[Prerequisites]:
- Have a Firefox profile with the latest Snooze Tabs add-on version (1.0.15 -dev, built on 02/28/2017) loaded as a temporary add-on.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisite and navigate to any website.
2. Click on the "SnoozedTabs" button from the Toolbar.
3. Select any snoozing option e.g. "Real Soon".
4. Wait until the SnoozedTabs notification is displayed and observe the notification elements.

[Expected result]:
- All the elements are correctly displayed in the notification.

[Actual result]:
- All the elements are correctly displayed except the "Mozilla" logo.

[Additional Notes]:
- Attached a screen recording of the issue:
![snoozetabs_notification_recording](https://cloud.githubusercontent.com/assets/20083658/23402084/c7cf6498-fdb2-11e6-8e35-5377d783e3b6.gif)

**Comment by bwinton** [comment]
Huh.  Yeah, apparently we're [looking for](https://github.com/bwinton/SnoozeTabs/blob/master/src/background.js#L274) the non-existent `link.png`…  We should fix that.

**Comment by SoftVision-EmilPasca** [comment]
The issue is no longer reproducible on the latest Snooze Tabs version (1.0.15-dev built on 03/01/2017).
