### ISSUE TITLE
SnoozeTabs context-menu is wrongly displayed for websites opened in Private Window tabs

### ISSUE THREAD

**Issue by SoftVision-EmilPasca** [bwinton/SnoozeTabs#228]
[Affected versions]:
- Nightly 54.0a1
- Snooze Tabs 1.0.15 (built on 02/28/2017)

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Have a Firefox profile with the latest Snooze Tabs add-on version (1.0.15 -dev, built on 02/28/2017) loaded as a temporary add-on.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisite.
2. Open a New Private Window (Ctrl+Shift+P) and navigate to any website.
3. Right-click on the opened tab and observe the context-menu.

[Expected result]:
- The SnoozeTabs context-menu is not displayed since SnoozeTabs should not work in Private Window.

[Actual result]:
- The SnoozeTabs context-menu is wrongly displayed in Private Window.

[Additional Notes]:
- Attached a screen recording of the issue:
![snoozetabs_private_window](https://cloud.githubusercontent.com/assets/20083658/23411614/7a69294a-fddb-11e6-93ac-8cd70193a668.gif)

**Comment by lmorchard** [comment]
This might not be an issue we can fix. Looking through [the WebExtension contextMenus API docs](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/contextMenus): You get a context menu on all tabs or none at all. There's no facility for deciding tab-by-tab.

Considered using a `tabs.onActivated` event handler to disable the menu, but that doesn't help us when the menu is activated on another tab in the tab bar.

For what it's worth, [we do bail out of actually snoozing the tab in Private Browser mode](https://github.com/bwinton/SnoozeTabs/blob/master/src/background.js#L315).

**Comment by lmorchard** [comment]
Going to say this is a wontfix
