### ISSUE TITLE
Page styles affect text in dropdown notification.

### ISSUE THREAD

**Issue by ericawright** [bwinton/SnoozeTabs#231]
On certain pages the page styles will apply to the drop-down notification. For example on this customizing mercurial page it seems to add a text shadow.

<img width="598" alt="screen shot 2017-03-02 at 9 17 32 am" src="https://cloud.githubusercontent.com/assets/10803178/23510959/92480244-ff29-11e6-9493-809530ed7f98.png">

**Comment by lmorchard** [comment]
Yeah, I'm not sure there's a good way to handle this across the board. Seems like it will always be a game of site-by-site whack-a-mole :/ Tried finding a good modern complete CSS reset that we could scope to the bar, but didn't have much luck yet

**Comment by lmorchard** [comment]
PR #231 fixes this particular issue, but I don't have a great idea for a general solution.

**Comment by lmorchard** [comment]
(whoops! forgot to actually submit the PR until now)
