### ISSUE TITLE
Update has deleted old snoozed tabs.

### ISSUE THREAD

**Issue by AussieGit** [bwinton/SnoozeTabs#237]
Installed the latest snoozetabs via Test Pilot and found that tabs snoozed under previous version issued March 2016 were all deleted & now there is no way to recover them. Warning should be issued to either backup previous tabs prior to installing latest version or move older snoozed tabs to a different folder within bookmarks.

Can I suggest that option be made available to export/back up snoozed tabs to avoid further issues such as this and also to be able to change the default snoozed times/periods.

Otherwise one of my top 3 extensions that is crucial to me web surfing and productivity.

**Comment by lmorchard** [comment]
Do you mean that the set of tabs you had waiting to wake under "Manage Snoozed Tabs" in the Snooze Tabs experiment were deleted after an update? If that's the case, then this is an unexpected issue. Updates shouldn't affect the set of tabs waiting to wake.

Or, do you mean that bookmarks in the "Snoozed Tabs" folder were deleted? If that's the case, then this is expected. That folder isn't meant to retain or archive previously snoozed tabs. It's just a backup of the current set waiting to wake.

**Comment by AussieGit** [comment]
Deleted everything. The previous version of snoozedtabs I had been using since Mar '16 used folder in my bookmarks called snoozetabs to store each of snoozed tab. I thought this was the default saving file and not a backup. After installing the new snoozetab version (please note that it was NOT an update but a new install, I still have the icon in my menu bar for the old version & the new version. However the 40-50 snoozedtabs I had under the older version are now gone. Clicking in manage snoozed tabs in the old version just brings up a list of the new snoozedtabs so all my older ones are deleted. I wasnever given an option to backup or even to update the previous version, simply a new install.

**Comment by lmorchard** [comment]
> After installing the new snoozetab version (please note that it was NOT an update but a new install, I still have the icon in my menu bar for the old version & the new version. However the 40-50 snoozedtabs I had under the older version are now gone. 

Did you install a version of Snooze Tabs from before [the Test Pilot releases on 2/21](https://github.com/bwinton/SnoozeTabs/releases)? That might explain things, since the Test Pilot release is basically an entirely new add-on project rebooted from the old prototype. Data wasn't deleted so much as not shared or carried over at all to the new project.

**Comment by sNiXx** [comment]
Follow-up question to this problem and the mentioned fix: If Snooze Tabs - for whatever reason - creates a new folder and the old tabs no longer show under "Manage Snooze Tabs" how can we restore the backed up tabs?
