### ISSUE TITLE
Add calendar event when you snooze a tab

### ISSUE THREAD

**Issue by ckprice** [bwinton/SnoozeTabs#238]
This was submitted by a contributor via email

> 1) Is it possible to have a setting that allows us to have an event imported into our calendar every time we schedule a snooze?
> I've been snoozing to basically get my courses on coursera/edX/MOOCS in general all organized with my study plan, and having this automatically done would be superb!!!
> 
> 2) Would that be possible to find a way to sync different time zones for the snooze and for the eventual importing on the calendar?
> I discuss with people in about 8-10 different cities/time zones, and it's pretty messy to have my iCalendar organized, even with google's tool supposedly to help us with that I get messed up very often. Perhaps we can find a way to make it better.

I've given them a link to this, and will let them ask any follow-up.

**Comment by orah** [comment]
Thank you, Cory!

**Comment by wresuolc** [comment]
Thanks for the suggestion.  This is a really cool idea, but it's a bit too complex for us to look at as an experiment right now (and maybe not even possible as a webextension).  Thanks again.
