### ISSUE TITLE
The SnoozedTabs notification is not displayed on Windows in browser Fullscreen mode

### ISSUE THREAD

**Issue by SoftVision-CarmenFat** [bwinton/SnoozeTabs#239]
[Notes]:
- This issue is not reproducible on Mac OS or Linux.
- If another window is focused, then the notification is displayed.

[Affected versions]:
- Nightly 54.0a1
- Snooze Tabs 1.0.15 (built on 06/03/2017)

[Affected Platforms]:
- All Windows

[Prerequisites]:
- Have a Firefox profile with the latest Snooze Tabs add-on version (1.0.15 -dev, built on 06/03/2017) loaded as a temporary add-on.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisite and navigate to any website.
2. Click on the "SnoozedTabs" button from the browser toolbar.
3. Click on the "Real Soon Now!" button.
4. On Confirmation notification, click "OK".
5. Press F11 and wait for the SnoozedTabs notification to be displayed.

[Expected result]:
- The SnoozedTabs notification is displayed.

[Actual result]:
- The SnoozedTabs notification is not displayed.

**Comment by lmorchard** [comment]
Do any browser notifications display at all in fullscreen? I don't think this is a think in particular that we can influence in Snooze Tabs.

**Comment by ckprice** [comment]
Going to close this because we don't think notifications show in full screen mode. Feel free to re-open if other notifications are showing.
