### ISSUE TITLE
Add acceptance criteria

### ISSUE THREAD

**Issue by johngruen** [bwinton/SnoozeTabs#24]

**Comment by johngruen** [comment]
## UX
- [ ] It should provide a toolbar button that exposes the Snooze Tabs Interface
- [ ] it should give the user a list of Snooze Times
- [ ] it should provide the user the ability to set a custom snooze time
- [ ] it should provide a visual affordance to let the user know they have snoozed the tab.
- [ ] It should bring back the tab (wake) in the background at the appointed time, or at the beginning of the next session if the browser is closed.
- [ ] it should trigger a push notification indicating the tab  as been ‘woken’
- [ ] it should put an activity indicator on the woken tab
- [ ] it should allow the user to see a list of currently snoozed tabs
- [ ] it should allow users to cancel currently snoozed tabs
- [ ] it should allow the user to see a list of previously snoozed tabs
- [ ] it should allow users to open currently snoozed tabs
- [ ] it should put all snoozes in a specific bookmarks folder
- [ ] it should allow users to enter their snooze bookmarks folder from the panel

## Measurements
- [ ] It should measure each time the snooze panel is opened
- [ ] It should measure each time  a user choses to snooze
- [ ] It should measure which snooze duration is chosen each time
- [ ] it should measure custom snooze durations
- [ ] It should measure the rate at which snooze tabs wake up
- [ ] it should measure if users focus previously snoozed tabs
- [ ] it should measure if users close a previously snoozed tab without refocusing
- [ ] it should measure if users re-snooze a tab
- [ ] it should measure snooze cancellations
- [ ] it should measure clicks on currently snoozed tabs
- [ ] it should measure clicks into bookmarks folder from the panel

## Dashboards
- [ ] Snoozes/Panel Opens
- [ ] Distribution of snooze durations (incl. custom durations)
- [ ] Resnoozes/Snoozes
- [ ] Cohort Engagement
- [ ] Focus vs Close after Snooze
- [ ] clicks on currently snoozed tabs/panel opens
- [ ] clicks on snooze bookmarks/panel opens

## experiments (require UX)
- [ ] It should optionally ask users if they’d like to close tabs when they are snoozed. This experiment should be conducted by a limited cohort and should measure response rates.

**Comment by sevaan** [comment]
Proposed UX: https://mozilla.invisionapp.com/share/MV9F846SY

**Comment by lmorchard** [comment]
Just to get this out of issues, I copied things over here to a wiki page:

https://github.com/bwinton/SnoozeTabs/wiki/Acceptance-Criteria
