### ISSUE TITLE
Snooze until <device> next open

### ISSUE THREAD

**Issue by Nidre** [bwinton/SnoozeTabs#244]
This is not an issue, but a feature request/idea.

**Why?**
I'm using Firefox on multiple devices on both work and home. They are synced using Firefox's sync service. I wanted to remember about a page when I was back home and opened my Firefox instead of a specific time. Just want to stress that this is a bit different than setting time for when I would be at home. Rather having it open as soon as I start my session on my other synced Firefox.

**How?**
So it would basically mean **Next Open ([synced device name])**.
Maybe something like that;

**Next Open other Device**
-[device 1]
-[device 2]

**Comment by sevaan** [comment]
Great idea! I would totally use this.

**Comment by wresuolc** [comment]
Thanks for the suggestion.  It sounds like we can't actually do this as a webextension (yet -- those APIs might be coming).  Closing for now
