### ISSUE TITLE
The "Trash can" button is not displayed when enabling High contrast white OS theme on Windows

### ISSUE THREAD

**Issue by SoftVision-CarmenFat** [bwinton/SnoozeTabs#245]
[Affected versions]:
- Nightly 55.0a1
- Snooze Tabs 1.0.15 (built on 07/03/2017)

[Affected Platforms]:
- All Windows.

[Prerequisites]:
- Have a Firefox profile with the latest Snooze Tabs add-on version (1.0.15 -dev, built on 07/03/2017) loaded as a temporary add-on.
- High contrast white OS theme on Windows is enabled.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisite and navigate to any website.
2. Click on the "SnoozedTabs" button from browser toolbar.
3. Click on the "Later Today" button.
4. Click "OK" on the Confirmation notification.
5. Click on the "SnoozedTabs" button from browser toolbar.
6. Click the "Manage Snoozed Tabs" button.
7. Hover the items displayed in the list and observe the "Trash can" button.

[Expected result]:
- The "Trash can" button is displayed to the right side of the snoozed item.

[Actual result]:
- The "Trash can" button is not displayed.

[Notes]:
- Clicking the blank area removes the website from the SnoozedTabs list.
- Please see the Screen Cast attached:
![no trash can](https://cloud.githubusercontent.com/assets/26000308/23662553/ab55d04e-0358-11e7-99c5-932ba76cf71b.gif)

**Comment by wresuolc** [comment]
This isn't something we'll work on for snooze tabs as an experiment.  Thanks for filing.
