### ISSUE TITLE
The snooze options panel is shortly displayed when clicking the "Snooze Tabs" button on special urls 

### ISSUE THREAD

**Issue by SoftVision-CarmenFat** [bwinton/SnoozeTabs#252]
[Affected versions]:
- Nightly 55.0a1
- Snooze Tabs 1.0.15 (built on 08/03/2017)

[Affected Platforms]:
- All Windows
- All MAC OS
- All Linux

[Prerequisites]:
- Have a Firefox profile with the latest Snooze Tabs add-on version (1.0.15 -dev, built on 08/03/2017) loaded as a temporary add-on.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites.
2. Navigate to a special url (about:addons, about:debugging etc.).
3. Click on the SnoozedTabs button.
4. Repeat step 3 few times and observe panel's behaviour.

[Expected result]:
- Manage Snoozed Tabs list is displayed.

[Actual result]:
- Snoozing options panel appears for a brief second, then the Manage Snoozed Tabs list is displayed.

[Notes]:
- Please see the Screen Cast attached:
![options panel](https://cloud.githubusercontent.com/assets/26000308/23703013/772993e2-0406-11e7-9f71-90db2f58e7c3.gif)

**Comment by lmorchard** [comment]
I don't think we have good options to address this. Might be a wontfix.

As part of #79, there's now an initial static rendering of the time choices in the HTML that gets displayed while the rest of the JS loads & starts up. But, until the JS loads, we don't have any mechanism to detect whether the current tab is eligible for snoozing and thus switch to the management panel. So, you'll see the list of times as a "loading" panel.

An alternative could be that we display a less specific "loading" panel until everything's ready, but that seems too obtrusive. The list of times works as a quick stand-in for most other use cases.

**Comment by wresuolc** [comment]
This is within experimental tolerance. :)  -> wontfix
