### ISSUE TITLE
If the button is moved in Firefox menu, the "Manage Snoozed Tabs" pannel cannot be scrolled while on special URLs

### ISSUE THREAD

**Issue by SoftVision-CarmenFat** [bwinton/SnoozeTabs#253]
[Affected versions]:
- Nightly 55.0a1
- Snooze Tabs 1.0.15 (built on 08/03/2017)

[Affected Platforms]:
- All Windows
- All MAC OS
- All Linux

[Prerequisites]:
- Have a Firefox profile with the latest Snooze Tabs add-on version (1.0.15 -dev, built on 08/03/2017) loaded as a temporary add-on.
- Have more than 20 snoozed pages on the same profile.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites. 
2. Right click on the SnoozedTabs button and click on "Move to Menu".
3. Click on the Hamburger menu and then on the SnoozedTabs button.
4. Observe the doorhanger aspect and choose to scroll the list.

[Expected result]:
- The "SnoozedTabs" doorhanger has the same length and width as when displayed in toolbar and all items are reachable trough scrolling.

[Actual result]:
- The doorhanger's length is increased and some of the snoozed websites are not reachable because the list cannot be scrolled.

[Notes]:
- Please see the Screen Cast attached:
![scroll list](https://cloud.githubusercontent.com/assets/26000308/23711344/44633a5e-0428-11e7-9969-7d2aa6dd9b5e.gif)

**Comment by wresuolc** [comment]
@SoftVision-CarmenFat can you recheck this?  The latest release may have fixed it

**Comment by SoftVision-CarmenFat** [comment]
The issue is no longer reproducible with the latest Snooze Tabs release (v. 1.0.15).

![scroll](https://cloud.githubusercontent.com/assets/26000308/24198645/539549e4-0f0f-11e7-8abd-8173989f969e.jpg)
