### ISSUE TITLE
Several UI issues occur on FR and DE builds, if the SnoozedTabs button is moved in the Firefox menu

### ISSUE THREAD

**Issue by SoftVision-CarmenFat** [bwinton/SnoozeTabs#262]
[Affected versions]:
Nightly 55.0a1
Snooze Tabs 1.0.15 (built on 14/03/2017)

[Affected Platforms]:
All Windows
All MAC OS
All Linux

[Prerequisites]:
Have a Firefox profile with the latest Snooze Tabs add-on version (1.0.15 -dev, built on 14/03/2017) loaded as a temporary add-on.
Have the Francais [fr] and the Deutsch [de] Firefox locale builds installed.

[Steps to reproduce]:
1. Open one of the localised Firefox builds with the profile from prerequisites and navigate to a website.
2. Right click on the Snooze Tabs button and choose the first option.
3. Click on the Hamburger Menu and then on the SnoozeTabs button.
4. Observe the way the items are displayed.

[Expected result]:
All the items are visible and can be reached out.

[Actual result]:
Some of the items are wrongly displayed:

- For the French locale build:

Windows:
“Later today”, “Next week” date/time and “Pick a Date/Time” arrow are misaligned with the others.
Part of the Confirmation notification checkbox is displayed in the Options Panel.

MAC OS:
"Later today" doesn't display any hour.
"Next week" and "Next month" are misaligned with the others.
The “Pick a Date/Time” arrow is not displayed.
Part of the Confirmation notification checkbox is displayed in the Options Panel.

- For the German locale build:

Windows:
“This weekend” date/time is misaligned with the others.
The “Pick a Date/Time” arrow is not displayed.

MAC OS:
"Real soon now!", "Later today" and “This weekend” date/time are misaligned with the others.
The “Pick a Date/Time” arrow is not displayed.
Part of the Confirmation notification checkbox is displayed in the Options Panel.

[Notes]:
The part of the Confirmation notification box is functional, it can be checked and unchecked.
Please see the Screenshot attached:
![ui](https://cloud.githubusercontent.com/assets/26000308/23912711/3a37d31c-08e9-11e7-9565-dd01e3a16db5.jpg)

**Comment by wresuolc** [comment]
@SoftVision-CarmenFat can you recheck this?  The latest release may have fixed this

**Comment by SoftVision-CarmenFat** [comment]
Tested this again using the latest Snooze Tabs release (v. 1.0.15) but the issues are still reproducible.

**Comment by SoftVision-CarmenFat** [comment]
Hi @bwinton,

I verified this issue again on the latest Snooze Tabs version (1.0.17 built on 04/14/2017) and everything seems to be fixed, but a little exception: on the "Manage Snooze Tabs" panel, the left border of the checkbox is still missing.  
Please see the screenshot attached:

![border missing](https://cloud.githubusercontent.com/assets/26000308/25043521/4a119b8a-2129-11e7-9ba9-73ee0b769171.jpg)

**Comment by SoftVision-CarmenFat** [comment]
The issue is no longer reproducible on the latest Snooze Tabs version (1.0.18 - built on 04/24/2017).
The checkbox from the "Manage Snoozed Tabs" panel is fully displayed.
