### ISSUE TITLE
Only one SnoozeTabs notification is displayed on Windows, if two or more tabs are snoozed

### ISSUE THREAD

**Issue by SoftVision-CarmenFat** [bwinton/SnoozeTabs#265]
[Affected versions]:
- Firefox Release 52.0

[Affected Platforms]:
- All Windows

[Prerequisites]:
- Have a Firefox profile with the latest Snooze Tabs add-on (
https://378-15314951-gh.circle-artifacts.com/0/tmp/circle-artifacts.ipWadCV/snoozetabs-1.0.15.zip) loaded as a temporary add-on.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites and navigate to any website in a new tab.
2. Click on the Snooze Tabs button and choose one of the options (eg: "Next open").
3. Repeat step 2 with another website.
4. Quit Firefox, then open it again.
5. Observe the behaviour of the unsnoozed tabs and their notifications.
 
[Expected result]:
- Tabs are brought back unfocused in 2 new tabs and each has favicons displaying an orange "Snooze Tabs" icon.
- Two notifications are displayed when the tabs appear.

[Actual result]:
- The tabs are brought back and have favicons, but their notifications are not displayed.

[Notes]:
- Please see the Screen Cast attached:
![notif](https://cloud.githubusercontent.com/assets/26000308/23961112/99217a94-09b2-11e7-84bc-d89b1dacbe24.gif)

**Comment by wresuolc** [comment]
We fire notifications for each tab, but Windows may be consolidating them.  I don't think there is anything we can do here.
