### ISSUE TITLE
When a tab with a local file is snoozed, none of the previous or next scheduled tabs will be unsnoozed

### ISSUE THREAD

**Issue by SoftVision-EmilPasca** [bwinton/SnoozeTabs#266]
[Affected versions]:
- Firefox 52.0
- Snooze Tabs 1.0.15

[Affected Platforms]:
- All Windows
- All Mac OS
- All Linux

[Prerequisites]:
- Have a Firefox profile with the latest Snooze Tabs add-on (
https://378-15314951-gh.circle-artifacts.com/0/tmp/circle-artifacts.ipWadCV/snoozetabs-1.0.15.zip) loaded as a temporary add-on.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisite.
2. Load a local file in the browser.
3. Click on the "SnoozedTabs" button from the Toolbar.
4. Choose the fastest snoozing options for quicker results (eg: "Pick a Date/Time") 
5. Wait for the tab to be unsnoozed.

[Expected result]:
- Tab reappears unfocused in a new tab after the snooze period has elapsed.

[Actual result]:
- The tab is not unsnoozed after the chosen period.

[Notes]:
- On Mac OS, the icon for a snoozed local file is not displayed in the "Manage Snooze tabs" panel.

**Comment by wresuolc** [comment]
Does the console show any errors?

**Comment by SoftVision-EmilPasca** [comment]
Hi @wresuolc, I've re-tested this issue and observed that everytime you snooze a new tab, the tabs which were scheduled to be unsnoozed after snoozing a local file are re-opened but not deleted from the "Manage Snoozed Tabs" panel. 

The browser console didn't show any errors, however I've attached the log [here.](https://github.com/bwinton/SnoozeTabs/files/861773/browser_console_snoozetabs.txt)


[Notes]:
- The tabs are also re-opened after restarting the browser.
- I've also attached a [screen recording of the issue.](https://drive.google.com/open?id=0B_8KoHFRS-VCWjBoNm5XQ29PUTQ)

**Comment by bwinton** [comment]
We weren't actually logging these errors (which I fixed in my previous PR), but they were erroring.

The error is:
```
SnoozeTabs (BE) handleWake update rejected Error: Illegal URL: file:///C:/Users/bwinton/Programming/StyleGuide/index.html
Stack trace:
Async*handleWake/</</<@moz-extension://b9afe189-c338-4f84-94f1-6d91f55cc0f5/background.js:5203:16
handleWake/</<@moz-extension://b9afe189-c338-4f84-94f1-6d91f55cc0f5/background.js:5193:26
promise callback*handleWake/<@moz-extension://b9afe189-c338-4f84-94f1-6d91f55cc0f5/background.js:5181:12
promise callback*handleWake@moz-extension://b9afe189-c338-4f84-94f1-6d91f55cc0f5/background.js:5176:10
```
and I will see what we can do about that.  (Probably not letting people snooze file urls…)

**Comment by bwinton** [comment]
(I've got a PR, but it kinda depends on #292, so I'm going to wait until that lands before I push it.

**Comment by SoftVision-EmilPasca** [comment]
The issue is no longer reproducible on the latest Snooze Tabs version (1.0.16 built on 04/03/2017).

**Comment by xuiqzy** [comment]
I was searching through the issues as I wanted to snooze a local file tab, I don't really understand the info in this issue (e.g. https://github.com/bwinton/SnoozeTabs/issues/266#issuecomment-290754577 ), is it (still) not possible to snooze local files technically or what is the issue preventing it?

**Comment by bwinton** [comment]
If I remember correctly, for security reasons extensions aren't allowed to run on file:// urls, so there's no way to snooze them, or restore them.
