### ISSUE TITLE
Two "Mozilla" logos are displayed in the SnoozedTabs notification on Mac OS

### ISSUE THREAD

**Issue by SoftVision-EmilPasca** [bwinton/SnoozeTabs#267]
[Notes]:
- On Windows only one logo is displayed in the "SnoozedTabs" notification.
- Based on the following design: https://mozilla.invisionapp.com/share/MV9F846SY#/screens two images should be displayed in the notification (one with the "Mozilla" logo the other with the site favicon).

[Affected versions]:
- Firefox 52.0
- Snooze Tabs 1.0.15

[Prerequisites]:
- Have a Firefox profile with the latest Snooze Tabs add-on (
https://378-15314951-gh.circle-artifacts.com/0/tmp/circle-artifacts.ipWadCV/snoozetabs-1.0.15.zip) loaded as a temporary add-on.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisite and navigate to any website.
2. Click on the "SnoozedTabs" button from the Toolbar.
3. Select any snoozing option e.g. "Later Today".
4. Wait until the "SnoozedTabs" notification is displayed and observe the notification elements.

[Expected result]:
- Only one "Mozilla" logo is displayed in the notification.

[Actual result]:
- Two "Mozilla" logos are displayed in the notification.
![windowsmacos_notification](https://cloud.githubusercontent.com/assets/20083658/23962646/75bf3276-09b7-11e7-9e82-fa4076d5b7e2.png)

**Comment by bwinton** [comment]
We have no control over what platform notifications look like.  Closing as impossible.  :wink:
