### ISSUE TITLE
The Confirmation notification is not displayed if Page Style is set to "No Style"

### ISSUE THREAD

**Issue by SoftVision-CarmenFat** [bwinton/SnoozeTabs#269]
[Affected versions]:
- Nightly 55.0a1
- Snooze Tabs 1.0.15 (built on 16/03/2017)

[Affected Platforms]:
- All Windows
- All MAC OS
- All Linux

[Prerequisites]:
- Have a Firefox profile with the latest Snooze Tabs add-on version (1.0.15 -dev, built on 16/03/2017) loaded as a temporary add-on.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites and navigate to any website (e.g. www.wikipedia.org).
2. Go to Menu Bar and click on View.
3. From "Page Style", click on "No Style" option.
4. Click on the Snooze Tabs button and choose one of the options (e.g. "Real Soon Now!").

[Expected result]:
- The Confirmation notification is displayed on the top of the page content.

[Actual result]:
- The Confirmation notification is not displayed.

[Notes]:
- If the "Ask for confirmation when snoozing tabs" checkbox is unchecked, the website is displayed on the Manage Snoozed Tabs panel and it gets unsnoozed at the time the user had set it. 
- Please see the Screen Cast attached:
![conf](https://cloud.githubusercontent.com/assets/26000308/24004899/3aba98c8-0a70-11e7-9cbf-a909b468a68a.gif)

**Comment by bwinton** [comment]
Ya know, I'm more than half tempted to file a bug to remove that option from Firefox.  😉
I would say "WONTFIX", but I'll wait for someone else to comment before closing this issue.

**Comment by wresuolc** [comment]
Agreed.
