### ISSUE TITLE
A new empty tab is wrongly opened if only one tab is opened and you change a snoozed tab's date/hour

### ISSUE THREAD

**Issue by SoftVision-CarmenFat** [bwinton/SnoozeTabs#272]
[Affected versions]:
- Nightly 55.0a1
- Snooze Tabs 1.0.15

[Affected Platforms]:
- All Windows
- All MAC OS
- All Linux

[Prerequisites]:
- Have a Firefox profile with the latest Snooze Tabs add-on version (1.0.15 -dev, built on 17/03/2017) loaded as a temporary add-on.
- Have a snoozed website and an opened tab on the same profile.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisite.
2. Click on the Snooze Tabs button and then on Manage Snoozed Tabs.
4. Click on the date and time.
5. Modify the date/time and click on "Snooze!" button.
6. Observe what happens next.

[Expected result]:
- Manage Snoozed Tabs panel is displayed.

[Actual result]:
- Manage Snoozed Tabs panel is displayed and a new empty tab is opened.

[Notes]:
- Please see the Screen cast attached:
![newt](https://cloud.githubusercontent.com/assets/26000308/24048969/3a2333d4-0b33-11e7-80a1-a89aafa3530b.gif)

**Comment by SoftVision-CarmenFat** [comment]
This behavior is reproducible also by clicking on the "Undo" button: the new empty tab appears only if there is one tab opened in the Tab bar.
Please see the following Screencast:

![tab](https://cloud.githubusercontent.com/assets/26000308/24359058/de476f40-130b-11e7-895c-36909a1bdc4d.gif)

**Comment by SoftVision-EmilPasca** [comment]
The issue is reproducible following the scenario when clicking on the "Undo" button, on the latest Snooze Tabs version (1.0.16 - downloaded from https://424-15314951-gh.circle-artifacts.com/0/tmp/circle-artifacts.iTa9l78/snoozetabs-1.0.16.zip).

**Comment by SoftVision-CarmenFat** [comment]
The issue is no longer reproducible on the latest Snooze Tabs version (1.0.17 built on 04/13/2017).
