### ISSUE TITLE
Bookmark management doesn't play well with Sync

### ISSUE THREAD

**Issue by mhammond** [bwinton/SnoozeTabs#273]
While going through my personal sync logs, I noticed some strangeness which I think I've narrowed down to https://github.com/bwinton/SnoozeTabs/blob/de20a9293e52eda6619c241a4256556c0d7975b0/src/background.js#L161. I see 2 main issues here:

* For a user with a Sync account and only 1 of the devices having this addon enabled, the fact that the menu is deleted and then repopulated every time is causing sync churn - sync notices the deletion of the "old" item and syncs the deletion. It then notices the creation of another identical bookmark (differing only by GUID) and syncs that. Other devices then do a little dance processing the deletion and the de-dupe logic does strange things.

* Worse, consider a Sync account where all devices have this addon enabled. Sync will keep this folder synced between multiple devices. This means that both devices will "battle" for ownership of that folder, with Sync doing its best to ensure all devices have the same copies. At any time, it seems that all devices will have the snoozed tabs from one arbitrary device, and which device that is appearing to change randomly.

cc @kitcambridge

**Comment by rnewman** [comment]
Things to consider:

- One snooze folder per device. Give each one a random ID. Now you can see your snoozed tabs on another device!
- Don't bulk-delete; do it properly. 
- Don't find the folder by title. That's just asking for trouble!
- Don't use bookmarks to store scratchpad data at all. If you don't want it synced, accessible to extensions like Xmarks, merged across devices, etc., then bookmarks is the wrong data store. 

I remember a similar issue seven years ago with Snowl. Good times!

**Comment by lmorchard** [comment]
> then bookmarks is the wrong data store

FWIW, bookmarks are *not* the data store for Snooze Tabs. The real store is [the WebExtension storage API](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/storage). We're only using the bookmark folder as a pre-emptive backup for the current set of snoozing tabs in case the add-on gets uninstalled, because we don't get an event to handle when WebExtensions are uninstalled.

**Comment by kitcambridge** [comment]
Thanks for clarifying, @lmorchard; that's very helpful! Another idea is to create the backup folder underneath the Places root (which Sync will ignore), and insert a "query" (a bookmark with a `place:` URL) into "Other Bookmarks" that points to the folder. That way, the folder will still show up  in the UI, but its contents won't be synced.

In the long run, I'm not sure if bookmarks are the right mechanism for backups like this. But, IIUC, the query might be a short-term way to work around Sync churn.

**Comment by lmorchard** [comment]
> Another idea is to create the backup folder underneath the Places root (which Sync will ignore), and insert a "query" (a bookmark with a place: URL) into "Other Bookmarks" that points to the folder.

This doesn't sound like something we can do with [the WebExtensions bookmark API](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/bookmarks) - which is all we have access to in SnoozeTabs.

**Comment by wresuolc** [comment]
These two things sound like things to investigate:

- One snooze folder per device. Give each one a random ID. Now you can see your snoozed tabs on another device!
- Don't bulk-delete; do it properly.

**Comment by pdehaan** [comment]
Instead of a random UUID, can we somehow get the device sync name (if any)?
https://blog.mozilla.org/services/2016/10/06/device-management-coming-to-your-firefox-account/

**Comment by rnewman** [comment]
> but is the backup folder worth that complexity?

I would say: for an experiment, probably not, so long as you don't forcibly remove the add-on before restoring snoozed tabs! (Perhaps the Test Pilot add-on itself can help somehow?)

If we decide to make this a product feature, then we would do persistence/backup differently. In the short term using bookmarks is an expensive way to cause Sync-related bugs 😁

**Comment by mhammond** [comment]
> Instead of a random UUID, can we somehow get the device sync name (if any)?

That's stored in a pref, but I'm not sure how you'd handle it being changed - at this stage the rename must only be done on the device itself, but in the future we intend allowing devices to be renamed externally via FxA device management on the web. I guess you'd also need to handle sync being configured (or disconnected) after the addon was installed.

**Comment by rnewman** [comment]
Also names aren't unique, so you'd want both some kind of random identifier (which doesn't strictly have to be sourced from Sync — indeed, you want it to change if a profile is copied, or again clients will fight!) and a name for the folder.

Doing this at all safely starts getting real hairy real fast.

**Comment by bwinton** [comment]
I'm about 80% sure we can't get any sort of device sync name from the WebExtensions APIs, but if one of you want to take a look at https://developer.mozilla.org/en-US/Add-ons/WebExtensions and see if there's anything there that would be better to use, that would be extremely helpful!  Thanks!

(One of the things I was looking at earlier was [bookmarks.getTree](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/bookmarks/getTree), which looked like it might return the Places root, instead of just the bookmarks root, and so maybe wouldn't get synced?  I could whip up a simple WebExtension that implemented that, if one of you was able to test it to see…)

**Comment by mhammond** [comment]
> I'm about 80% sure we can't get any sort of device sync name from the WebExtensions APIs,

The device name is stored in prefs, but it looks like there's not even read-only access to them. A complication in this route would be handling when a user with the extension signs in to (or signs out of) sync.

> One of the things I was looking at earlier was bookmarks.getTree, which looked like it might return the Places root,

Any such non-synced roots would also not be available in the UI, which would be an issue for it being a "pre-emptive backup". Kit mentioned above that this approach probably also needs a "query" to be created, which IIUC also isn't exposed via web extensions.

**Comment by kitcambridge** [comment]
I think, if we supported creating queries using Places GUIDs (`place:folder=${bookmarkTreeNode.id}`), you'd be able to insert a bookmark with that URL and it would "just work." But that would still be Firefox-specific, and I'm not sure it's the right approach considering the other comments in this thread.

**Comment by rnewman** [comment]
FYSA, I filed [Bug 1351897](https://bugzilla.mozilla.org/show_bug.cgi?id=1351897) to address the major shortcomings of `browser.bookmarks`.

**Comment by bwinton** [comment]
\o/
