### ISSUE TITLE
Most of the options from the panel and context menu start with lowercase letters on HU build

### ISSUE THREAD

**Issue by SoftVision-CarmenFat** [bwinton/SnoozeTabs#274]
[Affected versions]:
- Firefox 55.0a1
- Snooze Tabs 1.0.15

[Affected Platforms]:
- All Windows
- All MAC OS
- All Linux

[Prerequisites]:
- Have a Firefox profile with the latest Snooze Tabs add-on version (1.0.15 -dev, built on 20/03/2017) loaded as a temporary add-on.
- Have the Hungarian [hu] Firefox locale build installed.

[Steps to reproduce]:
1. Open the localized Firefox build with the profile from prerequisite.
2. Navigate to any website.
3. Click on the Snooze Tabs button and observe the options translations.

[Expected result]:
- Options panel is displayed and all options are visible starting with capital letters.

[Actual result]:
- Options panel is displayed but most of the options start with lowercase letters (except "Real soon now!" and "Pick a date/time").

[Notes]:
- Same issue affects the Context menu's options.
- Please see the Screenshot attached:
![lowercase](https://cloud.githubusercontent.com/assets/26000308/24108705/0c75cb52-0d97-11e7-8be2-38b9a55b3812.jpg)

**Comment by lmorchard** [comment]
Looks like that's [how these strings were localized in Pontoon](https://github.com/bwinton/SnoozeTabs/blob/master/locales/hu/snoozetabs.properties#L33):

```
# "Real Soon Now!" is in 5 seconds (for testing).
timeRealSoonNow=Egészen hamarosan!
timeLaterToday=ma egy későbbi időpontig
timeTomorrow=holnapig
timeThisWeekend=a hétvégéig
timeNextWeek=a következő hétig
timeNextMonth=a következő hónapig
# This means the next time Firefox opens.
timeNextOpen=a következő megnyitásig
timePickADate=Válasszon dátumot/időt
```

Not sure if we have a process to request changes from localizers?

**Comment by wresuolc** [comment]
@flodolo is this on purpose in HU or something we should change?

**Comment by flodolo** [comment]
@meskobalazs
Is this wanted?

**Comment by meskobalazs** [comment]
This is a bug, I'll fix it right away.

**Comment by lmorchard** [comment]
Looks done to me too! Closing

**Comment by SoftVision-CarmenFat** [comment]
Hello @lmorchard,

I have tested the Hungarian localization build again with Snooze Tabs v.1.0.17 (https://557-15314951-gh.circle-artifacts.com/0/tmp/circle-artifacts.qwCtnIN/snoozetabs-1.0.17.zip). Unfortunately, the issue still seems to reproduce, as you can see in the following screenshot:

![hu](https://cloud.githubusercontent.com/assets/26000308/25233624/20d46644-25e8-11e7-9e24-7f013bffa378.jpg)

**Comment by meskobalazs** [comment]
I am not sure what was the problem. Updated the file in Pontoon again, and removed the old translations.

**Comment by lmorchard** [comment]
https://github.com/bwinton/SnoozeTabs/commit/1ae4cad890df0e26959fd92edeb75c29f6369e04

**Comment by SoftVision-CarmenFat** [comment]
The issue is no longer reproducible on the latest Snooze Tabs version (1.0.18 - built on 04/21/2017).
Options from both Snooze Tabs panel and context menu start with uppercase letters.
