### ISSUE TITLE
Several areas are not localized in Asturian [ast]

### ISSUE THREAD

**Issue by SoftVision-EmilPasca** [bwinton/SnoozeTabs#275]
[Affected versions]:
- Nightly 55.0a1
- Snooze Tabs 1.0.15 (built on 03/20/2017)

[Affected Platforms]:
- All Windows
- All Mac OS
- All Linux

[Prerequisites]:
- Have a Firefox profile with the latest Snooze Tabs add-on version (1.0.15 -dev, built on 03/20/2017) loaded as a temporary add-on.
- Have the Asturian [ast] Firefox locale build installed.

The following areas are displayed in English and should be displayed in Asturian [ast]:
- All the strings in the "Manage SnoozedTabs" panel.
- The "Real Soon Now!", "Next Open" and "Pick a Date/Time" snoozing options.
- "This tab will snooze until" string in the notification bar.
- The "Snooze!" button in the "Pick a Date/Time" panel.
- The "SnoozeTabs" context-menu "Real Soon", "Next Open" options..
- The "SnoozeTabs" tooltip from the "SnoozeTabs" button in the browser toolbar. 

[Notes]:
- Attached a screen shot of the affected areas:
![issue_collage](https://cloud.githubusercontent.com/assets/20083658/24110992/b3405ffa-0d9d-11e7-9988-0a07df17c59d.png)

**Comment by lmorchard** [comment]
Looks like [this locale is only 45% translated in Pontoon as of right now](https://pontoon.mozilla.org/ast/test-pilot-snoozetabs/).

Might be worth considering whether we want to merge in partially completed locales (like I've done) or whether we only want to wait for 100%. I could revert this locale and only re-merge from the l10n branch when it's 100%.

**Comment by lmorchard** [comment]
FWIW, it looks like there's an API we can use to query 100% locales:

https://l10n.mozilla-community.org/webstatus/api/?product=testpilot-snoozetabs&txt&type=complete

Maybe we could tweak the [pontoon-to-webext](https://github.com/bwinton/pontoon-to-webext) tool to selectively process only a list of locales (i.e. the 100% ones from that API) and ignore the rest. That way, we could merge partial work, but only ship complete locales.

**Comment by SoftVision-EmilPasca** [comment]
@lmorchard On ”es-MX”, the “Pick a Date/Time” string is not correctly translated: “fecha” should have a capital letter and “Time” is still in english.
Should I log a separate issue for this?
![issue_es-mx](https://cloud.githubusercontent.com/assets/20083658/25237051/44c62f06-25f2-11e7-9f43-d63cdc43d986.jpg)

**Comment by lmorchard** [comment]
Yeah, separate issue - this one's about the missing ast locale. [Also looks like this is how the es-MX localizer chose to translate this string](https://pontoon.mozilla.org/es-MX/test-pilot-snoozetabs/snoozetabs.properties/?string=162270). @flodolo - is there a process for forwarding these kinds of issues on to localizers?

**Comment by flodolo** [comment]
One possible way is to CC the localizers, since Pontoon commits with attribution.
https://github.com/bwinton/SnoozeTabs/commits/l10n/locales/es-MX

@robertoalvarado
Thoughts on this issue?
