### ISSUE TITLE
Install vendor moment.js files via npm versus including in repo?

### ISSUE THREAD

**Issue by pdehaan** [bwinton/SnoozeTabs#29]
Other random thought... Currently we bundle the 249K "./lib/moment.js" into the repo.

It looks like if we do an "npm i moment -D" and then inspect the "./node_modules/moment/min/" directory we have a few options:

| SIZE | NAME | &nbsp;
|----:|----|----|
| 296K | locales.js
| 189K | locales.min.js
| 416K | moment-with-locales.js
| 249K | moment-with-locales.min.js | What we seem to currently be using.
| 60K | moment.min.js | If we don't care about l10n _yet_ and want to save ~190k bundle size.

We'd just need some crude build script that copies the appropriate minified files from ./node_modules/moment into ./lib.

**Comment by lmorchard** [comment]
Looks like this will be covered in #30 and the build process I rolled into that PR
