### ISSUE TITLE
Snoozed until "Next Open" tabs are unsnoozed after Disabling and Enabling the SnoozedTabs addon

### ISSUE THREAD

**Issue by SoftVision-EmilPasca** [bwinton/SnoozeTabs#298]
[Affected versions]:
- Firefox 52.0 and up
- Snooze Tabs 1.0.16

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Have a Firefox profile with the latest Snooze Tabs add-on version (1.0.16 -https://427-15314951-gh.circle-artifacts.com/0/tmp/circle-artifacts.Wjnytth/snoozetabs-1.0.16.zip).

[Steps to reproduce]:
1. Open the browser with the profile from prerequisite and navigate to any website.
2. Click on the "SnoozedTabs" button in the browser toolbar.
3. Click on the "Next Open" button and "OK" in the SnoozedTabs notification.
4. Navigate to "about:addons" page to the "Extensions" tab.
5. Disable the SnoozedTabs addon.
6. Re-enable the SnoozedTabs addon and observe the browser behavior.

[Expected result]:
- The tab which was snoozed until "Next Open" remains unsnoozed until browser restart.

[Actual result]:
- The tab which was snoozed until "Next Open" is wrongly unsnoozed.

[Notes]:
- Attached a screen recording of the issue:
![snoozetabs_disableenable_issue](https://cloud.githubusercontent.com/assets/20083658/24764144/1dbf7e36-1afc-11e7-9322-1a26c741151f.gif)

**Comment by lmorchard** [comment]
Going to call this a wontfix - kind of an edge case, but also actually useful for development.
