### ISSUE TITLE
Snooze Tabs panel becomes unresponsive after clicking the "Pick a Date/Time" option's arrow

### ISSUE THREAD

**Issue by SoftVision-CarmenFat** [bwinton/SnoozeTabs#304]
[Affected versions]:
- Nightly 55.0a1
- Snooze Tabs 1.0.17

[Affected Platforms]:
- All Windows
- All MAC OS
- All Linux

[Prerequisites]:
- Have a Firefox profile with the latest Snooze Tabs add-on version (1.0.17 -dev, built on 12/04/2017) loaded as a temporary add-on.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisite and navigate to any website.
2. Click on the "SnoozedTabs" button in the browser toolbar.
3. Click on the "Pick a Date/Time" arrow.

[Expected result]:
- "Pick a Date/Time" panel slides over.

[Actual result]:
- The "Options" panel is greyed out and unresponsive. 

[Notes]:
- The panel returns to normal if the user clicks outside the panel and goes back again to the Snooze Tabs button.
- This is also reproducible after moving the "Snooze Tabs" button in the Hamburger Menu.
- This is not reproducible with the Test Pilot version.
- Please see below the screen recording of the issue:

![snz](https://cloud.githubusercontent.com/assets/26000308/24962282/2ed7c348-1fa4-11e7-906f-9d2f3648fdd3.gif)

**Comment by lmorchard** [comment]
Hmm, I can't reproduce this. Is it still happening on latest master? Would you happen to have the git commit ID from when this happened?

**Comment by SoftVision-CarmenFat** [comment]
The issue is no longer reproducible on the latest Snooze Tabs version (1.0.18 - built on 04/21/2017).
