### ISSUE TITLE
Localization of DateTime picker strings

### ISSUE THREAD

**Issue by flodolo** [bwinton/SnoozeTabs#305]
A few minutes ago a lot of strings (29) landed and were exposed in Pontoon. I say a lot, given that the add-on so far consists of 34 strings.

I have asked @lmorchard to revert that change, because there are a few issues that I would like to discuss before exposing them for localization.
https://github.com/bwinton/SnoozeTabs/commit/76dfaca05285b646fab0ba9ef5c301aa4cb82a8a

My understanding from the IRC discussion is that they're used to localize this component
https://github.com/react-component/calendar/tree/master/src/locale

The first problem is that we shouldn't ask localizers to provide datetime formats. We have Intl APIs in Firefox, we should try to leverage that as much as possible.

There's also a datetime picker in Firefox, not sure in which versions is available and if it's a suitable alternative.

If we end up having to expose these strings, we need much better localization comments to explain what's going on. I also expect to be broken all over the place, with localizers picking wrong values because they don't understand what they're asked to do (I've worked on Firefox OS, I know that will happen).

CC @zbraniecki since he's doing all the work on Intl in Gecko.

**Comment by zbraniecki** [comment]
my primary concern here is that we should not ask localizers to provide date/time format patterns unless it's absolutely necessary. We have ECMA402 Intl  API in Firefox which formats dates and times.

Unless there's a very, very specific use-case that I don't understand yet, I believe we should just use Intl API from  JavaScript.

**Comment by lmorchard** [comment]
> The first problem is that we shouldn't ask localizers to provide datetime formats. We have Intl APIs in Firefox, we should try to leverage that as much as possible.

> my primary concern here is that we should not ask localizers to provide date/time format patterns unless it's absolutely necessary

I'll take a look at getting the component to use those APIs. 

> There's also a datetime picker in Firefox, not sure in which versions is available and if it's a suitable alternative.

I think we picked this component because a) it wasn't a suitable alternative and b) this component is localizable

> If we end up having to expose these strings, we need much better localization comments to explain what's going on.

Can you give examples on what kinds of comments are necessary? Except for the date formats, [most of these are just title labels for tooltips on buttons](https://github.com/bwinton/SnoozeTabs/blob/master/locales/en-US/snoozetabs.properties#L65-L95)

**Comment by flodolo** [comment]
> Can you give examples on what kinds of comments are necessary? Except for the date formats

It's mostly about the time formats. Note that some languages use different forms for tooltips and button labels (e.g. third person singular for a tooltip, imperative for a button), so it would be useful to clearly differentiate them (I don't think we can change the string IDs).

For the datetimepicker, I wonder if that wasn't available at all when the add-on started.

On unrelated notes: 'Ok' is not correct in English (should be 'OK'), and I wonder if CTRL+left/right actually works on all platforms.

**Comment by lmorchard** [comment]
> It's mostly about the time formats.

I'm going to try to remove those and replace their use with the Intl APIs.

> Note that some languages use different forms for tooltips and button labels (e.g. third person singular for a tooltip, imperative for a button), so it would be useful to clearly differentiate them (I don't think we can change the string IDs).

So... what does this mean for additional comments or string changes? What needs to change in the .properties file, practically speaking?

> I wonder if CTRL+left/right actually works on all platforms.

We have [another issue for keyboard navigation](https://github.com/bwinton/SnoozeTabs/issues/32), but that's kind of stalled in general as a feature. These are just strings from [what the component itself implements](https://github.com/react-component/calendar/blob/a380879f62c25f8e6dab704755dfbdc2dc2db458/src/Calendar.jsx). Looks like Ctrl or Meta key.

**Comment by flodolo** [comment]
> So... what does this mean for additional comments or string changes? What needs to change in the .properties file, practically speaking?

Need to figure how strings are used, and if it's worth adding a comment to the .properties file to make them clearer.

**Comment by flodolo** [comment]
From a quick look it doesn't look like we're using all of them (e.g. OK, now, today, back to today), and all I can find are used as tooltips.

**Comment by lmorchard** [comment]
I just submitted PR #306 with these main things for this issue:

* Found a way to use the Intl API without forking the rc-calendar component
* Removed some strings that we don't ever seem to display, thanks to how we're using the component
* Added comments before all the remaining new strings
* Upgraded the rc-calendar component, which now comes with more locales

Does this help things?

**Comment by flodolo** [comment]
> Does this help things?

Absolutely yes, thanks.

**Comment by lmorchard** [comment]
@flodolo Thanks for looking this over and helping me make this not entirely stupid 😁
