### ISSUE TITLE
Ensure build process works on Windows

### ISSUE THREAD

**Issue by lmorchard** [bwinton/SnoozeTabs#31]
In #30, I've introduced a new build process based on npm scripts. There are some issues in just running `npm start` on Windows. Need to circle back and make sure there's a good solution.

**Comment by bwinton** [comment]
We'll also need to expand out `{manifest.json,icons}` manually to `src/manifest.json src/icons`.

**Comment by SoftVision-PaulOiegas** [comment]
Maybe I do something wrong but I get errors also on linux when trying to create the build. 
1. Failed at the snoozetabs@1.0.0 copy:assets script 'cp -rv src/{manifest.json,icons} dist/ && mkdir -p dist/popup && cp -rv src/popup/*.html dist/popup/'.
2. Failed at the snoozetabs@1.0.0 build script 'npm run clean && npm-run-all --parallel copy:assets bundle:js bundle:css && npm run package'.

If I'm not wrong and you need any details or logs, let me know.

**Comment by lmorchard** [comment]
Looks like this was fixed in #38 modulo future improvements
