### ISSUE TITLE
Unable to set time

### ISSUE THREAD

**Issue by smigg221174** [bwinton/SnoozeTabs#311]
I have installed the SnoozeTabs preview, but I am unable to set any times against the options. Each option in the list has the ellipsis there, but clicking on this doesn't do anything. Also, clicking on the arrow next to the Custom Date/Time option does not do anything, and therefore I can't snooze any of my tabs.

[snoozetabs screen.docx](https://github.com/bwinton/SnoozeTabs/files/940862/snoozetabs.screen.docx)

**Comment by SoftVision-EmilPasca** [comment]
@smigg221174 Thank you for submitting this issue. 
Can you please give us more details about your system, such as what Firefox version you have installed, operating system and other addons you may have installed?

**Comment by smigg221174** [comment]
Hi,

thanks for the response. My system is Windows 7 SP1, with Firefox esr
45.8.0 installed. I have some other Firefox Test Pilot add-ons installed
(Page Shot, Min Vid and Activity Stream).

Thanks
Graeme

**Comment by SoftVision-EmilPasca** [comment]
@smigg221174 I'm sorry to say that Test Pilot no longer supports Firefox versions older than 49.0 for a few weeks now, same for some of the experiments(like Snoozetabs).
What I would recommend is to install the latest Firefox ESR(52.0) from [here](https://www.mozilla.org/en-US/firefox/organizations/all/) (installing over the older ESR, won't affect your current profile).
Please test this and let us know if it works for you.

Thank you.

**Comment by smigg221174** [comment]
Thanks for that. I'd be using the "check for updates" and thought I was up
to date. I've updated to ESR 52 and that has worked. Thanks for the fix!!

Thanks
Graeme
