### ISSUE TITLE
[Discussion/feedback] Which use cases for Snooze Tabs are actually useful?

### ISSUE THREAD

**Issue by smichel17** [bwinton/SnoozeTabs#318]
Started writing this in the feedback survey, but I wanted the opportunity for follow-up discussion.

I use [Tab Groups](https://addons.mozilla.org/en-US/firefox/addon/tab-groups-panorama/) to organize my tabs. However, I often find that I'm too lazy to change groups when I change to a new activity, and so I end up having to move tabs around later. A month ago, I installed Snooze Tabs hoping that it, plus the Containers experiment, would allow me to stop using Tab groups (especially since it'll stop working soon, when XUL is dropped).

I've used it maybe twice, when I forced myself to try it out. Turns out, Snooze Tabs doesn't really fit my use cases:

1. **Tab management:** cleaning things up to avoid tab overload
    - **Example:** I'm working on a project, and I have a bunch of tabs open for reference. I decide to take a break and do something else. I want to keep all the reference tabs around, but don't want them clogging up display while I'm doing other things.
    - **Why it doesn't work:** I might have 10+ tabs open for reference. Snoozing them all individually takes way too much time. Also, I don't know when I'm going to come back, so it doesn't make sense to pick a time.
    - **What would help:** Add a "Snooze all" button. Click it and get a text field. Type a name and hit enter. Snoozes all open tabs into one entry in the "Snoozed Tabs" list, with the name I gave.
2. **Reading lists:** things to read later. Essentially, one-time-use bookmarks.
    - **Example:** I'm reading a blog post. It links to another blog post, which links to another blog post, which links to... I want to break the cycle by assuring myself I won't forget about those links if I save them for later. At the same time, bookmarks are a bit clumsy for one-time use.
    - **Why it doesn't work:** Similar to tab managment above, I'd usually prefer to snooze indefinitely, and I'll pick it up again when I have time. I also often do this kind of reading on mobile.
    - **What would help:** Add an "Indefinitely" time period. Make Snooze Tabs available for firefox mobile.
3. **Task Management:** reminders to do something later
    - **Example:** I'm shopping (not time sensitive). I'm not done picking things out, and decide to come back to that later.
    - **Why it doesn't work:** This is essentially a thing in my todo list. I already have a todo list, and I don't want to spread it out between multiple applications. It's easier just to copy the link into my existing list.
    - **What would help:** Integration with todo lists. *I think this would be more appropriate for a todo list addon to implement itself, not something shipped in firefox proper.*

**Comment by albinhh** [comment]
although I don't speak for the "developing"-team I think the second and third function of this request go far beyond the core function of snooze tab, which is in my view:
"show this tab on a (specific) time in the future (and close it for now)"

the first function snooze multiple tabs was already requested, which I would find helpful as well.

@smichel17 
for "saving" multiple tabs I use "session manger": http://sessionmanager.mozdev.org/
essentially this is your "snooze function for an indefinite time period for multiple tabs" - you have to open it yourself when you need it

**Comment by lmorchard** [comment]
If you're looking for discussion, [the Snooze Tabs / Test Pilot forums](https://discourse.mozilla-community.org/c/test-pilot/snooze-tabs) would be a better venue.
