### ISSUE TITLE
Can't snoze any tab

### ISSUE THREAD

**Issue by Zawadx** [bwinton/SnoozeTabs#323]
Clicking on the bell icon opens up a menu, listing the different times available. But there are only '...' after the times (instead of a specific clock timing as seen in various screenshots), and clicking on the buttons doesn't do anything.

**Comment by lmorchard** [comment]
If you open a console with the menus Tools > Web Developer > Browser Console, do you see any errors? 

If you're just seeing the ellipses (...), that means Snooze Tabs failed to complete initialization of the options panel. Hopefully you might have an error that could tell us what happened and help fix it.

**Comment by Zawadx** [comment]
Turns out it was because my firefox wasn't updated (was at version 50.0.1). Updating fixed the problem ^^ Perhaps add a disclaimer on the page that it won't work unless you update (similar to how Pulse does it)
