### ISSUE TITLE
Pick a Date/Time missing on right click on tab

### ISSUE THREAD

**Issue by fauxcuss** [bwinton/SnoozeTabs#326]
If you click on the main SnoozeTabs icon on the toolbar, you get the option to "Pick a Date/Time".

This option is missing if you right click on a tab and choose SnoozeTab from the menu.

https://www.screencast.com/t/lkxUIhkZ4mj

**Comment by lmorchard** [comment]
I don't think we can offer the date/time selection panel from the context-menu - there's nowhere to display it. It can only be displayed in the panel summoned with the toolbar button.

**Comment by johngruen** [comment]
Closing due to impossibility
