### ISSUE TITLE
Problem with editing time on the Edit Date/Time panel

### ISSUE THREAD

**Issue by pcahan** [bwinton/SnoozeTabs#330]
When clicking on the icon and selecting manage snoozed tabs, you get a list of the snoozed tabs. If you then click on the date/time, the Edit Date/Time panel opens, showing the date on a calendar and the time below.

Clicking on a different date does edit the date.

Clicking on the time makes the field editable, but you do not get dropdowns to change it. You are allowed to edit it, but when you close your edit, the time reverts to the original time.

I did not find any way to access the type of time selected. (eg. Later today, Tomorrow, or Custom)

**Comment by SoftVision-EmilPasca** [comment]
@pcahan Thank you for submitting this issue.
Can you please give us more details about your system(OS) as well as Firefox version, TestPilot version, SnoozeTabs version and other add-ons you may have installed?

**Comment by lmorchard** [comment]
Hmm, I was unable to reproduce this. I was able to update the date and time separately from the management panel

**Comment by johngruen** [comment]
I can't repro either.
