### ISSUE TITLE
Snoozetabs panel is not displayed if the add-on is installed using the Windows Registry Editor

### ISSUE THREAD

**Issue by SoftVision-EmilPasca** [bwinton/SnoozeTabs#335]
[Notes]:
- A similar issue has been logged on Firefox Notes repository[ #156](https://github.com/mozilla/notes/issues/156) and Bugzilla [bug 1382180.](https://bugzilla.mozilla.org/show_bug.cgi?id=1382180)

[Affected versions]:
- Firefox 56.0a1
- Snoozetabs v1.0.18

[Affected Platforms]:
- All Windows

[Prerequisites]:
- Have the latest Snoozetabs add-on xpi (version 1.0.18) unpacked in a local folder.
- The pref "xpinstall.signatures.required" is set to "false".
- Have a string variable with the value name "snoozetabs@mozilla.com" and value data "C:\Users\username\Downloads\snoozetabs" (path to the add-on folder) under the "HKEY_LOCAL_MACHINE\SOFTWARE\Mozilla\Firefox\Extensions" registry folder. Details [here](https://developer.mozilla.org/en-US/Add-ons/Adding_extensions_using_the_Windows_registry).

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites.
2. Navigate to "about:addons" and click on the "Extensions" tab.
3. Enable "Snoozetabs".
4. Click on the "Snoozetabs" toolbar button.
5. Observe the "Snoozetabs" panel.

[Expected result]:
- The "Snoozetabs" panel is correctly displayed, showing the snoozing options and all the other UI elements.

[Actual result]:
- The "Snoozetabs" panel is displayed only for a fraction of a second and then it is closed. The options from the panel cannot be accessed.

[Additional Notes]:
- Attached the browser console messages:
[snoozetabs_browser_console_error_win_regedit.txt](https://github.com/bwinton/SnoozeTabs/files/1159477/snoozetabs_browser_console_error_win_regedit.txt)
- Attached a screen recording of the issue:
![snoozetabs_registry_issue](https://user-images.githubusercontent.com/20083658/28373185-6080930e-6caa-11e7-991c-d964cc2eed5f.gif)

**Comment by lmorchard** [comment]
SnoozeTabs should only be installed via the Test Pilot site. I don't think this is an expected or supported use case.

**Comment by johngruen** [comment]
Whelp
