### ISSUE TITLE
Clicking one of the snoozing options badly breaks website's UI

### ISSUE THREAD

**Issue by SoftVision-CarmenFat** [bwinton/SnoozeTabs#340]
[Notes]:
- This is a regression that is present in Nightly and Beta.
- Here is the regression range:
Last good revision: cee08328318a1ba8adcc1eff9c783fbecfed3540
First bad revision: 659451f14dddb66b1bf2c27fc19b704a3fd4e64a
- Pushlog:
https://hg.mozilla.org/integration/autoland/pushloghtml?fromchange=cee08328318a1ba8adcc1eff9c783fbecfed3540&tochange=659451f14dddb66b1bf2c27fc19b704a3fd4e64a

[Affected versions]:
- Beta 55.0b11
- Nightly 56.0a1

[Affected Platforms]:
- All Windows
- All Linux
- All Mac

[Prerequisites]:
- Have latest Snooze Tabs v. 1.0.18 experiment installed.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites and navigate to www.youtube.com
2. Click on the Snooze Tabs button from toolbar.
3. Click on one of the snoozing options and observe the effect on the website's UI.

[Expected result]:
- Website's UI elements remain unchanged.

[Actual result]:
- Website's UI breaks.

[Additional notes]:
- This seems to affect most of the tested websites (Google, Reddit, Yahoo, Facebook, Wikipedia etc)
- Added a screen recording with the issue:

![snooze break](https://user-images.githubusercontent.com/26000308/28578994-fe376b78-7163-11e7-8664-34422b3000d7.gif)

**Comment by SoftVision-EmilPasca** [comment]
Reopening this since is still reproducible on latest Firefox Release(57.0.1) and latest Nightly (59.0a1-20171207100053) with Snoozetabs (version 1.0.20).

**Comment by johngruen** [comment]
Here's Github looking janky
![screen shot 2018-01-10 at 8 45 17 pm](https://user-images.githubusercontent.com/3323249/34792109-4cc7f0c4-f647-11e7-96a5-6c9243ef62a3.png)

**Comment by SoftVision-EmilPasca** [comment]
This issue is no longer reproducible, I have tested this on Mac 10.12, Windows 10 x64 and Ubuntu 14.04 x64 with the latest Firefox Release (57.0.4) and latest Nightly (59.0a1-20180118012136) using the latest Snoozetabs (1.0.21 - downloaded from https://circleci.com/gh/bwinton/SnoozeTabs/651#artifacts/containers/0)
