### ISSUE TITLE
manage snoozed tab should show the actual time set.

### ISSUE THREAD

**Issue by MadhuriQA** [bwinton/SnoozeTabs#341]
While using “snooze tabs”, I noticed that if I set time to snooze a tab as 1:09 pm ,

Actual Result - it shows @1pm in “manage snoozed tabs” options.

Expected result - it should show the actual time set as @1:09 pm.

**Comment by SoftVision-PaulOiegas** [comment]
@MadhuriQA Hey, it seems that this was intended but I haven't found any clear reasons behind it. But it seems that even if you have a set hour like 1:50PM it still shows 1PM, which I personally consider not to be ok.
I support the idea that we should display also the minutes on the snoozed tabs timestamp.

**Comment by SoftVision-PaulOiegas** [comment]
I think that If you choose to edit one of the occurrences, the pick a date and time view will show you the exact set time. A quick workaround. But yeah, as I said, we should display HH:MM.

**Comment by MadhuriQA** [comment]
thanks @SoftVision-PaulOiegas  and yes you are correct on editing the occurrences thing but we need to move the track of issue reported :-)

**Comment by johngruen** [comment]
Seems reasonable
