### ISSUE TITLE
Ubuntu 17.04

### ISSUE THREAD

**Issue by DioGreene** [bwinton/SnoozeTabs#347]
When using this feature withing Ubuntu 17.04 "Zesty Zapus", the feature will only open to the "no upcoming snoozes" page and won't let me actually snooze a page.

**Comment by lmorchard** [comment]
On what URL are you trying to open the snooze tabs panel? [We have some code that restricts snoozes to certain URL protocols](https://github.com/bwinton/SnoozeTabs/blob/master/src/popup/snooze-content.js#L89) that could cause this - wondering if your URL fails that test, correctly or incorrectly.
