### ISSUE TITLE
Snooze time options available for Private mode windows and later vanishes off

### ISSUE THREAD

**Issue by Radhraj** [bwinton/SnoozeTabs#353]
Steps to reproduce:

1. Open the browser where the snooze plugin is enabled.
2. Snooze any website you need.
3. Open another window in Private mode and click on Snooze.

Expected result:

- Private Windows must not have the options for snooze.There can be options only to view all the websites snoozed.

Actual result:

- Private window shows the snooze options for few seconds and later vanishes off.

Attached Screenshot:

![snoozoptionsavailableforprivatemode](https://user-images.githubusercontent.com/30893077/29210882-6299ebf2-7eb3-11e7-8ad5-d05ad04ad449.gif)

**Comment by SoftVision-EmilPasca** [comment]
@Radhraj Thank you for submitting this issue.
Can you please give us more details about your system, such as what Firefox version you have installed, operating system and other addons you may have installed?

**Comment by Radhraj** [comment]
@SoftVision-EmilPasca 
Hello!
Here are the details you have asked for:
Firefox version-55.0.1
OS-Windows 7 64 Bit
Other Addons added-Notes,Voice Fill

**Comment by lmorchard** [comment]
I think this is resolved by #392. 

Looking at the animation, the options that appear are temporary content we displayed while the panel JS loaded. The vanishing is the panel finally starting up, which is the point where it could detect Private Browsing Mode and adjust accordingly. In #392, we dropped the loader, so hopefully this doesn't happen in the future
