### ISSUE TITLE
No higher limit set for snooze time.Any Year can be set.

### ISSUE THREAD

**Issue by Radhraj** [bwinton/SnoozeTabs#354]
Steps to reproduce:
1.	Open the browser with snooze plugin enabled.
2.	Select any website and try snoozing it to the year which is way ahead in future ex:2190 
3.	Click on OK
Expected result:

- The future time snoozing any website must have a upper limit and must throw error if it exceeds that.
Actual result:

- No such error message displayed.

Attached Screenshot:

![nolimitsetforfuturedate](https://user-images.githubusercontent.com/30893077/29211367-4d7a9890-7eb6-11e7-93a8-2883c52d9419.gif)

**Comment by fishzle** [comment]
I don't consider this a defect. I've already been considering using snooze as a form of bookmarks ordering.

**Comment by johngruen** [comment]
We're optimistic :)
