### ISSUE TITLE
Next Open works only when there is a single instance of the browser opened

### ISSUE THREAD

**Issue by Radhraj** [bwinton/SnoozeTabs#357]
Steps to reproduce:
1.	Open the browser with snooze plugin enabled.
2.     Select Next Open for any desired website.
3.     Open a new Firefox window.
4.     Close all the existing windows and open only 
single instance of the browser after sometime.

Expected result:

- Next Open must work for any new window of Firefox browser.

Actual result:

- This works only if all the instances are closed and a single instance of browser is opened.

Attached Screenshot:
![nexttimeworksonlyforsingleinstance](https://user-images.githubusercontent.com/30893077/29214435-dd9ebd90-7e96-11e7-8799-0bf92e398d4a.gif)

**Comment by lmorchard** [comment]
Next open of the Firefox application after having been exited is the intended result for this feature, not the next open of any window
