### ISSUE TITLE
Move to new page menu

### ISSUE THREAD

**Issue by passcod** [bwinton/SnoozeTabs#361]
Given this is a page-related tool, it should probably be moved to the newish? Page Action menu instead of the main toolbar.

**Comment by MikkCZ** [comment]
+1 for me. Some of the views like the list of the snoozed tabs should stay under the toolbar button, but the snoozing would definitely fit into the page actions menu.

**Comment by lmorchard** [comment]
@johngruen / @sevaan - Might need to do some UX thinking about this... Some options:

1. *Move* the options *out* of the toolbar popup altogether? (i.e. so that the toolbar popup is *just* snooze management like on an about:* page)
1. Duplicate the toolbar popup options? (i.e. the options are available in two places)
1. Build a simple list of text options similar to the tab right-click context menu?

**Comment by sevaan** [comment]
[Initial UX thinking](https://mozilla.invisionapp.com/share/SUFN0I05MG4#/276880941_Page_Action_Menu) for Page Action menu integration.

**Comment by MikkCZ** [comment]
I like that visual proposal. Maybe you can use the HTML5 time and date form inputs, so you do not have to care about their localization yourself.

**Comment by johngruen** [comment]
@sevaan looks good...one comment: you can't overflow the main panel in a doorhanger, so we'd have to reconsider the date picker.

**Comment by passcod** [comment]
I don't think it can be underflowed, either, right? It's always the same size as its initial invocation. Can the calendar fit inline in the proposal's first example's space?

**Comment by sevaan** [comment]
I wrote "some kind of calendar control" figuring maybe there was a library we could use. If not, an alternate solution could just be to switch to a drop-down menu system for the date.

**Comment by lmorchard** [comment]
Another wrinkle: I don't think a WebExtension can add anything to the Library in Firefox. Could be handy if Snooze Tabs gets rebuilt as an in-product feature, though

**Comment by jacktose** [comment]
It would be great to have the option to put it in any/all of:

- page action menu
- toolbar/overflow menu
- tab context menu
- page context menu

With as-similar-as-possible UX in each.

I don't know how much of that can/should be configured in the extension options vs the customize function.

**Comment by bwinton** [comment]
So, I knew if I waited long enough that page actions would go away entirely! 😉
Seriously, though, I think this isn't possible in the latest Firefox, so I'm gonna close out the issue.
