### ISSUE TITLE
Snooze Tab - Great idea if I could get it to work, but I can't

### ISSUE THREAD

**Issue by LionDan** [bwinton/SnoozeTabs#367]
Trying ST for the first time and can't set a snooze:
1. Running Firefox 56.0.1 x64 on Win 7 Pro ASUS laptop.
2. Page at https://testpilot.firefox.com/experiments/snooze-tabs says Snooze Tabs is enabled.
3. Click bell icon and get pull down menu, but that's as far as it goes:
4. Click any menu button (I tried manage, later today & pick) and get NO response to click.
5. Click outside the menu  to close it and nothing has (visibly at least) changed.

**Comment by SoftVision-EmilPasca** [comment]
Hi @LionDan, thanks for reporting this.
Can you please list the add-ons you have installed on your profile? Or you might like to add the information from `about:support` page, so that we can investigate this issue further.

**Comment by LionDan** [comment]
Because I had forgotten this post when I created #422, I'm abandoning this one and continuing there, where I've added the about:support data which I thought I'd posted here, but apparently didn't.

**Comment by BHMOO028** [comment]
hello world
