### ISSUE TITLE
Add recurring URL

### ISSUE THREAD

**Issue by jbvsmo** [bwinton/SnoozeTabs#373]
This is a feature request:

Please add an option to reopen multiple times until canceled. Examples:
Open a tab every day/weekday or once a week on mondays or every 13th of each month.

I used this feature before with http://www.tabsnooze.com/ on Chrome and it is very handy

**Comment by johngruen** [comment]
Like this idea, closing bug as duplicate

**Comment by bit-man** [comment]
Sorry, can't find bug that this one duplicates
