### ISSUE TITLE
Consider moving confirmation into the panel

### ISSUE THREAD

**Issue by johngruen** [bwinton/SnoozeTabs#383]
B/C the injected content is fragile, we should maybe just do the confirmation dialog in the panel. @sevaan wanna to a mock for this?

**Comment by lmorchard** [comment]
We've historically had constant issues with this - currently #380 & #371 & #340 in the ESR milestone are about styles for the in-content confirmation bar breaking either the bar or the site itself.

**Comment by bwinton** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1429914 :)

**Comment by lmorchard** [comment]
Hmm, I thought `<notificationbox>` was going away with Photon. If it's still there, I might try making a WebExtension Experiment API with it

**Comment by lmorchard** [comment]
Another idea I can't remember if we tried - an `<iframe>`

Been using the bitwarden password manager, and it has a similar in-content notification bar. I can't say I've ever seen it break site content or get broken by content.

The code's on github for reference https://github.com/bitwarden/browser/blob/master/src/content/notificationBar.js

**Comment by sevaan** [comment]
The [Page Action integration work](https://mozilla.invisionapp.com/share/SUFN0I05MG4#/screens/276880941_Page_Action_Menu) shows how an in-panel confirmation could work.
