### ISSUE TITLE
Re-snooze a waking tab

### ISSUE THREAD

**Issue by lmorchard** [bwinton/SnoozeTabs#40]
When the user gets the notification of a waking tab, they should easily be able to push it off again.

Not sure about the UX for this, since Firefox doesn't support additional buttons in notifications yet.

**Comment by sevaan** [comment]
We thought about this, and using system notifications to delay the snooze (the way you can delay a system update through a notification), but since we are popping the tab anyway, the user can just resnooze through the panel.

Might be a roadmap item if users want it.

**Comment by lmorchard** [comment]
> the user can just resnooze through the panel.

But, we can't actually offer additional buttons & etc on the notification. Firefox doesn't support that feature, yet. You just get to click the notification in general.

**Comment by sevaan** [comment]
Yes they can just snooze again like usual. Closing this issue.
