### ISSUE TITLE
The arrow button from the "Pick a Date/Time" option is small and wrongly shaped

### ISSUE THREAD

**Issue by SoftVision-CarmenFat** [bwinton/SnoozeTabs#402]
[Affected versions]:
- Release 58.0 and up
- Snooze Tabs 1.0.21

[Affected Platforms]:
- All Windows
- All Linux

[Prerequisites]:
- Have a Firefox profile with the latest Snooze Tabs add-on version (https://665-15314951-gh.circle-artifacts.com/0/tmp/circle-artifacts.PS80CkV/addon.xpi) loaded as a temporary add-on.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisite and navigate to a website.
2. Click the "Snooze Tabs" button from the toolbar.
3. Observe the arrow from the "Pick a Date/Time" option.

[Expected result]:
- The arrow is correctly displayed.

[Actual result]:
- The arrow is not photonised correctly: it's smaller than it should be and its shape is not the desired one.

[Notes]:
- Attached a comparison screenshot of the issue and the mock-ups:

![arrow photon](https://user-images.githubusercontent.com/26000308/35401153-65b7fbf4-0201-11e8-8abb-1b2e32baec9c.png)

**Comment by johngruen** [comment]
hmm, that sucks. I think i'll use an svg icon instead of a unicode character.
