### ISSUE TITLE
Unnecessary vertical scrollbar on the options panel

### ISSUE THREAD

**Issue by SoftVision-CarmenFat** [bwinton/SnoozeTabs#403]
[Affected versions]:
- Release 58.0 and up
- Snooze Tabs 1.0.21

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Have a Firefox profile with the latest Snooze Tabs add-on version (https://665-15314951-gh.circle-artifacts.com/0/tmp/circle-artifacts.PS80CkV/addon.xpi) loaded as a temporary add-on.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisite and navigate to a website.
2. Click the "Snooze Tabs" button from the toolbar.
3. Observe the way the options panel is displayed.

[Expected result]:
- The panel is displayed correctly and all buttons are fully visible.

[Actual result]:
- A vertical scroll bar is displayed on the right side of the panel.

[Notes]:
- Attached a screencast of the issue:

![unnecessary scroll vertical](https://user-images.githubusercontent.com/26000308/35401212-8bcb3748-0201-11e8-8a99-a8efe1663b29.gif)

**Comment by lmorchard** [comment]
Huh, I can't seem to reproduce this one, though I'm using Dev Edition 59.0b3. Will try with an unbranded release build

**Comment by johngruen** [comment]
I can't repro this on my mac, but I can look into it.
