### ISSUE TITLE
There is a noticeable delay until the Snooze Tabs panel is displayed when accessing it from the Overflow Menu

### ISSUE THREAD

**Issue by SoftVision-CarmenFat** [bwinton/SnoozeTabs#410]
[Affected versions]:
- Release 58.0 and up
- Snooze Tabs 1.0.21

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Have a Firefox profile with the latest Snooze Tabs add-on version (https://669-15314951-gh.circle-artifacts.com/0/tmp/circle-artifacts.kZdit8p/addon.xpi) loaded as a temporary add-on.
- The Snooze Tabs button is moved to the Overflow Menu.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisite and navigate to a website.
2. Click the "Overflow Menu" button.
3. Click the "Snooze Tabs" option and observe the way the panel is displayed.

[Expected result]:
- The panel is almost instantly displayed.

[Actual result]:
- The panel is displayed with a ~2 seconds delay.

[Notes]:
- Attached a screencast of the issue:

![pin to overflow](https://user-images.githubusercontent.com/26000308/35512317-0a878cd6-0508-11e8-818e-add084cce328.gif)

**Comment by lmorchard** [comment]
I think this is a Firefox issue that we can't influence from the WebExtension. I see it happening with other add-ons.
