### ISSUE TITLE
The current hour on the top of the drop down from the "Pick a Date/Time" panel is wrongly aligned to the left

### ISSUE THREAD

**Issue by SoftVision-CarmenFat** [bwinton/SnoozeTabs#412]
[Affected versions]:
- Release 58.0 and up
- Snooze Tabs 1.0.21

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Have a Firefox profile with the latest Snooze Tabs add-on version (https://669-15314951-gh.circle-artifacts.com/0/tmp/circle-artifacts.kZdit8p/addon.xpi) loaded as a temporary add-on.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisite and navigate to a website.
2. Click the "Snooze Tabs" button from the toolbar.
3. Click on the "Pick a Date/Time" option.
4. Click the "customizable time drop-down" field and observe the current hour on top of the drop-down.

[Expected result]:
- The current hour is centered.

[Actual result]:
- The current hour is aligned to the left.

[Notes]:
- Attached a screencast of the issue:

![aligned to left hour](https://user-images.githubusercontent.com/26000308/35512413-5dc1a8e6-0508-11e8-8891-1862a0577fc0.gif)

**Comment by lmorchard** [comment]
Looks like a small regression from the Photon-y updates in 55ee6adf86e0ed37df2a282ed86c82e9233649c4, will take a look
