### ISSUE TITLE
The :00 minutes numbers are wrongly displayed for the suggested hour on the "Later Today" snooze option

### ISSUE THREAD

**Issue by SoftVision-CarmenFat** [bwinton/SnoozeTabs#414]
[Affected versions]:
- Release 58.0 and up
- Snooze Tabs 1.0.21

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Have a Firefox profile with the latest Snooze Tabs add-on version (https://669-15314951-gh.circle-artifacts.com/0/tmp/circle-artifacts.kZdit8p/addon.xpi) loaded as a temporary add-on.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisite and navigate to a website.
2. Click the "Snooze Tabs" button from the toolbar.
3. Observe the suggested hour for "Later Today" option.

[Expected result]:
- Only the suggested hour is displayed.

[Actual result]:
- :00 minutes are also displayed.     

[Notes]:
- Attached a screenshot of the issue:

![minutes](https://user-images.githubusercontent.com/26000308/35512542-bed33ece-0508-11e8-8728-b0f5663131eb.png)

**Comment by lmorchard** [comment]
This time format was changed for the management panel in #341 - we use the same format here for the Later Today snooze option. Might be a good idea to keep it this way? Otherwise, we can add a second time format to split out this option from the management view
