### ISSUE TITLE
Save snoozed tabs somewhere on uninstall

### ISSUE THREAD

**Issue by lmorchard** [bwinton/SnoozeTabs#42]
We've been talking about skipping full sync to bookmarks with snoozed tabs. But, we should still have a bookmarks folder to which snoozed tabs can be exported on extension uninstall and imported on install. Maybe also as a manual action?

**Comment by ckprice** [comment]
Question: what happens when we uninstall? Should we save those somewhere.

**Comment by ckprice** [comment]
One option that was brought up was to open all snoozed tabs (would probably need to tell the user that happened/is going to happen).

**Comment by sevaan** [comment]
What are our options for communicating with users after uninstall?

On the Test Pilot site we have the survey prompt. Could we put a custom message in that modal?

Another option would be to put something at the end of the tour, or just at the bottom of the experiment description.

**Comment by lmorchard** [comment]
> On the Test Pilot site we have the survey prompt. Could we put a custom message in that modal?

I don't think that option exists right now. Might be worth opening an issue on Test Pilot if we really want it.
