### ISSUE TITLE
 Graduate from Test Pilot!

### ISSUE THREAD

**Issue by wresuolc** [bwinton/SnoozeTabs#421]
Congratulations on a successful Test Pilot run!  We'd like to get this in AMO.  Below are the steps to do that:

-  [x] Drop the UpdateURL.  Just delete the whole line.  Without it specified, it defaults back to AMO.
-  [x] Drop Telemetry.  We need to not send anything to Telemetry.
-  [x] Upload the new add-on to AMO.  When uploading the new add-on be sure to change the "How to distribute" option to be AMO instead of "on your own"
-  [x] Disable the install button on Test Pilot (publish the graduation report)
- [x] Stop building the add-on in Test Pilot
-  [x] Wil can redirect existing users to the AMO version.  They'll get the new version as their browser checks for updates (once a day)

**Comment by lmorchard** [comment]
> Upload the new add-on to AMO. When uploading the new add-on be sure to change the "How to distribute" option to be AMO instead of "on your own"

How does this get done using the Mozilla AMO account? Don't want to do this under my own account

**Comment by wresuolc** [comment]
I can do it if you send me the .xpi.

**Comment by lmorchard** [comment]
[Finally tagged a release for this](https://github.com/bwinton/SnoozeTabs/releases/tag/1.1.0), should have [a copy of the unsigned XPI included](https://github.com/bwinton/SnoozeTabs/releases/download/1.1.0/addon.xpi)

**Comment by wresuolc** [comment]
I tried to upload this and got a conflict on the ID.  I'm asking the AMO folks who owns the ID, but no response yet.  Perhaps it's @bwinton ?

**Comment by lmorchard** [comment]
Hmm, it might actually be me, since we were releasing signed XPIs before the Test Pilot infra using the special Mozilla key came around. Can I turn over ownership of the ID somehow, add team members or whatnot?

**Comment by wresuolc** [comment]
Oh, perfect.  That'll work

**Comment by wresuolc** [comment]
Ok. I uploaded the new version (it's waiting for review), enabled AMO hosting instead of self-hosting, and made Mozilla the owner.

One thing -- I needed to put a license and it doesn't have a LICENSE file so I just made it all rights reserved.  @bwinton if it should be something else, can you add a license file?

**Comment by bwinton** [comment]
MPL maybe?

**Comment by wresuolc** [comment]
Ok, here we are:  https://addons.mozilla.org/en-US/firefox/addon/snoozetabs/

- Marked as MPL now
- Has icons/screenshots/descriptions
- Made Blake the visible author

I'll leave this bug open until we do the rest of the steps.

**Comment by wresuolc** [comment]
For the last bullet point about redirecting users...I don't think that's a thing anymore.  We put the latest version on Test Pilot without the updateURL specified, which means users will update to that, and then future checks will go to AMO.  So, I guess that checkbox is leftover from an old system.

Anyway, we're done here.  Thanks!

**Comment by wresuolc** [comment]
I reopened this but didn't get my comment in.  We never pushed the new tag to the production branch so test pilot users never got the upgrade.  Les pushed it and jbuck put it on test pilot so we should be good here.
