### ISSUE TITLE
Can't snooze a tab in read mode

### ISSUE THREAD

**Issue by emmguyot** [bwinton/SnoozeTabs#424]
When a tab is in read mode, the snooze icon is grayed and I can't snooze it. 
I have to leave the read mode.

**Comment by bwinton** [comment]
Yeah, that's cause the location for things in reader mode is `about:reader?url=https…` which aren't allowed to be snoozed. So there's not a lot I can do here, unfortunately.

**Comment by bwinton** [comment]
(Actually, maybe I can do something here… )
