### ISSUE TITLE
Button badge when a tab is restored

### ISSUE THREAD

**Issue by lmorchard** [bwinton/SnoozeTabs#43]
We can't really bounce the toolbar button or decorate the newly active tab. Beyond that, it would be good to put an indicator on the toolbar button when a tab is restored - maybe a count? maybe just a dot?

**Comment by sevaan** [comment]
Darn.

Okay, since we have some limitations, how about dropping a notification bar...something like this?: https://mozilla.invisionapp.com/share/GK9V7WUVQ

**Comment by bwinton** [comment]
There are no WebExtension APIs to do that.  We could fake it by putting something in the page, but we'ld have to put it in all the pages, and then remove it, which is kinda gross…

We _could_ change the `favIconUrl` of the tab, to decorate it a little?  And I think I remember that Heather's research showed that badging the snoozetabs icon was a clear enough reminder for people.

**Comment by bwinton** [comment]
I've got something that looks like this so far:
![screenshot 2016-12-30 15 19 31](https://cloud.githubusercontent.com/assets/159571/21572092/8c85ae44-cea3-11e6-95e2-a5fd79dc4faa.png)

I think I'll work on it a little more, and show it to Sevaan in person, before sending the pull request, though.  (I also need to ask Sevaan when the badge should go away, and which colour we should make it… 😉)

**Comment by bwinton** [comment]
Soooo… after chatting with Sevaan, we think that this will get people to click on the snoozetabs button too often, in an effort to clear the badge, so badging the tab's favicon would be better.

**Comment by sevaan** [comment]
Soooo... after chatting with Blake and him whipping up a quick prototype, we can flash the favicon in the tab between the site's favicon and the SnoozeTabs bell. When going back and forth, I think it can be pretty eye-catching.

Couple ideas for it that need thinking through still:

- The flashing should go for like 10 seconds, and then stop on the Snooze Tabs icon
-- Or should it end on the site's favicon?
- When the user clicks on the tab, end the flashing immediately and show the site's favicon
- If the user doesn't click on the tab, should we reflash the tab 30 minutes later? An hour later? Every hour until it's clicked on?
