### ISSUE TITLE
Icon color is wrong

### ISSUE THREAD

**Issue by umpirsky** [bwinton/SnoozeTabs#437]
![screenshot from 2018-02-25 12-52-09](https://user-images.githubusercontent.com/208957/36641106-d7437956-1a2a-11e8-89e6-4358a681bb85.png)
![screenshot from 2018-02-25 12-51-58](https://user-images.githubusercontent.com/208957/36641107-d7621a64-1a2a-11e8-81a1-0ea17ceca2c2.png)
![screenshot from 2018-02-25 12-51-48](https://user-images.githubusercontent.com/208957/36641108-d77f341e-1a2a-11e8-90ec-e07f052f1a51.png)

It should use colors from https://design.firefox.com/photon/visuals/color.html#icons-and-other-elements

**Comment by bwinton** [comment]
Looks like this is fixed now…
