### ISSUE TITLE
Snoozing a tab in a context/container wakes the tab in the default container

### ISSUE THREAD

**Issue by hoelzro** [bwinton/SnoozeTabs#438]
"Context/container" refers to https://github.com/mozilla/multi-account-containers

Ex. let's say I snooze my work e-mail tab, which is in the Work context.  When snoozetabs brings it back, the new tab is in the default context, instead of the work context.

**Comment by bwinton** [comment]
I'm just using the [tabs.create()](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/tabs/create) API, which doesn't have any concept of a container, so there's not a lot I can do here. Maybe this is more a request for the containers people to automatically open given urls in specific contexts? 🤷🏻‍♂️

**Comment by unhammer** [comment]
The container extension can already open given urls in specific containers by default, but sometimes we don't want that, e.g. for using containers to switch between multiple accounts on the same site. Also, it's manual work to have to specify for each site. 

Ideally, snooze tabs would remember the container the snoozed site was in and use a `tabs.create({…, container, …)` API. That seems like it should be already possible considering the amount of container-extensions out there. 

And I think it is:
* https://github.com/mozilla/multi-account-containers/wiki/Developer-Documentation has docs on how to get the current container (but really needs some docs on how to use that info)
* https://gitlab.com/mjanetmars/switch-container/-/blob/master/switch_container.js#L52  loops through the available containers (`browser.contextualIdentities`) and then https://gitlab.com/mjanetmars/switch-container/-/blob/master/switch_container.js#L31 opens a tab sending `cookieStoreId:identity` as an argument.

**Comment by bwinton** [comment]
As you might have noticed, I haven't had a lot of time to work on this recently…
So I'm going to put a stake in the ground, and say that I'm not maintaining it anymore, and if someone felt like taking it over and adding this support, I'd be happy to pass it along. 🙂
