### ISSUE TITLE
The bell icon and "x" button from the confirmation bar are not displayed on Send website

### ISSUE THREAD

**Issue by SoftVision-CarmenFat** [bwinton/SnoozeTabs#442]
[Affected versions]:
- Firefox 58.0.2 and above
- Snooze Tabs 1.1.0

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Have a Firefox profile with the latest Snooze Tabs add-on version (https://github.com/bwinton/SnoozeTabs/releases/tag/1.1.0) loaded as a temporary add-on.
- "Ask for confirmation when snoozing tabs" checkbox is checked.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites and navigate to https://send.firefox.com/
2. Click on the "Snooze tabs" toolbar button.
3. Click on one of the snooze options (except "Pick a Date/Time").
4. Observe the confirmation bar.

[Expected result]:
- The confirmation bar is correctly displayed and all its items are visible.

[Actual results]:
- The left (bell icon) and right ("x" button) sides of the confirmation bar are not displayed.

[Notes]:
- For the stage and dev servers of the experiment (https://send.stage.mozaws.net/ and https://send.dev.mozaws.net/), the confirmation bar looks even worse:

![conf bar stage](https://user-images.githubusercontent.com/26000308/36793279-ac790042-1ca5-11e8-86d1-8c39f1cbfa64.gif)

- Attached a screencast of the issue:

![conf bar](https://user-images.githubusercontent.com/26000308/36793284-b1019052-1ca5-11e8-8a34-7a36bd035335.gif)

**Comment by jacktose** [comment]
[Send is no more.](https://blog.mozilla.org/blog/2020/09/17/update-on-firefox-send-and-firefox-notes/) 😢 Can this be replicated on other sites, or just closed?

**Comment by bwinton** [comment]
Let's go for closing. Thanks!
