### ISSUE TITLE
Snooze Tabs icon in Extensions Manager is off-center

### ISSUE THREAD

**Issue by sevaan** [bwinton/SnoozeTabs#444]
Slightly off-center logo:

<img width="47" alt="image" src="https://user-images.githubusercontent.com/473531/36869963-77b6745e-1d6b-11e8-9db8-1a601e914d98.png">

**Comment by bwinton** [comment]
Man, if I haven't fixed this by now, I'm probably not going to. 😉

**Comment by jacktose** [comment]
FWIW, I can't replicate this in about:addons. Is this issue possibly from the old Extensions Manager, and therefore fixed by waiting?

**Comment by bwinton** [comment]
Yeah, could be…
