### ISSUE TITLE
The confirmation bar is not displayed when snoozing Test Pilot website

### ISSUE THREAD

**Issue by SoftVision-CarmenFat** [bwinton/SnoozeTabs#445]
[Affected versions]:
- Firefox 58.0.2 and above
- Snooze Tabs 1.1.0

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Have a Firefox profile with the latest Snooze Tabs add-on version (https://github.com/bwinton/SnoozeTabs/releases/tag/1.1.0) loaded as a temporary add-on.
- "Ask for confirmation when snoozing tabs" checkbox is checked.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites and navigate to https://testpilot.firefox.com/
2. Click on the "Snooze tabs" toolbar button.
3. Click on one of the snooze options (except "Pick a Date/Time").
4. Observe what happens next.

[Expected result]:
- The confirmation bar is displayed.

[Actual results]:
- The confirmation bar is not displayed and the tab is closed.

[Notes]:
- This is also reproducible with the Test Pilot version of Snooze Tabs.
- Attached a screencast of the issue:

![conf bar tp](https://user-images.githubusercontent.com/26000308/36907433-539d794c-1e41-11e8-8f5b-2b8580a5fc2a.gif)

**Comment by lmorchard** [comment]
This is a known issue - if I recall, Test Pilot specifically blocks content (like the notification bar) injected by add-ons for security reasons with CSP. So, we fail back to just snoozing the tab

https://github.com/bwinton/SnoozeTabs/issues/197
