### ISSUE TITLE
Metrics plan

### ISSUE THREAD

**Issue by lmorchard** [bwinton/SnoozeTabs#45]
Need to come up with a firm initial metrics plan. Notes from [acceptance criteria](https://github.com/bwinton/SnoozeTabs/issues/24) as a starting point:

* It should measure each time the snooze panel is opened
* It should measure each time a user choses to snooze
* It should measure which snooze duration is chosen each time
* it should measure custom snooze durations
* It should measure the rate at which snooze tabs wake up
* it should measure if users focus previously snoozed tabs
* it should measure if users close a previously snoozed tab without refocusing
* it should measure if users re-snooze a tab
* it should measure snooze cancellations
* it should measure clicks on currently snoozed tabs
* <strike>it should measure clicks into bookmarks folder from the panel</strike>

**Comment by lmorchard** [comment]
Additional note, here: This plan should result in the production of `docs/metrics.md` in the repo, describing the metrics in a public place. Some examples: [minvid](https://github.com/meandavejustice/min-vid/blob/master/docs/metrics.md); [Tab Center](https://github.com/bwinton/TabCenter/blob/master/docs/metrics.md).

**Comment by johngruen** [comment]
@lmorchard i think final UX does not have any bookmarks folder backing snooze tabs, so that last item is moot

**Comment by ckprice** [comment]
Needs: what are the questions we're asking, and how do we know it's successful. Assigning to Wil and John.
