### ISSUE TITLE
[Enhancement] The "Snooze Tabs" toolbar button's icon does not change to the selected "Themer" add-on toolbar icon color

### ISSUE THREAD

**Issue by Softvision-MariusComan** [bwinton/SnoozeTabs#452]
**[Affected versions]:**
- Firefox 58.0.2 and up

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have a Firefox profile with the latest version of the "Snooze Tabs" add-on (1.0.20) installed.
- Have a Firefox profile with the latest version of the "Themer" add-on (0.0.27 custom build from 08.03.2018) installed from the "about:debugging" page.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites.
2. Click the "Themer" toobar button.
3. Observe the "Snooze Tabs" toolbar button's icon.

**[Expected result]:**
- The icon has the same color as the rest of the toolbar icons.

**[Actual result]:**
- The icon has a different color.

**[Notes]:
- The "Test Pilot", "Firefox Multi-Account Containers" and "Themer" toolbar button icons all change according to the icon color set by the "Themer" add-on.
- Attached a screen recording of the issue: 
![rec of the issue snooze](https://user-images.githubusercontent.com/31243259/37161457-68d5a1a4-22fb-11e8-8e49-ebb0635ce915.gif)

**Comment by lmorchard** [comment]
This is expected behavior: Like most add-ons, the icon for 1.0.20 does not use context-fill and does not adapt to the current theme. [The 1.1.0 version that we're pushing to AMO in the near future](https://github.com/bwinton/SnoozeTabs/releases/tag/1.1.0) should change this by using the Mozilla-specific context-fill feature for the icon.

**Comment by Softvision-MariusComan** [comment]
I have verified this issue with the 1.1.0 build from the comment above and the icon looks ok for the most part. However when I've changed to the browser's dark theme the "Snooze Tabs" icon was too bright. 

Attached a screenshot.

@lmorchard , do you have any thoughts on this?
![issue](https://user-images.githubusercontent.com/31243259/37200595-e53cf214-238d-11e8-80f0-25c41b46d4ee.png)

**Comment by lmorchard** [comment]
Might be worth a separate issue if anyone knows why that happens (I don't)
