### ISSUE TITLE
Check internet access before re-opening tabs

### ISSUE THREAD

**Issue by bubblefoil** [bwinton/SnoozeTabs#457]
When I wake up my laptop at a place without an internet access and it is the time to reopen some tabs, I end up with a bunch of tabs with the yellow warning sign.
Because I use this extension for the things I _want_ to read later, not _have to_ do later, I find reopening tabs this way useless.

**Comment by matijakovacevic** [comment]
good one.
but, the question is, when to reactivate/unsnooze them then?

maybe switch them to group "On next open" ?

**Comment by bubblefoil** [comment]
I think that it could be just a matter of seconds after I wake up my laptop. The browser is already running but the wi-fi adapter takes a moment to re-establish the connection. It might be sufficient to give it several retries and eventually just open the tabs anyway, leaving them empty.

**Comment by bwinton** [comment]
(Tried to mark it as a dupe, but couldn't figure out how…)
