### ISSUE TITLE
Have a snooze option for indefinite time

### ISSUE THREAD

**Issue by dominik-ba** [bwinton/SnoozeTabs#459]
It would be nice to have one more predefined "timeframe" of indefinite time. These tabs would only be opened again manually. This somehow would be similar to the feature of Microsoft Edge to save tabs for later.

**Comment by eiro10** [comment]
These 02 add-ons are doing what you asked for:
[Browse Later](https://addons.mozilla.org/fr/firefox/addon/browselater/)
[SaveForReadLater](https://addons.mozilla.org/fr/firefox/addon/saveforreadlater/)

**Comment by bwinton** [comment]
Yeah, I think this is more like bookmarks, and doesn't really fit what this add-on is trying to do… Thanks for the idea, though!
