### ISSUE TITLE
Allow named snoozes

### ISSUE THREAD

**Issue by mystiquewolf** [bwinton/SnoozeTabs#465]
In Microsoft Edge there is a very useful function that allows you to save tabs for later, and name them. This is not like bookmarks, it doesn't just save the links, it also saves the scroll position and the previous visited pages. Also, allow us to save whole windows at a click of a button. That means that for example we are learning something, but an urgent issue comes at work and we are able to save that tabs, go do it and restore the opened tabs and continue to learn later. Syncing between PCs is also a good feature to be available.

I don't know how much of this can be done by extensions APIs, but please forward to Mozilla everything that you cannot do on my behalf. I believe this is something that many users will love Firefox for.

**Comment by eiro10** [comment]
This is exactly what the great add-on **Session Manager** does before WebExtensions **killed** it.

**Comment by mystiquewolf** [comment]
This feature request would probably be better served by [Tab Stash](https://addons.mozilla.org/bg/firefox/addon/tab-stash/)
