### ISSUE TITLE
backup/restore snoozed tabs

### ISSUE THREAD

**Issue by gherghel** [bwinton/SnoozeTabs#466]
Show me a method to backup snoozed tabs and to restore them later.

**Comment by pdehaan** [comment]
I think this is a dupe of #454

**Comment by AussieGit** [comment]
Is there a workaround to restore my 80 odd tabs from an old profile to a new FF profile? Where is the data saved? I can see a Snoozed Tabs folder in my bookmarks which syncs across but it does not restore the tabs in SnoozeTab itself. Any workaround would really be apprecoated as I am too lazy to manually resnooze..

**Comment by bwinton** [comment]
Closing as a dupe… Thanks for the report!
