### ISSUE TITLE
SnoozeTabs add-on abandoned?

### ISSUE THREAD

**Issue by sNiXx** [bwinton/SnoozeTabs#468]
As it has been several months without any updates, closed issues or merged pull requests:

**Is this project abadoned or can we expect updates in the near future?**

I personally would very much like to see SnoozeTabs continue, as it has much potential and there are some great ideas/feature requests to be found in the open issues.
Would be great if @lmorchard or @bwinton could comment.
Thanks!

**Comment by lmorchard** [comment]
Snooze Tabs graduated from Test Pilot this past spring. That's about when I last worked on it. As far as I'm aware, there are no current plans to resume active development.

https://medium.com/firefox-test-pilot/snooze-tabs-graduation-report-254e0d395887

**Comment by sergeevabc** [comment]
Sad news then…

**Comment by Dimas-sc** [comment]
It'd be nice to integrate it into official Firefox release, add some more functionalities and make it more discoverable. Now that I know how it works I can't live without it.

**Comment by dudeshino** [comment]
So if it graduates, that means they won't work on it? Is it up to the community? I have files a bug a while ago and nothing has happened to fix it...

**Comment by bwinton** [comment]
Yeah, kinda. Both Les and I have moved on to other projects, and don't really have the time to maintain this one. Fortunately, there seem to be a number of add-ons which do similar things. [Snooze Tabby](https://addons.mozilla.org/en-US/firefox/addon/snooze-tabby/) seems to be the one people are talking about most…

**Comment by rdrey** [comment]
To save others some time: Snooze Tabby seems to be more buggy than this Snooze Tabs extension. It only "wakes up" tabs when Firefox restarts, which isn't very useful for someone who has a couple of pinned tabs open at all times.

**Comment by maxsu** [comment]
Snooze Tabby's [domain](snoozetabby.com) is also dead.

SnoozeTabs is currently the most functional snooze addon on firefox OR chrome.

I think this project is worth maintaining and converting to WebExt- but it's definitely in need of more volunteers.

**Comment by bwinton** [comment]
(It should already be a web extension, but I agree more volunteers are needed!)

**Comment by maxsu** [comment]
Oops! I misinterpreted "Should we write this as a WebExtension?  YES!" as saying it was not yet a webex. 

I should test this in chrome. It competes favorably with existing offerings (all closed source), and it would be interesting to see if adding it to the chrome webstore would attract more contributors. OTOH very tempted to say "fuck chrome," lmao 😂
