### ISSUE TITLE
Don't require access to private windows

### ISSUE THREAD

**Issue by jacktose** [bwinton/SnoozeTabs#469]
Firefox 67 added the option to allow each extension to run in private windows, or not. Snooze Tabs, for some reason, requires access to private windows, so users cannot choose. It doesn't seem there should be any reason to block this choice.

![Screen Shot 2019-05-28 at 13 10 41](https://user-images.githubusercontent.com/12414794/58509215-dc97a700-814a-11e9-9a26-32e80620ddb6.png)

**Comment by scheinercc** [comment]
FYI, I can see the option in latest Nightly (new Add-on Manager; https://bugzilla.mozilla.org/show_bug.cgi?id=1555012), but it does not get saved
<img width="430" alt="image" src="https://user-images.githubusercontent.com/817856/59552099-eb44e180-8fc5-11e9-8788-8abf380409b9.png">

**Comment by jacktose** [comment]
Confirmed fixed in 1.1.1 (Ff 7.0.1) or earlier.
