### ISSUE TITLE
Where is the update 1.1.1?

### ISSUE THREAD

**Issue by dwbapst** [bwinton/SnoozeTabs#473]
Firefox Addons says that this app updated in January 2019 to version 1.1.1. 

https://addons.mozilla.org/en-US/firefox/addon/snoozetabs/

Where is this version - it doesn't seem to be on the main branch.

I'm concerned because I am pretty sure one of my non-verified addons are leaking security content and so I'm trying to figure out which addon is doing it. Apparently there were a lot of fake copies of many addons, such as Dark Reader, recently, contianing malware.

https://darkreader.org/blog/attention/

**Comment by rugk** [comment]
Just disable it and then you'll see whether it is this one.

But I agree it should be uploaded here and linked to  https://addons.mozilla.org/firefox/addon/snoozetabs/, which seems the official account now that testpilot is deprecated. Opened a PR https://github.com/bwinton/SnoozeTabs/pull/474 for this now.

**Comment by rugk** [comment]
Note WebExtensions are just ZIP files, so you can inpect them by renaming. On https://addons.mozilla.org/en-US/firefox/addon/snoozetabs/versions/ you can also find all versions, and it says v1.1.1 were "minor security updates".

**Comment by rugk** [comment]
You can e.g. use https://try.diffoscope.org/ to compare the files then.

**Comment by dwbapst** [comment]
Doing a diff though doesn't really explain why the most recent update isn't in this repo... which it should be.

**Comment by bwinton** [comment]
Yeah, I think we lost it when I switched computers a while back. I'll probably release 1.2.0 soon, and that's in this repo, so I'm gonna close this bug.
