### ISSUE TITLE
Is this maintained?

### ISSUE THREAD

**Issue by rugk** [bwinton/SnoozeTabs#475]
Testpilot ended, but this extension is still on AMO, which is good IMHO, because I really like it.

Howerver, you did not link it from here, which is not so nice.

I've opened https://github.com/bwinton/SnoozeTabs/pull/474 to fix that at least.

However, in general there is the question of whether this is maintained.

If not you can [archive this repository](https://help.github.com/articles/archiving-repositories/), to mark it as unmaintained. People then cannot submit PRs and there is a big warning that this is archived.
Remember to add a note to the Readme before to explain that it is unmaintained, and – if you think this is useful – why and probably mention alternatives.

**Comment by bwinton** [comment]
Yeah, it's semi-maintained, in that I've been starting to use it again, and trying to get it building on the new version of CircleCI, but that hasn't been working…

**Comment by rugk** [comment]
Oh okay great though. Could you have a look at https://github.com/bwinton/SnoozeTabs/issues/487 and potentially release a fix for that?

This has been annoying me for some time and I only came ago now (as far as I see/know) to create a bug for that…

**Comment by bwinton** [comment]
If I could build it, yeah, but it's using a really old, unsupported version of Sass, and I haven't had the energy to replace it what with the global pandemic and all. It's still on my radar, but if you wanted to take a stab at getting it building, that would be a massive help!

**Comment by rugk** [comment]
Oh that is the problem okay uff… I doubt I can help much and do have other priorities there, but thanks for your reply in any case! :slightly_smiling_face:

**Comment by bwinton** [comment]
I'll keep on plugging away at it when I can, and hopefully this pandemic will end, and I'll have a little more energy. (Or maybe someone else will fix it in the meantime! 🙂)

**Comment by rugk** [comment]
Sure, take all time you need and stay healthy! :+1:

**Comment by rugk** [comment]
:tada: :+1: :blush:
