### ISSUE TITLE
Add support for file:// URLs

### ISSUE THREAD

**Issue by mystiquewolf** [bwinton/SnoozeTabs#478]
Currently file:// URLs are not supported, although one can bookmark them manually in Firefox, they are not bookmarked when trying to use the add-on.

**Comment by bwinton** [comment]
Unfortunately it's not possible to create a tab and point it to a `file://` url (check the `url` section of [this page](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/tabs/create)), so even though we can snooze them, we're not allowed to wake them up. So, yeah, it's going to have to remain unsupported I'm afraid.
