### ISSUE TITLE
Cannot snooze tabs with Nightly 91.0a1 (2021-06-16)

### ISSUE THREAD

**Issue by gaul** [bwinton/SnoozeTabs#484]
None of my scheduled snoozed tabs reopen either.

**Comment by bwinton** [comment]
Yep. I noticed this too, and am talking with the addons team about it.
(Their last comment was:
> Oops we should fix this regression and evaluate whether it's happening anywhere else. 

so I suspect it'll resolve itself in time. 🙂)

**Comment by bwinton** [comment]
(But I'll leave this open until it starts working again.)

**Comment by gaul** [comment]
Thanks, good to have confirmation that it's not a local configuration problem!

**Comment by gherghel** [comment]
In fact, it works with Nightly 91.0a1 (2021-06-15) but not with Nightly 91.0a1 (2021-06-16) ...... (2021-06-20)
Something happened in between.

**Comment by bwinton** [comment]
And it looks like https://bugzilla.mozilla.org/show_bug.cgi?id=1717006 was fixed about three hours ago, so it should start working again some time tomorrow… (I'll check, and let them know if it doesn't. 🙂)

**Comment by bwinton** [comment]
Uh, it worked, as the 15 tabs that just popped up after I restarted demonstrate. 🤣

**Comment by gaul** [comment]
Confirmed fixed in 91.0a1 (2021-06-26).
