### ISSUE TITLE
Improvement: UX more like Google

### ISSUE THREAD

**Issue by hrdwdmrbl** [bwinton/SnoozeTabs#486]
I think it makes more sense when

1. "Next week" = monday 
![Screen Shot 2021-08-13 at 14 24 50](https://user-images.githubusercontent.com/554881/129402899-a64a6e18-e038-4d9c-9209-7359139a8504.png)
2. Next month = 1st of the month
3. The time picker has one dropdown in increments of 15 minutes.
![Screen Shot 2021-08-13 at 14 24 01](https://user-images.githubusercontent.com/554881/129402844-6e9425b3-609b-40e7-95e8-09e7f54ba1b1.png)

**Comment by Dimas-sc** [comment]
I normaly use "Next week" and "Next month" to check a page one time a month so for me that was not useful, I prefer 1 week or 1 month from now.

**Comment by hrdwdmrbl** [comment]
@Dimas-sc If you did that on the first of every month, then it would work for you :) (But also, just for a laugh, https://xkcd.com/1172/ )

**Comment by hrdwdmrbl** [comment]
Okay, I think we can all agree that no one needs 1 minute precision on the minute wheel. 5 minutes is totally sufficient 99% of the time. 15 minute is sufficient 95% of the time. It should text-editable if the person wants 1 minute precision.

**Comment by bwinton** [comment]
Text-editable isn't one of the options in the component I'm using. But I did change it to 5 minutes just now…
