### ISSUE TITLE
Can't click snooze time in Firefox 93.0a1

### ISSUE THREAD

**Issue by gaul** [bwinton/SnoozeTabs#488]
I cannot select "Later today", "Tomorrow", etc. using Firefox nightly 93.0a1 (2021-08-24).  This is a recent regression.

**Comment by bwinton** [comment]
Well, the code didn't change on my end, so I suspect it's a WebExtension bug. Can you see if there's anything in the Browser Console, and file it [on Bugzilla](https://bugzilla.mozilla.org/enter_bug.cgi?product=WebExtensions&component=General) and post the link here so that I can follow it?

**Comment by gaul** [comment]
Filed https://bugzilla.mozilla.org/show_bug.cgi?id=1727958.

**Comment by gaul** [comment]
This is fixed upstream.
