### ISSUE TITLE
Ensure date selection disallows values in the past

### ISSUE THREAD

**Issue by lmorchard** [bwinton/SnoozeTabs#50]
You can currently pick any date/time in the past. That doesn't make much sense.

**Comment by bwinton** [comment]
Pinging @sevaan for ideas on what to do here…  🙂

**Comment by lmorchard** [comment]
> Pinging @sevaan for ideas on what to do here… 🙂

FWIW, I think he may be out this week.

**Comment by sevaan** [comment]
I'm back at it this week!

Can we just [disable](https://firefoxux.github.io/StyleGuide/#/buttons) the Snooze button anytime the date/time is inactive?

**Comment by bwinton** [comment]
https://twitter.com/bwinton/status/791337794874511360 seems relevant.  😉

(Although yes, I believe that wouldnʼt be _toooo_ hard in this case…)
