### ISSUE TITLE
Snooze Tabs doorhanger no longer displays any snooze options on the latest version (12/19/2016)

### ISSUE THREAD

**Issue by SoftVision-CiprianMuresan** [bwinton/SnoozeTabs#52]
[Affected versions]:
- Nightly 53.0a1
- Snooze Tabs 1.0-dev

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- SnoozeTabs build was created today (12/19/2016) by cloning the repository (master branch).
- SnoozeTabs is loaded as a Temporary Add-on in about:debugging

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites and navigate to a web page.
2. Click the Snooze Tabs button from the browser toolbar.
3. Observe the doorhanger.

[Expected result]:
- The Snooze Tabs doorhanger is displayed and it contains all the snoozing options.

[Actual result]:
- The Snooze Tabs doorhanger is displayed, but no snooze options are in it.

[Notes]:
- Attached a screen recording of the issue:
![snoozetabs doorhanger no longer displays snooze options](https://cloud.githubusercontent.com/assets/18304511/21314974/8fc1e6f8-c602-11e6-9b16-09bfa2f89777.gif)

**Comment by bwinton** [comment]
Hi Ciprian!

I'm still not sure whether this add-on is ready for testing, but if you want to test it you'll need to follow the instructions [here](https://github.com/bwinton/SnoozeTabs#how-to-run)  (Specifially, you need to run `npm run build` or `npm run start` to build it before you can load the `dist` directory as a temporary add-on.)

Thanks!

**Comment by SoftVision-CiprianMuresan** [comment]
I understand that the add-on might not be ready for testing, this is why we have refrained from logging issues that are related to incomplete functionalities. 
However, I built the add-on on Thursday and the doorhanger worked as expected.

**Comment by bwinton** [comment]
The error in the Browser Console says:
```
"Download the React DevTools for a better development experience: https://fb.me/react-devtools"  snooze-content.js:18894:9
SnoozeTabs (FE): fetching items  snooze-content.js:29027:6
SnoozeTabs (FE): fetched items Object {  }  snooze-content.js:29027:6
ReferenceError: React is not defined[Learn More] snooze-content.js:29109:3
	render$1 moz-extension://ff609cbb-f832-45e4-b2fe-7d978a43eb07/popup/snooze-content.js:29109:3
	init moz-extension://ff609cbb-f832-45e4-b2fe-7d978a43eb07/popup/snooze-content.js:29137:3
	<anonymous> moz-extension://ff609cbb-f832-45e4-b2fe-7d978a43eb07/popup/snooze-content.js:29140:1
	<anonymous> moz-extension://ff609cbb-f832-45e4-b2fe-7d978a43eb07/popup/snooze-content.js:1:2
```
tagging @lmorchard, who did most of these changes. 😉

**Comment by lmorchard** [comment]
Yeah, I think [this bit in PR 51 fixes the issue](https://github.com/bwinton/SnoozeTabs/pull/51/files#diff-29d8f6d1c5853fb560604b7501058b89R9), because linting was misconfigured and yelled at me to take that React import out by mistake.

**Comment by lmorchard** [comment]
Actually, since I broke the build, I think I might just pull that fix out of that PR and merge it in to fix things.

**Comment by bwinton** [comment]
👍  (Consider that an rs=me for just merging.)

**Comment by lmorchard** [comment]
The PR I just self-merged *should* fix this

**Comment by bwinton** [comment]
Tested, and it looks fixed for me now.

**Comment by SoftVision-CiprianMuresan** [comment]
The issue is no longer reproducible on the latest Snooze Tabs version (built today, 12/20/2016).
