### ISSUE TITLE
Attempting to snooze special urls causes chaos…

### ISSUE THREAD

**Issue by bwinton** [bwinton/SnoozeTabs#59]
`about:debugging` for instance, can't be restored (nor can `about:newtab` or some others).
So, we snooze it, and it goes away, but we can't open it from the Manage menu, and when its alarm fires, it fails to restore (and is thus lost forever), and the error prevents us from rescheduling the next alarm, so the whole thing breaks!  😢

Maybe we should check our ability to restore a tab before we snooze it?  Or just whitelist http/https urls and only deal with those?

**Comment by sevaan** [comment]
We will need to inform the user if they can't snooze a page. Could we do an error modal saying "This page cannot be snoozed"?

**Comment by lmorchard** [comment]
Maybe rather than an error modal over the whole browser, just display a panel in the pop-up with the message?

**Comment by sevaan** [comment]
Can we disable the icon in the toolbar on these pages to save them having to even open the pan

**Comment by sevaan** [comment]
Can we disable the icon in the toolbar on these pages to save them having to even open the panel?

**Comment by bwinton** [comment]
We should be able to, I believe.

**Comment by sevaan** [comment]
Lets do that then. Thanks!

**Comment by bwinton** [comment]
So, I've got a thing that does this now, but it also prevents people from managing their snoozed tabs when they're on a special tab.  Maybe that's not a huge issue, though.

**Comment by sevaan** [comment]
I don't think it's a huge issue for now. Eventually we'll want to move the list of Snoozed Tabs to the Bookmarks Library for management, and that will be accessible at all times.

**Comment by sevaan** [comment]
After discussing with Blake, who sits across from me at the office...we're going to show the icon in a disabled state, but it will be clickable. However, if the user clicks it the panel will open just to the Manage Tabs pane.

**Comment by SoftVision-EmilPasca** [comment]
Tested this scenario with a local file opened in a new tab and the snooze options were available. 
Shouldn't we have the options disabled also for this kind of tabs? If yes, do you want me to log a separate issue for this or you want me to reopen this?
