### ISSUE TITLE
Add tab-close confirmation modal

### ISSUE THREAD

**Issue by sevaan** [bwinton/SnoozeTabs#60]
After a user clicks a snooze option, we want to inform them that the tab is going to be closed, as well a provide the option to not see the confirmation modal in the future.

UX: https://mozilla.invisionapp.com/share/F29T5JA8S#/211984424_Today_Confirmation

Today: "This tab will close and be reopened today at _time_"
Tomorrow: "This tab will close and be reopened tomorrow at _time_"
This Weekend: "This tab will close and be reopened on _date_ at _time_"
Next Week: "This tab will close and be reopened on _date_ at _time_"
Next Month: "This tab will close and be reopened on _date_ at _time_"
Custom Date/Time: "This tab will close and be reopened on _date_ at _time_"

**Comment by bwinton** [comment]
Given the research results indicating that people wanted to be able to change the time on the confirmation, should we stick with the alert, or should we use an in-page notification dropdown thing at the top of the page?  (Or should we put the confirmation in the popup after you click one of the times?)

**Comment by sevaan** [comment]
How about this:

<img width="893" alt="screen shot 2017-01-06 at 3 40 09 pm" src="https://cloud.githubusercontent.com/assets/473531/21732224/8007f7e8-d426-11e6-8368-d70c359f9b19.png">

**Comment by lmorchard** [comment]
Hate to be that guy again, but: Can we do a notification bar like that from a WebExtension? Maybe we can do something grungy like inject it into the page content, but that seems fraught

**Comment by bwinton** [comment]
So, injecting it into page content seems okay to me in this case, because it should only show up for that tab…

**Comment by sevaan** [comment]
I spoke to Flod regarding the localization of this string and here is his response on how best to break it down:

> the point is: with a variable it's 1 string + 3 variants, 4 strings
> is instead it's 3 strings, like "This tab will be … to you later today at %S", "This tab will be … to you tomorrow at %S", "This tab will be … to you on date at %S"
> 3 string, and they have all the flexibility they need
> last one being "This tab will be … to you on %S at %S"

**Comment by designakt** [comment]
Why does this need to be modal? Seams rather intense for a notifications that is educational and can be opted out off. 
Could it be a confirmation step in the snoozeTab doorhanger where the interaction is started? Like, click on a time, secondary panel slides in with the confirmation...

**Comment by bwinton** [comment]
It's not actually modal, it's just overlaid on top of the page, but having it in the tab (instead of in the doorhanger) links it more closely with the content that will be snoozed.

**Comment by bwinton** [comment]
@sevaan: Turns out we can't open the browserAction panel when the user clicks the link.  Other suggestions for what to do in that case?

**Comment by sevaan** [comment]
> Turns out we can't open the browserAction panel when the user clicks the link. Other suggestions for what to do in that case?

Arghhhh. Well, as discussed with you face-to-face: let's explore hanging the calendar widget in a door hanger off of that link, or possibly a modal over the page.

> (Also, what's the difference between the "Cancel" button and the "x"?)

The cancel button reduces any ambiguity. A user might could surmise that the Ok button and the X do the same thing. Putting a cancel communicates things a bit clearer.

> (Also also, if someone checks the "Don't show this again" checkbox, how will they reverse that decision?)

As discussed, let's try put it at the bottom of the Manage Tabs page. This would remain static in the panel with the list of snoozes scrolling behind it. So a white container, with 8px padding above and below.

<img width="783" alt="screen shot 2017-01-31 at 11 50 44 am" src="https://cloud.githubusercontent.com/assets/473531/22474949/846813d4-e7ab-11e6-90f5-6a59867df614.png">
