### ISSUE TITLE
Cancel snoozed tab when it's clicked & opened from the list?

### ISSUE THREAD

**Issue by lmorchard** [bwinton/SnoozeTabs#62]
When you click a snoozed tab title in the management list, we open it in a tab. Should we also cancel it's scheduled wake alarm at that point?

**Comment by sevaan** [comment]
No. It's a way to access that content, but if a user wants to remove it, they can manually do it from that screen. Let's leave it in the queue.

**Comment by lmorchard** [comment]
Cool, will close this then!
