### ISSUE TITLE
Darken font for panel headers and times

### ISSUE THREAD

**Issue by sevaan** [bwinton/SnoozeTabs#66]
Based on Yura's accessibility review...

> * Panel header (snooze this tab, manage snooze tabs, pick date time) font contrast is a little low (you can see this tool to check how well the font color works with the background - http://webaim.org/resources/contrastchecker/)
> * ^ Same goes for the right column within the snooze times list

Let’s change the colour of these elements to #6E6E6E (instead of #808080). This includes the times and URLs on the Manage tabs panel.

**Comment by bwinton** [comment]
The current patch looks like this…
![Darker text](https://cloud.githubusercontent.com/assets/159571/21729730/5898ef52-d41a-11e6-87ca-a8cc156371cf.png)

**Comment by sevaan** [comment]
Merci

**Comment by bwinton** [comment]
(Let's leave this open until it lands… 😉)
