### ISSUE TITLE
In DevEdition's dark theme, the SnoozeTabs icon should be white

### ISSUE THREAD

**Issue by sevaan** [bwinton/SnoozeTabs#67]
The SnoozeTabs icon in the dark theme for Firefox's DevEdition browser should be white.

![image 2017-01-06 at 12 08 59 pm](https://cloud.githubusercontent.com/assets/473531/21726034/f3d3e916-d408-11e6-98dc-b7419bd10e24.png)

**Comment by bwinton** [comment]
This is currently impossible to do.  I filed [bug 1329242](https://bugzilla.mozilla.org/show_bug.cgi?id=1329242) to add an API or something to WebExtensions, which should let us fix this in the future, but until that's fixed, I vote we close this one as "unfixable"…  😢

**Comment by bwinton** [comment]
It looks like [bug 1329242](https://bugzilla.mozilla.org/show_bug.cgi?id=1329242) has landed, so we should probably look into this at some point…

**Comment by lmorchard** [comment]
Yeah, would be good to not keep closing dupes :)

**Comment by SoftVision-EmilPasca** [comment]
I've checked this on the latest Nightly(56.0a1-20170630030203), the SnoozeTabs icon looks better, however, in my opinion I think we should keep the same color as the other toolbar icons.
![snoozetabs_icon_better](https://user-images.githubusercontent.com/20083658/27736893-bf8b92fa-5dae-11e7-9f9d-179cd11cc5f2.png)

**Comment by terrycloth** [comment]
We could also maybe have a single icon image if there were an opaque background, to ensure sufficient visual contrast.

**Comment by SoftVision-PaulOiegas** [comment]
@lmorchard John just fixed yesterday the Test Pilot button icon to work as expected on all 3 Firefox themes. Maybe we can do the same with the Snooze Tabs one which is not completely adapting to the themes?
Also, bug [1329242 ](https://bugzilla.mozilla.org/show_bug.cgi?id=1329242) that was blocking this, seems to be fixed now.

**Comment by umpirsky** [comment]
In `57.0b4 (64-bit)`:

![snooze-tabs](https://user-images.githubusercontent.com/208957/31052658-72598b10-a68b-11e7-9add-0d71f7f8b738.gif)

**Comment by MikkCZ** [comment]
I am not sure about how DevEdition looks now, but in Nightly 58 with the dark theme the icon is almost invisible. Sometimes I almost forgot to use this instead of pinning the tab, which I was used before installing this experiment.

**Comment by umpirsky** [comment]
Still invisible in `57.0b14 (64-bit)`.

**Comment by tilgovi** [comment]
This doesn't just apply to dark themes. Other icons seem to change if you move them to the tab bar using `Customize...`, but Snooze does not.

**Comment by lmorchard** [comment]
I think this was handled by CSS & SVG updates in https://github.com/bwinton/SnoozeTabs/commit/55ee6adf86e0ed37df2a282ed86c82e9233649c4

**Comment by lmorchard** [comment]
Oof, looks like this is still happening - also #401

**Comment by johngruen** [comment]
@lmorchard this works correctly if you run the add-on through npm run build and load it in about:debugging... it is indeed the signature that causes the issue:

<img width="836" alt="screen shot 2018-01-26 at 12 45 23 pm" src="https://user-images.githubusercontent.com/3323249/35438489-04e38cbc-0297-11e8-87e9-08cfcbf83346.png">
<img width="264" alt="screen shot 2018-01-26 at 12 45 26 pm" src="https://user-images.githubusercontent.com/3323249/35438491-054aa708-0297-11e8-974f-57c5d484b9f9.png">
