### ISSUE TITLE
Calendar overlay should not take up full-width of the panel

### ISSUE THREAD

**Issue by sevaan** [bwinton/SnoozeTabs#68]
Currently the calendar panel overlay looks something like this:

<img width="271" alt="screen shot 2017-01-06 at 3 12 11 pm" src="https://cloud.githubusercontent.com/assets/473531/21731479/8a8d2908-d422-11e6-9e61-55411858f200.png">

This panel should not take up the full width of the Snooze Tabs panel:

<img width="355" alt="image" src="https://cloud.githubusercontent.com/assets/473531/21731499/a79cf3de-d422-11e6-901a-9a4b03187f02.png">

This is to match how overlay panels work elsewhere in Firefox. It provides some context for the user on how they got there, and where they can go back to. Basically the background should grey out slightly as the panel slides out. See History or Synced Tabs when the icon is in the hamburger menu.

**Comment by lmorchard** [comment]
Probably going to knock this one off along with other discrepancies in #101
