### ISSUE TITLE
Allow users to edit default snooze times

### ISSUE THREAD

**Issue by sevaan** [bwinton/SnoozeTabs#69]
Our user research has shown that users want to customize some of the default times provided in the Snooze Tabs panel list.

For example, currently when a user opens the panel they can snooze a tab until tomorrow morning at 9:am. Some users want to bring it back tomorrow morning, but maybe at 10am instead. Right now they would have to go through the Custom Date/Time option which can be tedious.

Instead, if the user clicks on the row, snooze as usual. If, however, they hover over the date in the row, change the hover colour over the date to #009CFC and make it a hyperlink. If they click the link, slide over the panel with the right date selected and the 10 box of the time selector already selected, so they can quickly edit the time and move on.

<img width="934" alt="screen shot 2017-01-06 at 3 16 48 pm" src="https://cloud.githubusercontent.com/assets/473531/21731682/884567a4-d423-11e6-8815-7aef0e6a53e4.png">

**Comment by lmorchard** [comment]
Thinking out loud about how this would work and have a few assumptions (feel free to correct):

* All canned times will be editable. (ie. not just "Tomorrow")

* Edits limited to *time* and we disable date changes - or maybe just offer a time selector?

* The date itself just keeps moving forward. (i.e. Tomorrow is always a day ahead of today, next week is 7 days ahead, etc)

**Comment by sevaan** [comment]
> All canned times will be editable. (ie. not just "Tomorrow")

Correct.

If a user edits the time on a tab, it is for that tab only. If they go to another tab and open it, the pre-canned times will be reset for that tab. In the future we will add the ability to permanently edit times in the options. For now, it's fine as is I think.

> Edits limited to time and we disable date changes - or maybe just offer a time selector?

Incorrect.

We should allow the user to edit the date at this point to. The time field will be selected, but the calendar helps make it clear when it is coming back, and might as well be editable as well, so if I accidentally clicked on an option, or change my mind about when I want it to come back, I don't have to go back first to start over.

> The date itself just keeps moving forward. (i.e. Tomorrow is always a day ahead of today, next week is 7 days ahead, etc).

Correct.

**Comment by lmorchard** [comment]
> > Edits limited to time and we disable date changes - or maybe just offer a time selector?
>
> Incorrect.
>
> We should allow the user to edit the date at this point to. The time field will be selected, but the calendar helps make it clear when it is coming back, and might as well be editable as well, so if I accidentally clicked on an option, or change my mind about when I want it to come back, I don't have to go back first to start over.

Okay, that part I don't understand, then. Say I edit the date/time for "Tomorrow" and set it for 7 days from now. Then I edit the date/time for "Next Week" and set it for tomorrow. What did I just do?
