### ISSUE TITLE
Add confirmation when deleting snoozed tab?

### ISSUE THREAD

**Issue by pdehaan** [bwinton/SnoozeTabs#72]
I just had the issue where I accidentally+eagerly double clicked on a delete icon when deleting a snoozed tab, and accidentally deleted the subsequent snoozed tab which moved to fill the first snoozed tab's position in the list.

Not sure if we want to add some confirmation step, or if that makes the deleting step too interactive.

**Comment by sevaan** [comment]
Idea: To avoid the confirmation step, we could just fade the row out, and change the delete icon to an undo icon...then make the row disappear after like 5-10 seconds. A user can quickly bring it back if they mis-click, but we don't need to add an extra step.

**Comment by wresuolc** [comment]
Related to #114

**Comment by lmorchard** [comment]
Do we have a preferred undo icon to use?

**Comment by ericawright** [comment]
I think these two 'undo's pair well with the bell and the trash can:
https://thenounproject.com/search/?q=undo&i=15363
https://thenounproject.com/search/?q=undo&i=716798

**Comment by wresuolc** [comment]
Let's go with 716798. Thanks!

**Comment by sevaan** [comment]
I think we should just use text that says "Undo". After some thought I don't think it will be clear what this icon means.

**Comment by lmorchard** [comment]
One problem with text: What's "undo" in locales other than en-US, and will it fit in that space?

**Comment by lmorchard** [comment]
Just submitted #276 *with* the undo button icon. I also added strings for a `title` attribute on delete & undo buttons - "Delete" & "Undo" respectively.

But, if that icon doesn't look like a good idea, it's easy to switch to "Undo" text as long as we've got a good l10n fit
