### ISSUE TITLE
Display snoozed tab's site favicon instead of generic icon?

### ISSUE THREAD

**Issue by pdehaan** [bwinton/SnoozeTabs#74]
Probably full of scarier edge cases (low resolution favicons, cross-site-loading, etc), but not sure if the snoozed tab UI should attempt to use the site's favicon instead of the generic [src/icons/nightly.svg](https://github.com/bwinton/SnoozeTabs/blob/b2ea0b116224006ebb5cf82ad1f30c809c5c4683/src/icons/nightly.svg) icon for all results.

![menubar_and_congress_begins_to_search_for_funds_to_help_trump_build_border_wall_-_la_times_and_react_storybook](https://cloud.githubusercontent.com/assets/557895/21737243/e16e66ca-d42b-11e6-8b38-e76733f1a9df.png)

**Comment by sevaan** [comment]
We should be using favicons where available.
