### ISSUE TITLE
Put Snooze Tab UI behind long-press of tab close button ("X")

### ISSUE THREAD

**Issue by chutten** [bwinton/SnoozeTabs#80]
Currently a long-press of the X to close a tab does absolutely nothing. Can we hang (duplicate) the SnoozeTab UI on it? Would it make sense?

I think tying Snoozing a tab to the tab UI will help identify that it's a tab action, not a browser action. It won't be terribly discoverable (or accessible), though, so keeping the default WebExtension toolbar-based UI may be prudent.

(( not necessarily something that can be done with the WebExtensions APIs as they stand (or something that is easily API-able... but food for thought? ))

**Comment by sevaan** [comment]
Hi Chutten,

We currently have a plan to put Snoozes in the context menu for the tab. I don't think it's a good idea to long-press on the close icon as it is easy to make a mistake and lose the tab completely.

One option for tab menus I designed years ago had the favicon become a clickable button with menu options hanging off of it. It's currently just visual decoration, but could be made more useful. Something to think about definitely.

**Comment by sevaan** [comment]
Bwinton just corrected me...context menu for Snoozes is currently implemented in Nightly!

**Comment by ckprice** [comment]
Can't do.
