### ISSUE TITLE
Toolbar button tooltip has the experiment name in lowercase

### ISSUE THREAD

**Issue by SoftVision-CiprianMuresan** [bwinton/SnoozeTabs#82]
[Affected versions]:
- Nightly 53.0a1
- Snooze Tabs 1.0 (built on 1/10/2016)

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Have a Firefox profile with the latest Snooze Tabs add-on version (1.0-dev, built on 1/9/2016) loaded as a temporary add-on.

[Steps to reproduce]:
1. Focus the window with the profile from prerequisites.
2. Hover the Snooze Tabs button from the browser toolbar.
3. Observe the tooltip.

[Expected results]:
- "Snooze Tabs" string is displayed.

[Actual results]:
- The tooltip is in lowercase letters.

[Notes]:
Attached a screenshot:
![tooltip in lowercase](https://cloud.githubusercontent.com/assets/18304511/21810824/0757732c-d756-11e6-94be-dca79f276e29.png)

**Comment by pdehaan** [comment]
This is more obvious if you hide the Snooze Tabs icon behind the hamburglar menu:

![menubar_and_cnn_-_breaking_news__latest_news_and_videos_and_1__npm_start__node_](https://cloud.githubusercontent.com/assets/557895/21867834/d93ed99e-d804-11e6-9ecd-55f54bf5c281.png)

... or, if you have a narrower browser window that hides some toolbar icons behind the &raquo; in the toolbar:

![snoozetabs_and_menubar_and_cnn_-_breaking_news__latest_news_and_videos_and_index_js_ _testpilot-containers](https://cloud.githubusercontent.com/assets/557895/21867870/06f1c914-d805-11e6-8756-482afc5d431d.png)

**Comment by sevaan** [comment]
Let's change the tooltip text to "Snooze tab until..." to match the option in the context menu.
