### ISSUE TITLE
The Snoozed Tabs list display is limited to about 60% of the panel length when snoozetabs button is moved in the Firefox menu

### ISSUE THREAD

**Issue by SoftVision-EmilPasca** [bwinton/SnoozeTabs#83]
[Affected versions]:
- Nightly 53.0a1
- Snooze Tabs 1.0 (built on 1/10/2017)

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Have a Firefox profile with the latest Snooze Tabs add-on version (1.0-dev, built on 1/10/2017) loaded as a temporary add-on.
- Have a few tabs snoozed (>6) in the Manage Snooze Tabs Panel.

[Steps to reproduce]:
1. Right-click on the Snooze Tabs icon in the toolbar and select the "Move to Menu" option from the doorhanger.
2. Click on the Hamburger Menu icon.
3. Click on the Snooze Tabs icon.
4. Click on the Manage Snoozed Tabs button.
5. Observe the Manage Snoozed Tabs panel.

[Expected result]:
- The Snoozed Tabs list fills up the entire space of the panel.

[Actual result]:
- The Snoozed Tabs list fills only about 60% of the panel.

[Notes]:
- This seems to be more of an enhancement than an issue in my opinion. 
- Attached a screen recording of the issue:
![snoozetabs_snoozefrommenu](https://cloud.githubusercontent.com/assets/20083658/21814941/ad1677b0-d763-11e6-84ce-5a762a44a8f6.gif)

**Comment by ckprice** [comment]
@bwinton to update.

**Comment by pdehaan** [comment]
Related: #87

**Comment by SoftVision-EmilPasca** [comment]
The issue is no longer reproducible on the latest Snooze Tabs version  (1.0 built on 01/18/2017).
