### ISSUE TITLE
Sort snoozed tabs list by snooze date?

### ISSUE THREAD

**Issue by pdehaan** [bwinton/SnoozeTabs#84]
Currently I have 4 snoozed tabs. Two of them are set for "Next time Firefox opens" and 2 of them are for specific dates/times. I'm guessing the list is currently sorted by the date they were added. But does it make more/any sense to sort by when they should reopen (since that roughly signals how important they are)?

![firefox_developer_edition_start_page_and_1__npm_run_run__plugin-container_](https://cloud.githubusercontent.com/assets/557895/21821388/3f6de3dc-d728-11e6-8e8b-e929e55c07a5.png)

For example, in the screenshot above, I'd almost expect two tabs sorted first by "Next time Firefox opens", and then the 4th result for Feb 10, 2017, and then finally the 2nd result for ~18.1 years in the future (Feb 9, 2035).

Unrelated, but if the reminder is set for more than X weeks/months, should we change the format from "Day, Month Date, @ Hour" to "Month Date, Year".

**Comment by sevaan** [comment]
Yes, it should be sorted according to when the tab is set to return. The next tab to open should be at the top, and the last to open at the bottom. This is part of the spec: http://i.sevaan.com/1I1O0o2E1G3r

> Unrelated, but if the reminder is set for more than X weeks/months, should we change the format from "Day, Month Date, @ Hour" to "Month Date, Year".

I think the time is still important information to show the user. According to the spec, after "Today" and "Tomorrow" we just "Day, Month Date @ Hour" and only lose the day and just use "Month Date, Year @ Hour" for items on a different calendar year. I think it covers all the cases for now.

**Comment by pdehaan** [comment]
Actually, it looks like we are calling `.sort()` in [/src/lib/components/ManagePanel.js:24](https://github.com/bwinton/SnoozeTabs/blob/bd936846316f7b4b1f03fdc6502827442c07d62b/src/lib/components/ManagePanel.js#L24), although I think the sorting only breaks once I add a "Next Open" snooze since it's trying to do a `sortedEntries.sort((a, b) => a.time - b.time);` where one of the `time` fields is actually a literal string `'next'` and not a timestamp.
