### ISSUE TITLE
Need to figure out what to do when user tries to edit a snoozed tab for "Next time Firefox opens".

### ISSUE THREAD

**Issue by pdehaan** [bwinton/SnoozeTabs#85]
Ref: https://github.com/bwinton/SnoozeTabs/pull/65#discussion_r95435034

---

> Sorry, I don't know where to pin this comment, but the sharp edge case here seems to be managing a "Next time Firefox opens" snoozed tab, when you get back into calendar view.
> ![firefox_developer_edition_and_feat__handle_snoozing_tabs_until_next_open__by_bwinton_ _pull_request__65_ _bwinton_snoozetabs_and_mozilla_-_calendar_-_week_of_jan_9__2017](https://cloud.githubusercontent.com/assets/557895/21820646/6662d34c-d725-11e6-94e2-87992bbef3f6.png)
> ![firefox_developer_edition_and_feat__handle_snoozing_tabs_until_next_open__by_bwinton_ _pull_request__65_ _bwinton_snoozetabs_and_mozilla_-_calendar_-_week_of_jan_9__2017](https://cloud.githubusercontent.com/assets/557895/21820670/7c120b2c-d725-11e6-8ab2-c050ddf712f7.png)

@bwinton replied to said comment with:

> Uh, file a followup bug for that (in the Initial Release milestone), I think. We'll need a new design from @sevaan. (In the meantime, I'm making the time non-clickable. Or, rather, making it so that clicking the time will open the tab, just like clicking anywhere else on that line.)

**Comment by bwinton** [comment]
(We don't let people edit them, currently, but we might want to do something better than just disallowing it.)

**Comment by ckprice** [comment]
Landed the important part. Moving to Next

**Comment by johngruen** [comment]
this is fixed.
