### ISSUE TITLE
Odd "dead zone" when managing big list of snooze tabs

### ISSUE THREAD

**Issue by pdehaan** [bwinton/SnoozeTabs#87]
```
HEAD is now at b31e8b2 feat: Flash the favicon of newly-woken tabs.
```

![menubar_and_the_new_york_times_-_breaking_news__world_news___multimedia_and_1__npm_start__node__and_feat__flash_the_favicon_of_newly-woken_tabs__by_bwinton_ _pull_request__86_ _bwinton_snoozetabs](https://cloud.githubusercontent.com/assets/557895/21868651/a5c55792-d808-11e6-9340-e1ef6395bb7c.png)

![blank_skitch_document](https://cloud.githubusercontent.com/assets/557895/21868602/669c9666-d808-11e6-9d26-299b4c1bd6e6.png)

**Comment by ckprice** [comment]
@bwinton double checking

**Comment by bwinton** [comment]
Yeah, I had a fix for it, but it seems to have gotten lost in one of my rebasings, so I'll just quickly re-create it.
