### ISSUE TITLE
Snoozed private tabs reopen in non-private tabs if no Private browsing window is open

### ISSUE THREAD

**Issue by pdehaan** [bwinton/SnoozeTabs#88]
Found in b31e8b2

---

### Steps to reproduce:
1. Open a regular browsing window.
1. Open a private browsing window and go to http://www.cnn.com.
1. Snooze the private CNN tab to "Real Soon Now!" which should relaunch it after a few seconds.
1. Before the new tab is launched in the private browsing window (created in step 2), close that private browsing session.

### Actual results:
CNN is reopened in the non-private browsing session (created in step 1 above).

### Expected results:
A new Private browsing session browser instance is launched (if one isn't already opened) and the snoozed CNN link is reopened in private browsing mode.

Not sure if we can annotate links as private/public when snoozing them, but we should open them in their pre-snoozed browsing context.

This will be further confused when we also launch [Containers/Spaces](https://github.com/mozilla/testpilot-containers) and user's can have a tab in a Personal/Shopping/Banking tab group. Similarly to the private session above, we should reopen a snoozed "banking" link in their original context.

**Comment by sevaan** [comment]
I believe the plan of action is to disable SnoozeTabs in Private Browsing for now.

**Comment by pdehaan** [comment]
This will also be complicated by the upcoming [Containers](https://github.com/mozilla/testpilot-containers) experiment, where you can open a tab in a specific container (Personal, Shopping, Banking, etc). If we snooze a "Personal" tab, it should probably be reopened in that container in the future. Tricky.
