### ISSUE TITLE
Remove seconds from time picker?

### ISSUE THREAD

**Issue by pdehaan** [bwinton/SnoozeTabs#89]
Currently when snoozin' to a custom time, the Time Picker control supports Hours : Minutes : Seconds.

Seconds may be a bit _too_ granular.
I can't imagine wanting to snooze something until 9:17 AM and exactly 43 seconds.

![menubar_and_github_-_mozilla_testpilot-containers_and_firefox_test_pilot](https://cloud.githubusercontent.com/assets/557895/21870661/5fea0d94-d812-11e6-9820-286b26773e72.png)

**Comment by sevaan** [comment]
Yes, definitely way too granular. We are going to be replacing the Time UI with a single field on the same panel as the calendar.
